name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "@DeltaKroneckerGithub_7854"
    type: trojan
    server: "rested-seahorse.rooster465.autos"
    port: 443
    password: "XG59623478"
    sni: "rested-seahorse.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_6322"
    type: trojan
    server: "kind-grizzly.rooster465.autos"
    port: 443
    password: "PD07395842"
    sni: "kind-grizzly.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_3112"
    type: vless
    server: "149.202.58.99"
    port: 443
    uuid: "b585dc5e-55bf-4a8b-913a-27c9ccac05c3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bab-6.site"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/vws/"
      headers:
        Host: "bab-6.site"
  - name: "@DeltaKroneckerGithub_5188"
    type: trojan
    server: "tolerant-rattler.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "tolerant-rattler.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1884"
    type: vless
    server: "132-243-223-227.sslip.io"
    port: 2101
    uuid: "2edfd299-fd54-4056-9d79-3c99f19bdae1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "132-243-223-227.sslip.io"
    client-fingerprint: "chrome"
    network: grpc
    grpc-opts:
      grpc-service-name: "fi-grpc-test"
  - name: "@DeltaKroneckerGithub_2941"
    type: vless
    server: "45.138.100.226"
    port: 2083
    uuid: "0c6b632a-cd96-4b74-9b51-151e3b5697db"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "45.138.100.226"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "@DeltaKroneckerGithub_5134"
    type: trojan
    server: "novel-mouse.rooster465.autos"
    port: 443
    password: "WG39087154"
    sni: "novel-mouse.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_4775"
    type: trojan
    server: "supreme-leopard.rooster465.autos"
    port: 443
    password: "PD07395842"
    sni: "supreme-leopard.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_9323"
    type: ss
    server: "156.146.38.169"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "@DeltaKroneckerGithub_2098"
    type: vless
    server: "154.17.9.119"
    port: 16378
    uuid: "7bb12326-c2ef-47e9-9aa1-bf56d13d9880"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "3tmj2egtm-fno.49bnithzk8vphybv36d1z1xkzfvogt2m6.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "3tmj2egtm-fno.49bnithzk8vphybv36d1z1xkzfvogt2m6.workers.dev"
  - name: "@DeltaKroneckerGithub_4124"
    type: vless
    server: "05a5f9v5a6cm563ieoye7j-8tnpd.hsysyegegrygvvvdujhh.workers.dev"
    port: 443
    uuid: "527451fe-ee1f-4e6f-94ca-808f055f7c9b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "05a5f9v5a6cm563ieoye7j-8tnpd.hsysyegegrygvvvdujhh.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/vl/ERYN0G44hia16zhR?ed=2560"
      headers:
        Host: "05a5f9v5a6cm563ieoye7j-8tnpd.hsysyegegrygvvvdujhh.workers.dev"
  - name: "@DeltaKroneckerGithub_8054"
    type: trojan
    server: "203.69.207.175"
    port: 8443
    password: "96983eb4-c8f1-316e-ab00-500014ed3d8b"
    sni: "203.69.207.175"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_703"
    type: vless
    server: "169.40.42.212"
    port: 443
    uuid: "d65cc14c-f53f-4fe2-b262-97856601319c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "ios"
    reality-opts:
      public-key: "e2RLf57Li_-MDZGE9ss1BWPgP54mqRb5PfXhW2jcVVg"
      short-id: "c39cc7310a"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_5177"
    type: trojan
    server: "grateful-unicorn.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "grateful-unicorn.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1186"
    type: vless
    server: "38.47.96.220"
    port: 11424
    uuid: "1d16c6e0-1bbe-435b-b661-90043fee999c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "notls.lukongtou.eu.org"
    network: ws
    ws-opts:
      path: "Telegram-WangCai2🇨🇳"
      headers:
        Host: "notls.lukongtou.eu.org"
  - name: "@DeltaKroneckerGithub_6390"
    type: trojan
    server: "nl-trojan.bonds.id"
    port: 443
    password: "96884680-77e6-11eb-8d67-1239d0255272"
    sni: "nl-trojan.bonds.id"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_6158"
    type: trojan
    server: "live-javelin.rooster465.autos"
    port: 443
    password: "PD07395842"
    sni: "live-javelin.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_9902"
    type: vmess
    server: "94.156.170.102"
    port: 110
    uuid: "8e9687fc-a3a7-414a-8676-8e2136797cfe"
    alterId: 0
    cipher: "auto"
    udp: true
  - name: "@DeltaKroneckerGithub_10076"
    type: vmess
    server: "172.64.80.1"
    port: 8443
    uuid: "60441548-b68e-43b2-8191-e3b884be4b3c"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "v2ray1.dozapp.xyz"
    network: ws
    ws-opts:
      path: "/lMnsZUN4/"
      headers:
        Host: "v2ray1.dozapp.xyz"
  - name: "@DeltaKroneckerGithub_874"
    type: vless
    server: "104.18.93.3"
    port: 80
    uuid: "a41322e9-d0f1-4ff1-ac5c-a486e2b680b2"
    udp: true
    network: ws
    ws-opts:
      path: "/2EP6G0LoOvs5eNZj"
      headers:
        Host: "worker3.yahoya44555.workers.dev"
  - name: "@DeltaKroneckerGithub_8924"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_6201"
    type: trojan
    server: "glad-roughy.rooster465.autos"
    port: 443
    password: "NQ26071394"
    sni: "glad-roughy.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_819"
    type: vless
    server: "34.222.2.182"
    port: 50159
    uuid: "8c235628-4c27-44b5-9559-7ab1d53b7ff3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "SX1vaYIIZcbcfO3RrAPhYQ1FAeA7bkcDZJtEDN9pbxw"
      short-id: "94c8a1b378da7250"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_8151"
    type: trojan
    server: "legal-glider.rooster465.autos"
    port: 443
    password: "WG39087154"
    sni: "legal-glider.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1626"
    type: vless
    server: "log.bpminecraft.com"
    port: 8880
    uuid: "1f06dae9-e4cc-4aae-b026-07f7fc81fb56"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.JP.CMLiussss.net"
      headers:
        Host: "spring-fire-a493.251-67d.workers.dev"
  - name: "@DeltaKroneckerGithub_8270"
    type: trojan
    server: "curious-ocelot.rooster465.autos"
    port: 443
    password: "EQ30679154"
    sni: "curious-ocelot.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_6442"
    type: trojan
    server: "firm-krill.rooster465.autos"
    port: 443
    password: "NQ26071394"
    sni: "firm-krill.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_5300"
    type: trojan
    server: "welcome-owl.rooster465.autos"
    port: 443
    password: "FH72359861"
    sni: "welcome-owl.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1398"
    type: vless
    server: "104.17.148.22"
    port: 443
    uuid: "518de0d4-6ce8-4404-80db-23c4a8806128"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ez-5FAAFb.EsmAoi.wORKeRs.DEv"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiQkFLTnhqM2tZTSIsInByb3RvY29sIjoidmwiLCJtb2RlIjoicHJveHlpcCIsInBhbmVsSVBzIjpbXX0="
      headers:
        Host: "ez-5faafb.esmaoi.workers.dev"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_7854"
      - "@DeltaKroneckerGithub_6322"
      - "@DeltaKroneckerGithub_3112"
      - "@DeltaKroneckerGithub_5188"
      - "@DeltaKroneckerGithub_1884"
      - "@DeltaKroneckerGithub_2941"
      - "@DeltaKroneckerGithub_5134"
      - "@DeltaKroneckerGithub_4775"
      - "@DeltaKroneckerGithub_9323"
      - "@DeltaKroneckerGithub_2098"
      - "@DeltaKroneckerGithub_4124"
      - "@DeltaKroneckerGithub_8054"
      - "@DeltaKroneckerGithub_703"
      - "@DeltaKroneckerGithub_5177"
      - "@DeltaKroneckerGithub_1186"
      - "@DeltaKroneckerGithub_6390"
      - "@DeltaKroneckerGithub_6158"
      - "@DeltaKroneckerGithub_9902"
      - "@DeltaKroneckerGithub_10076"
      - "@DeltaKroneckerGithub_874"
      - "@DeltaKroneckerGithub_8924"
      - "@DeltaKroneckerGithub_6201"
      - "@DeltaKroneckerGithub_819"
      - "@DeltaKroneckerGithub_8151"
      - "@DeltaKroneckerGithub_1626"
      - "@DeltaKroneckerGithub_8270"
      - "@DeltaKroneckerGithub_6442"
      - "@DeltaKroneckerGithub_5300"
      - "@DeltaKroneckerGithub_1398"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "@DeltaKroneckerGithub_7854"
      - "@DeltaKroneckerGithub_6322"
      - "@DeltaKroneckerGithub_3112"
      - "@DeltaKroneckerGithub_5188"
      - "@DeltaKroneckerGithub_1884"
      - "@DeltaKroneckerGithub_2941"
      - "@DeltaKroneckerGithub_5134"
      - "@DeltaKroneckerGithub_4775"
      - "@DeltaKroneckerGithub_9323"
      - "@DeltaKroneckerGithub_2098"
      - "@DeltaKroneckerGithub_4124"
      - "@DeltaKroneckerGithub_8054"
      - "@DeltaKroneckerGithub_703"
      - "@DeltaKroneckerGithub_5177"
      - "@DeltaKroneckerGithub_1186"
      - "@DeltaKroneckerGithub_6390"
      - "@DeltaKroneckerGithub_6158"
      - "@DeltaKroneckerGithub_9902"
      - "@DeltaKroneckerGithub_10076"
      - "@DeltaKroneckerGithub_874"
      - "@DeltaKroneckerGithub_8924"
      - "@DeltaKroneckerGithub_6201"
      - "@DeltaKroneckerGithub_819"
      - "@DeltaKroneckerGithub_8151"
      - "@DeltaKroneckerGithub_1626"
      - "@DeltaKroneckerGithub_8270"
      - "@DeltaKroneckerGithub_6442"
      - "@DeltaKroneckerGithub_5300"
      - "@DeltaKroneckerGithub_1398"

rules:
  - MATCH,PROXY
