name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "@DeltaKroneckerGithub_139"
    type: vless
    server: "199.232.173.242"
    port: 443
    uuid: "b0cf4078-96b8-4e11-80a8-0f9352565a16"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "piracy-android.video-streams.org"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/ws"
      headers:
        Host: "piracy-android.video-streams.org"
  - name: "@DeltaKroneckerGithub_4793"
    type: trojan
    server: "helped-grouper.rooster465.autos"
    port: 443
    password: "PD07395842"
    sni: "helped-grouper.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_2749"
    type: vless
    server: "104.21.201.219"
    port: 443
    uuid: "fdc48be3-a615-41ac-8bd1-ed844c931048"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "edgetunnel-4uw.pages.dev"
    client-fingerprint: "unsafe"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "edgetunnel-4uw.pages.dev"
  - name: "@DeltaKroneckerGithub_6216"
    type: trojan
    server: "adapting-basilisk.rooster465.autos"
    port: 443
    password: "CF68213490"
    sni: "adapting-basilisk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_4136"
    type: trojan
    server: "rare-lion.rooster465.autos"
    port: 443
    password: "EQ30679154"
    sni: "rare-lion.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_4671"
    type: trojan
    server: "uk1.test3.net"
    port: 443
    password: "970ec930-48a2-11f0-a318-1239d0255272"
    sni: "uk1.test3.net"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_233"
    type: vless
    server: "104.21.39.30"
    port: 80
    uuid: "7201b2cd-0675-4c1a-9c76-07ca14ffcf08"
    udp: true
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiTEwyZVI5T3BYZDBxTzhPRCIsInByb3RvY29sIjoidmwiLCJtb2RlIjoicHJveHlpcCIsInBhbmVsSVBzIjpbXX0="
      headers:
        Host: "6crihfknlqjdu3yuzco9phspq86dbp6q.christanmoccasin.workers.dev"
  - name: "@DeltaKroneckerGithub_5450"
    type: trojan
    server: "91.199.84.199"
    port: 443
    password: "PD07395842"
    sni: "liberal-salmon.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_7114"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_1560"
    type: vless
    server: "bounded-crammed.video-streams.org"
    port: 443
    uuid: "c7f0b683-61ea-48c5-93f1-783459ba2124"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bounded-crammed.video-streams.org"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/ws"
      headers:
        Host: "bounded-crammed.video-streams.org"
  - name: "@DeltaKroneckerGithub_7760"
    type: ss
    server: "172.64.153.86"
    port: 443
    cipher: "none"
    password: "79960b0b-7d31-4263-8915-6511b0e137a8"
    udp: true
  - name: "@DeltaKroneckerGithub_3972"
    type: trojan
    server: "assuring-werewolf.rooster465.autos"
    port: 443
    password: "NQ26071394"
    sni: "assuring-werewolf.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_3966"
    type: trojan
    server: "intense-basilisk.rooster465.autos"
    port: 443
    password: "IQ68037294"
    sni: "intense-basilisk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_4884"
    type: trojan
    server: "liberal-salmon.rooster465.autos"
    port: 443
    password: "WG39087154"
    sni: "liberal-salmon.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_6514"
    type: ss
    server: "149.22.87.204"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "@DeltaKroneckerGithub_5861"
    type: trojan
    server: "pretty-rat.rooster465.autos"
    port: 443
    password: "PQ05174892"
    sni: "pretty-rat.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_5240"
    type: trojan
    server: "ja262.magiclampcloud.cn"
    port: 59443
    password: "2bec9594deabbce4b0030700e6e916f0"
    sni: "ja262.magiclampcloud.cn"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_4378"
    type: trojan
    server: "51.38.65.155"
    port: 443
    password: "6e73f720-f389-11ef-9fc3-1239d0255272"
    sni: "uk1.test3.net"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_4560"
    type: trojan
    server: "87.121.33.158"
    port: 443
    password: "OD90375861"
    sni: "selected-bison.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_3449"
    type: vless
    server: "8.34.70.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime09.workers.dev"
  - name: "@DeltaKroneckerGithub_6863"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_682"
    type: vless
    server: "23.191.200.207"
    port: 443
    uuid: "a2dad423-4dbe-4f04-a84b-2f5870b6a2c3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "7j3hmlHrEDk3Kjx-dFG3E3jf0c6PZF45trIPFsuKWmI"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_7382"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_7203"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_2531"
    type: vless
    server: "172.67.190.141"
    port: 8880
    uuid: "0787cfdb-9930-4abb-8419-c1b96c3ef628"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "red-snowflake-c399.12-ee1.workers.dev"
  - name: "@DeltaKroneckerGithub_7402"
    type: ss
    server: "156.146.38.168"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "@DeltaKroneckerGithub_4596"
    type: trojan
    server: "normal-pika.rooster465.autos"
    port: 443
    password: "HW85960347"
    sni: "normal-pika.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_5832"
    type: trojan
    server: "194.124.216.55"
    port: 443
    password: "VuyKYqyDTU1GFaxF3o"
    sni: "nl-4.tr202504.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_7106"
    type: ss
    server: "82.38.31.3"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_7768"
    type: ss
    server: "50.62.88.16"
    port: 443
    cipher: "none"
    password: "14b02e2a-8930-4afb-8412-ea4a4954ca5b"
    udp: true
  - name: "@DeltaKroneckerGithub_2318"
    type: vless
    server: "104.24.2.147"
    port: 443
    uuid: "c4edb87e-8544-4fa4-bd1c-b0cda9a34b46"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "a.cwvps.eu.org"
    client-fingerprint: "unsafe"
    network: ws
    ws-opts:
      path: "/ws"
      headers:
        Host: "a.cwvps.eu.org"
  - name: "@DeltaKroneckerGithub_5725"
    type: trojan
    server: "209.248.32.116"
    port: 28121
    password: "i99Cef"
    sni: "ctldl.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_5603"
    type: trojan
    server: "194.99.79.189"
    port: 443
    password: "AE62539071"
    sni: "humorous-parakeet.rooster465.autos"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_139"
      - "@DeltaKroneckerGithub_4793"
      - "@DeltaKroneckerGithub_2749"
      - "@DeltaKroneckerGithub_6216"
      - "@DeltaKroneckerGithub_4136"
      - "@DeltaKroneckerGithub_4671"
      - "@DeltaKroneckerGithub_233"
      - "@DeltaKroneckerGithub_5450"
      - "@DeltaKroneckerGithub_7114"
      - "@DeltaKroneckerGithub_1560"
      - "@DeltaKroneckerGithub_7760"
      - "@DeltaKroneckerGithub_3972"
      - "@DeltaKroneckerGithub_3966"
      - "@DeltaKroneckerGithub_4884"
      - "@DeltaKroneckerGithub_6514"
      - "@DeltaKroneckerGithub_5861"
      - "@DeltaKroneckerGithub_5240"
      - "@DeltaKroneckerGithub_4378"
      - "@DeltaKroneckerGithub_4560"
      - "@DeltaKroneckerGithub_3449"
      - "@DeltaKroneckerGithub_6863"
      - "@DeltaKroneckerGithub_682"
      - "@DeltaKroneckerGithub_7382"
      - "@DeltaKroneckerGithub_7203"
      - "@DeltaKroneckerGithub_2531"
      - "@DeltaKroneckerGithub_7402"
      - "@DeltaKroneckerGithub_4596"
      - "@DeltaKroneckerGithub_5832"
      - "@DeltaKroneckerGithub_7106"
      - "@DeltaKroneckerGithub_7768"
      - "@DeltaKroneckerGithub_2318"
      - "@DeltaKroneckerGithub_5725"
      - "@DeltaKroneckerGithub_5603"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "@DeltaKroneckerGithub_139"
      - "@DeltaKroneckerGithub_4793"
      - "@DeltaKroneckerGithub_2749"
      - "@DeltaKroneckerGithub_6216"
      - "@DeltaKroneckerGithub_4136"
      - "@DeltaKroneckerGithub_4671"
      - "@DeltaKroneckerGithub_233"
      - "@DeltaKroneckerGithub_5450"
      - "@DeltaKroneckerGithub_7114"
      - "@DeltaKroneckerGithub_1560"
      - "@DeltaKroneckerGithub_7760"
      - "@DeltaKroneckerGithub_3972"
      - "@DeltaKroneckerGithub_3966"
      - "@DeltaKroneckerGithub_4884"
      - "@DeltaKroneckerGithub_6514"
      - "@DeltaKroneckerGithub_5861"
      - "@DeltaKroneckerGithub_5240"
      - "@DeltaKroneckerGithub_4378"
      - "@DeltaKroneckerGithub_4560"
      - "@DeltaKroneckerGithub_3449"
      - "@DeltaKroneckerGithub_6863"
      - "@DeltaKroneckerGithub_682"
      - "@DeltaKroneckerGithub_7382"
      - "@DeltaKroneckerGithub_7203"
      - "@DeltaKroneckerGithub_2531"
      - "@DeltaKroneckerGithub_7402"
      - "@DeltaKroneckerGithub_4596"
      - "@DeltaKroneckerGithub_5832"
      - "@DeltaKroneckerGithub_7106"
      - "@DeltaKroneckerGithub_7768"
      - "@DeltaKroneckerGithub_2318"
      - "@DeltaKroneckerGithub_5725"
      - "@DeltaKroneckerGithub_5603"

rules:
  - MATCH,PROXY
