name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "@DeltaKroneckerGithub_895"
    type: vless
    server: "ns.cloudflare.com"
    port: 2095
    uuid: "86c50e3a-5b87-49dd-bd20-03c7f2735e40"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "cnmfangbinxingnmsl.cnmfangbinxing-h.workers.dev"
  - name: "@DeltaKroneckerGithub_3307"
    type: vless
    server: "www.speedtest.net"
    port: 443
    uuid: "b19329df-09d6-4bef-ba4a-5a2700000000"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "netlivpn0004.svsv2626.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN"
      headers:
        Host: "netlivpn0004.svsv2626.workers.dev"
  - name: "@DeltaKroneckerGithub_7524"
    type: trojan
    server: "35.180.10.212"
    port: 443
    password: "IQ68037294"
    sni: "firm-warthog.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_907"
    type: vless
    server: "104.16.72.30"
    port: 443
    uuid: "a8b1d666-d3ba-4b17-90c4-ba7514c74f78"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "xstack.mahanfixe.workers.dev"
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_5292"
    type: trojan
    server: "23.95.14.5"
    port: 443
    password: "2ee85121-31de-4581-a492-eb00f606e392"
    sni: "rc9.freeguard.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_707"
    type: vless
    server: "31.58.50.200"
    port: 8443
    uuid: "813a5411-08ac-4346-888a-992f35acbf89"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tradingview.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "mr5AF0LFyDzYDRoYAwH6QNcHXL77-LoiwRx50ZzU8QU"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_283"
    type: vless
    server: "104.17.147.22"
    port: 443
    uuid: "cf0248f7-afaa-49fd-821e-6adc951df1a5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "BPb-C4AfEfbB.djFvbKjDfV.woRKeRs.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoibzdETUxDZXk3RjNkY1BBIiwicHJvdG9jb2wiOiJ2bCIsIm1vZGUiOiJwcm94eWlwIiwicGFuZWxJUHMiOltdfQ==?ed=2560"
      headers:
        Host: "bpb-c4afefbb.djfvbkjdfv.workers.dev"
  - name: "@DeltaKroneckerGithub_3722"
    type: vless
    server: "cgxgqcheiamna-jks01fidlsnqojwf-s.aliama.workers.dev"
    port: 443
    uuid: "d8c14c5c-a80a-4f6f-a5fb-52071849c443"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "CgxGqchEiAMnA-jkS01FiDlsnqOjwF-S.ALIAmA.WOrKErS.DeV"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiZTFWRGJFS0NUd2F2NkRmIiwicHJvdG9jb2wiOiJ2bCIsIm1vZGUiOiJwcm94eWlwIiwicGFuZWxJUHMiOltdfQ==?ed=2560"
      headers:
        Host: "cgxgqcheiamna-jks01fidlsnqojwf-s.aliama.workers.dev"
  - name: "@DeltaKroneckerGithub_1197"
    type: vless
    server: "www.speedtest.net"
    port: 2053
    uuid: "06823dfb-4ced-425d-a905-3774ee9d5026"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "b22nTzAJtaFvKew6EM2TH68A6030-OGu.HirAd228.WORkErS.DeV"
    network: ws
    ws-opts:
      path: "/vl/34xavP4FSqCtRPNpxO9J"
      headers:
        Host: "b22ntzajtafvkew6em2th68a6030-ogu.hirad228.workers.dev"
  - name: "@DeltaKroneckerGithub_6917"
    type: trojan
    server: "amazed-burro.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "amazed-burro.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_6316"
    type: trojan
    server: "leading-ram.rooster465.autos"
    port: 443
    password: "JT80563429"
    sni: "leading-ram.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_5662"
    type: trojan
    server: "167.114.153.171"
    port: 443
    password: "opentunnel.net-newdday"
    sni: "cat-1.opensvr.net"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_3334"
    type: vless
    server: "95.85.16.34"
    port: 8443
    uuid: "f9a32cc6-7dab-4d36-a839-ea276777dc30"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dsvh58bp.v6d30b.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "dsvh58bp.v6d30b.workers.dev"
  - name: "@DeltaKroneckerGithub_7697"
    type: ss
    server: "sub.danfeng.eu.org"
    port: 443
    cipher: "none"
    password: "79960b0b-7d31-4263-8915-6511b0e137a8"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "/79960b0b-7d31-4263-8915-6511b0e137a8/?ed=2560"
      host: "woshinidie-et3.pages.dev"
      tls: true
  - name: "@DeltaKroneckerGithub_5629"
    type: trojan
    server: "new-antelope.rooster465.autos"
    port: 443
    password: "WG39087154"
    sni: "new-antelope.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_4520"
    type: vless
    server: "104.20.17.127"
    port: 443
    uuid: "50414e45-4c5f-5a45-5553-ef859652a80e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "trex-panel-nubj0s.samifakor.workers.dev"
    client-fingerprint: "ios"
    network: ws
    ws-opts:
      path: "/stream/TrexBridge/ef859652a80e"
      headers:
        Host: "trex-panel-nubj0s.samifakor.workers.dev"
  - name: "@DeltaKroneckerGithub_8222"
    type: ss
    server: "156.146.38.169"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "@DeltaKroneckerGithub_4225"
    type: vless
    server: "104.17.135.117"
    port: 2095
    uuid: "86c50e3a-5b87-49dd-bd20-03c7f2735e40"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "cnmfangbinxing.cnmfangbinxing-1.workers.dev"
  - name: "@DeltaKroneckerGithub_3731"
    type: vless
    server: "107.181.151.241"
    port: 443
    uuid: "317bc783-340f-453c-afb5-b6bf637c0b23"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tradingview.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "fc994ae7eb10"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_4308"
    type: vless
    server: "45.196.201.200"
    port: 443
    uuid: "f75814f6-8f81-4847-b792-168c41f2dc85"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "storage.yandex.net"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "zii4nGNapnFKL6SN8GzWNqFlElBvUCUFUThEP0kFH04"
      short-id: "c6ef72e4635d15a5"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_6611"
    type: trojan
    server: "51.44.167.144"
    port: 443
    password: "FC60532879"
    sni: "immune-earwig.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1562"
    type: vless
    server: "94.139.251.23"
    port: 443
    uuid: "35699c54-9188-4f43-972e-e8e42dbb104e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "6ycuxfrEPsqE9eXZ5_Osbnx4g6hXWmkc8pFuAJkJ4jY"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_1918"
    type: vless
    server: "2.26.78.58"
    port: 443
    uuid: "02ae7872-1c03-4214-8b95-14c126da831e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pro-de.emrata.top"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "F2VfBr2UmjDTErB_oruvW5aIvzH_xGfM2AW5_w-DF0I"
      short-id: ""
  - name: "@DeltaKroneckerGithub_2711"
    type: vless
    server: "95.163.232.183"
    port: 443
    uuid: "5777cec3-89c0-462c-af00-abfe6320dfab"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "5post-gate.x5.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "V6FabatADtcX7aO9KMjGCadJC4LuQ_5nRViab-z-nFQ"
      short-id: "abcd"
    network: grpc
    grpc-opts:
      grpc-service-name: "5post.gate.v1"
  - name: "@DeltaKroneckerGithub_5604"
    type: trojan
    server: "185.244.208.13"
    port: 443
    password: "PD07395842"
    sni: "ace-starling.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_7095"
    type: trojan
    server: "charmed-cheetah.rooster465.autos"
    port: 443
    password: "PD07395842"
    sni: "charmed-cheetah.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1328"
    type: vless
    server: "www.speedtest.net"
    port: 443
    uuid: "mahanvpn-mahanvpn"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "mAhaNrEaliteAm.MaHkHan.iR"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "mAhaNrEaliteAm.MaHkHan.iR"
  - name: "@DeltaKroneckerGithub_1655"
    type: vless
    server: "104.25.242.40"
    port: 443
    uuid: "fe273991-0514-4a16-8ec4-b15ae861c000"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zyzzzoao.xn--fiqv8j.eu.org"
    client-fingerprint: "randomized"
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_2185"
    type: vless
    server: "172.67.143.139"
    port: 8080
    uuid: "18907dc3-7e4c-476f-9ed8-b360db563bf9"
    udp: true
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiN3FOeFprWFkiLCJwcm90b2NvbCI6InZsIiwibW9kZSI6InByZWZpeCIsInBhbmVsSVBzIjpbIlsyYTAyOjg5ODoxNDY6NjQ6Ol0iXX0="
      headers:
        Host: "server8.faway91418.workers.dev"
  - name: "@DeltaKroneckerGithub_2124"
    type: vless
    server: "172.66.216.117"
    port: 443
    uuid: "103744ce-0153-49b1-2eac-d293a6ddd7e2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nahan-mouse-7749.amirsina2026.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/sync"
      headers:
        Host: "nahan-mouse-7749.amirsina2026.workers.dev"
  - name: "@DeltaKroneckerGithub_3299"
    type: vless
    server: "188.114.97.6"
    port: 443
    uuid: "abe50676-d90e-4d13-8344-ee38c21da55a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "SiLeNt-tHUNdEr-8469.sHSFHhdfh.WOrkERS.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiUDF3NHE0c1QiLCJwcm90b2NvbCI6InZsIiwibW9kZSI6InByZWZpeCIsInBhbmVsSVBzIjpbIlsyYTAyOjg5ODoxNDY6NjQ6Ol0iXX0=?ed=2560"
      headers:
        Host: "SiLeNt-tHUNdEr-8469.sHSFHhdfh.WOrkERS.dev"
  - name: "@DeltaKroneckerGithub_7325"
    type: trojan
    server: "upright-hamster.rooster465.autos"
    port: 443
    password: "WG39087154"
    sni: "upright-hamster.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_2444"
    type: vless
    server: "104.18.9.212"
    port: 8443
    uuid: "90a656ff-c77a-4b6d-87f4-a0b2cec91373"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "young-queen-488a.adriansheykhi730.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "young-queen-488a.adriansheykhi730.workers.dev"
  - name: "@DeltaKroneckerGithub_7136"
    type: trojan
    server: "tidy-gelding.rooster465.autos"
    port: 443
    password: "NQ26071394"
    sni: "tidy-gelding.rooster465.autos"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_895"
      - "@DeltaKroneckerGithub_3307"
      - "@DeltaKroneckerGithub_7524"
      - "@DeltaKroneckerGithub_907"
      - "@DeltaKroneckerGithub_5292"
      - "@DeltaKroneckerGithub_707"
      - "@DeltaKroneckerGithub_283"
      - "@DeltaKroneckerGithub_3722"
      - "@DeltaKroneckerGithub_1197"
      - "@DeltaKroneckerGithub_6917"
      - "@DeltaKroneckerGithub_6316"
      - "@DeltaKroneckerGithub_5662"
      - "@DeltaKroneckerGithub_3334"
      - "@DeltaKroneckerGithub_7697"
      - "@DeltaKroneckerGithub_5629"
      - "@DeltaKroneckerGithub_4520"
      - "@DeltaKroneckerGithub_8222"
      - "@DeltaKroneckerGithub_4225"
      - "@DeltaKroneckerGithub_3731"
      - "@DeltaKroneckerGithub_4308"
      - "@DeltaKroneckerGithub_6611"
      - "@DeltaKroneckerGithub_1562"
      - "@DeltaKroneckerGithub_1918"
      - "@DeltaKroneckerGithub_2711"
      - "@DeltaKroneckerGithub_5604"
      - "@DeltaKroneckerGithub_7095"
      - "@DeltaKroneckerGithub_1328"
      - "@DeltaKroneckerGithub_1655"
      - "@DeltaKroneckerGithub_2185"
      - "@DeltaKroneckerGithub_2124"
      - "@DeltaKroneckerGithub_3299"
      - "@DeltaKroneckerGithub_7325"
      - "@DeltaKroneckerGithub_2444"
      - "@DeltaKroneckerGithub_7136"


rules:
  - MATCH,PROXY
