name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "@DeltaKroneckerGithub_1743"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1845"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_1847"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1884"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_2059"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "127.0.0.1"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_2135"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "87d1bfd4-574e-4c96-ad42-0426f27461ff"
    sni: "_acme-challenge.sb.cloudns.biz"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_2256"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_2375"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_2645"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_2670"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_2694"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8ccc5a61-b4f5-4fe4-a394-65890d8f044b"
    sni: "space.byu.id.yxls.eu.cc"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/sg-orcl"
      headers:
        Host: "space.byu.id.yxls.eu.cc"
  - name: "@DeltaKroneckerGithub_3061"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_3135"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "018b8e7b-7813-4dcb-84a5-3c98f1521e00"
    sni: "id1.nathaya.web.id"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/trojan"
  - name: "@DeltaKroneckerGithub_3176"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_3223"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_3374"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_3412"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "HutaoCloud"
    sni: "185.220.238.77"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/api"
  - name: "@DeltaKroneckerGithub_3420"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "018b8e7b-7813-4dcb-84a5-3c98f1521e00"
    sni: "id1.nathaya.web.id"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/trojan"
  - name: "@DeltaKroneckerGithub_3426"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8ccc5a61-b4f5-4fe4-a394-65890d8f044b"
    sni: "space.byu.id.yxls.eu.cc"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/sg-orcl"
  - name: "@DeltaKroneckerGithub_3437"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_3464"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_3618"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_3751"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_3965"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_4035"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_4240"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_4272"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_4324"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_4326"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_4332"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_4335"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_4337"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_4339"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_4342"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_4369"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_4412"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_4414"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_4416"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_4418"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_4420"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "mitivpn"
    sni: "google.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/---@MiTiVPN---@MiTiVPN/---@MiTiVPN---@MiTiVPN/---@MiTiVPN---@MiTiVPN/u-s@MiTiVPN---@MiTiVPN/---@MiTiVPN---@MiTiVPN/---@MiTiVPN---@MiTiVPN"
      headers:
        Host: "3x-mitivpn--mitivpn------mitivpn.global.ssl.fastly.net"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_1743"
      - "@DeltaKroneckerGithub_1845"
      - "@DeltaKroneckerGithub_1847"
      - "@DeltaKroneckerGithub_1884"
      - "@DeltaKroneckerGithub_2059"
      - "@DeltaKroneckerGithub_2135"
      - "@DeltaKroneckerGithub_2256"
      - "@DeltaKroneckerGithub_2375"
      - "@DeltaKroneckerGithub_2645"
      - "@DeltaKroneckerGithub_2670"
      - "@DeltaKroneckerGithub_2694"
      - "@DeltaKroneckerGithub_3061"
      - "@DeltaKroneckerGithub_3135"
      - "@DeltaKroneckerGithub_3176"
      - "@DeltaKroneckerGithub_3223"
      - "@DeltaKroneckerGithub_3374"
      - "@DeltaKroneckerGithub_3412"
      - "@DeltaKroneckerGithub_3420"
      - "@DeltaKroneckerGithub_3426"
      - "@DeltaKroneckerGithub_3437"
      - "@DeltaKroneckerGithub_3464"
      - "@DeltaKroneckerGithub_3618"
      - "@DeltaKroneckerGithub_3751"
      - "@DeltaKroneckerGithub_3965"
      - "@DeltaKroneckerGithub_4035"
      - "@DeltaKroneckerGithub_4240"
      - "@DeltaKroneckerGithub_4272"
      - "@DeltaKroneckerGithub_4324"
      - "@DeltaKroneckerGithub_4326"
      - "@DeltaKroneckerGithub_4332"
      - "@DeltaKroneckerGithub_4335"
      - "@DeltaKroneckerGithub_4337"
      - "@DeltaKroneckerGithub_4339"
      - "@DeltaKroneckerGithub_4342"
      - "@DeltaKroneckerGithub_4369"
      - "@DeltaKroneckerGithub_4412"
      - "@DeltaKroneckerGithub_4414"
      - "@DeltaKroneckerGithub_4416"
      - "@DeltaKroneckerGithub_4418"
      - "@DeltaKroneckerGithub_4420"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "@DeltaKroneckerGithub_1743"
      - "@DeltaKroneckerGithub_1845"
      - "@DeltaKroneckerGithub_1847"
      - "@DeltaKroneckerGithub_1884"
      - "@DeltaKroneckerGithub_2059"
      - "@DeltaKroneckerGithub_2135"
      - "@DeltaKroneckerGithub_2256"
      - "@DeltaKroneckerGithub_2375"
      - "@DeltaKroneckerGithub_2645"
      - "@DeltaKroneckerGithub_2670"
      - "@DeltaKroneckerGithub_2694"
      - "@DeltaKroneckerGithub_3061"
      - "@DeltaKroneckerGithub_3135"
      - "@DeltaKroneckerGithub_3176"
      - "@DeltaKroneckerGithub_3223"
      - "@DeltaKroneckerGithub_3374"
      - "@DeltaKroneckerGithub_3412"
      - "@DeltaKroneckerGithub_3420"
      - "@DeltaKroneckerGithub_3426"
      - "@DeltaKroneckerGithub_3437"
      - "@DeltaKroneckerGithub_3464"
      - "@DeltaKroneckerGithub_3618"
      - "@DeltaKroneckerGithub_3751"
      - "@DeltaKroneckerGithub_3965"
      - "@DeltaKroneckerGithub_4035"
      - "@DeltaKroneckerGithub_4240"
      - "@DeltaKroneckerGithub_4272"
      - "@DeltaKroneckerGithub_4324"
      - "@DeltaKroneckerGithub_4326"
      - "@DeltaKroneckerGithub_4332"
      - "@DeltaKroneckerGithub_4335"
      - "@DeltaKroneckerGithub_4337"
      - "@DeltaKroneckerGithub_4339"
      - "@DeltaKroneckerGithub_4342"
      - "@DeltaKroneckerGithub_4369"
      - "@DeltaKroneckerGithub_4412"
      - "@DeltaKroneckerGithub_4414"
      - "@DeltaKroneckerGithub_4416"
      - "@DeltaKroneckerGithub_4418"
      - "@DeltaKroneckerGithub_4420"

rules:
  - MATCH,PROXY
