name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "@DeltaKroneckerGithub_1835"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1839"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_1958"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1981"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_2040"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "018b8e7b-7813-4dcb-84a5-3c98f1521e00"
    sni: "id1.nathaya.web.id"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/trojan"
  - name: "@DeltaKroneckerGithub_2367"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "letiranbreath-x@^f"
    sni: "0XS3Ced9.zZzqwdBWq.wOrKErS.DEv"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiYmx1NXI3dml6NjB3NW9nZyIsInByb3RvY29sIjoidHIiLCJtb2RlIjoicHJveHlpcCIsInBhbmVsSVBzIjpbIjEwNC4yOC4yNTUuNzQiXX0=?ed=2560"
      headers:
        Host: "0xs3ced9.zzzqwdbwq.workers.dev"
  - name: "@DeltaKroneckerGithub_2400"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "letiranbreath-x@^f"
    sni: "0XS3Ced9.zZzqwdBWq.wOrKErS.DEv"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiYmx1NXI3dml6NjB3NW9nZyIsInByb3RvY29sIjoidHIiLCJtb2RlIjoicHJveHlpcCIsInBhbmVsSVBzIjpbIjEwNC4yOC4yNTUuNzQiXX0=?ed=2560"
      headers:
        Host: "0xs3ced9.zzzqwdbwq.workers.dev"
  - name: "@DeltaKroneckerGithub_2613"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_2657"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "HutaoCloud"
    sni: "185.220.238.77"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/api"
  - name: "@DeltaKroneckerGithub_2786"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "C910E5F2-A662-7CFB-B5A6-5D39DB212CBA"
    sni: "muddy-frost-4e2d.vpnetwork3567.workers.dev"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/?--Telegram--Viturey--Telegram--Viturey--"
      headers:
        Host: "muddy-frost-4e2d.vpnetwork3567.workers.dev"
  - name: "@DeltaKroneckerGithub_2913"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_2966"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "018b8e7b-7813-4dcb-84a5-3c98f1521e00"
    sni: "id1.nathaya.web.id"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/trojan"
  - name: "@DeltaKroneckerGithub_2984"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "018b8e7b-7813-4dcb-84a5-3c98f1521e00"
    sni: "id1.nathaya.web.id"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/trojan"
  - name: "@DeltaKroneckerGithub_2989"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_3007"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_3031"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_3268"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_3552"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_3634"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8ccc5a61-b4f5-4fe4-a394-65890d8f044b"
    sni: "space.byu.id.yxls.eu.cc"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/sg-orcl"
  - name: "@DeltaKroneckerGithub_3681"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_3702"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "MiTiVPN"
    sni: "8373638-mitivpn--mitivpn------mitivpn.mitivpn-s.lifestyle"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/---@MiTiVPN---@MiTiVPN/---@MiTiVPN---@MiTiVPN/---@MiTiVPN---@MiTiVPN/f-l@MiTiVPN---@MiTiVPN/---@MiTiVPN---@MiTiVPN/---@MiTiVPN---@MiTiVPN"
  - name: "@DeltaKroneckerGithub_4149"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_4184"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_4201"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "letiranbreath-x@^f"
    sni: "0XS3Ced9.zZzqwdBWq.wOrKErS.DEv"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiYmx1NXI3dml6NjB3NW9nZyIsInByb3RvY29sIjoidHIiLCJtb2RlIjoicHJveHlpcCIsInBhbmVsSVBzIjpbIjEwNC4yOC4yNTUuNzQiXX0=?ed=2560"
      headers:
        Host: "0xs3ced9.zzzqwdbwq.workers.dev"
  - name: "@DeltaKroneckerGithub_4370"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "87d1bfd4-574e-4c96-ad42-0426f27461ff"
    sni: "_acme-challenge.sb.cloudns.biz"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_4451"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_4484"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_4536"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "letiranbreath-x@^f"
    sni: "0XS3Ced9.zZzqwdBWq.wOrKErS.DEv"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiYmx1NXI3dml6NjB3NW9nZyIsInByb3RvY29sIjoidHIiLCJtb2RlIjoicHJveHlpcCIsInBhbmVsSVBzIjpbIjEwNC4yOC4yNTUuNzQiXX0=?ed=2560"
      headers:
        Host: "0xs3ced9.zzzqwdbwq.workers.dev"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_1835"
      - "@DeltaKroneckerGithub_1839"
      - "@DeltaKroneckerGithub_1958"
      - "@DeltaKroneckerGithub_1981"
      - "@DeltaKroneckerGithub_2040"
      - "@DeltaKroneckerGithub_2367"
      - "@DeltaKroneckerGithub_2400"
      - "@DeltaKroneckerGithub_2613"
      - "@DeltaKroneckerGithub_2657"
      - "@DeltaKroneckerGithub_2786"
      - "@DeltaKroneckerGithub_2913"
      - "@DeltaKroneckerGithub_2966"
      - "@DeltaKroneckerGithub_2984"
      - "@DeltaKroneckerGithub_2989"
      - "@DeltaKroneckerGithub_3007"
      - "@DeltaKroneckerGithub_3031"
      - "@DeltaKroneckerGithub_3268"
      - "@DeltaKroneckerGithub_3552"
      - "@DeltaKroneckerGithub_3634"
      - "@DeltaKroneckerGithub_3681"
      - "@DeltaKroneckerGithub_3702"
      - "@DeltaKroneckerGithub_4149"
      - "@DeltaKroneckerGithub_4184"
      - "@DeltaKroneckerGithub_4201"
      - "@DeltaKroneckerGithub_4370"
      - "@DeltaKroneckerGithub_4451"
      - "@DeltaKroneckerGithub_4484"
      - "@DeltaKroneckerGithub_4536"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "@DeltaKroneckerGithub_1835"
      - "@DeltaKroneckerGithub_1839"
      - "@DeltaKroneckerGithub_1958"
      - "@DeltaKroneckerGithub_1981"
      - "@DeltaKroneckerGithub_2040"
      - "@DeltaKroneckerGithub_2367"
      - "@DeltaKroneckerGithub_2400"
      - "@DeltaKroneckerGithub_2613"
      - "@DeltaKroneckerGithub_2657"
      - "@DeltaKroneckerGithub_2786"
      - "@DeltaKroneckerGithub_2913"
      - "@DeltaKroneckerGithub_2966"
      - "@DeltaKroneckerGithub_2984"
      - "@DeltaKroneckerGithub_2989"
      - "@DeltaKroneckerGithub_3007"
      - "@DeltaKroneckerGithub_3031"
      - "@DeltaKroneckerGithub_3268"
      - "@DeltaKroneckerGithub_3552"
      - "@DeltaKroneckerGithub_3634"
      - "@DeltaKroneckerGithub_3681"
      - "@DeltaKroneckerGithub_3702"
      - "@DeltaKroneckerGithub_4149"
      - "@DeltaKroneckerGithub_4184"
      - "@DeltaKroneckerGithub_4201"
      - "@DeltaKroneckerGithub_4370"
      - "@DeltaKroneckerGithub_4451"
      - "@DeltaKroneckerGithub_4484"
      - "@DeltaKroneckerGithub_4536"

rules:
  - MATCH,PROXY
