name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "@DeltaKroneckerGithub_7907"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "60441548-b68e-43b2-8191-e3b884be4b3c"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "v2ray1.dozapp.xyz"
    network: ws
    ws-opts:
      path: "/lMnsZUN4/"
      headers:
        Host: "v2ray1.dozapp.xyz"
  - name: "@DeltaKroneckerGithub_7909"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "567f4be5-12ab-42e1-b8d9-db6fd1fdd31c"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/vmess/"
      headers:
        Host: "google.com"
  - name: "@DeltaKroneckerGithub_7914"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "mTCKUNDiGePwU3uP.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_7917"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "6JDvArazgU3qQR6Q.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_7934"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "60441548-b68e-43b2-8191-e3b884be4b3c"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "v2ray1.dozapp.xyz"
    network: ws
    ws-opts:
      path: "/lMnsZUN4/"
  - name: "@DeltaKroneckerGithub_7950"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "60441548-b68e-43b2-8191-e3b884be4b3c"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "v2ray1.dozapp.xyz"
    network: ws
    ws-opts:
      path: "/lMnsZUN4/"
      headers:
        Host: "v2ray1.dozapp.xyz"
  - name: "@DeltaKroneckerGithub_7960"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "b9de1bc9-baa7-41ac-86f7-ccd59695cb21"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/arki"
  - name: "@DeltaKroneckerGithub_7965"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "mTCKUNDiGePwU3uP.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_7975"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "DrBKg16eGf3FZlM3.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "DrBKg16eGf3FZlM3.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_7986"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "U2FRxj0G13vDI0Wo.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_7991"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "b15e481d-17e4-41a8-84c2-23d4f0514d9a"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_8013"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vah4urdzl3jdx5r2.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
  - name: "@DeltaKroneckerGithub_8021"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "NYcQg19zkwaCPM1B.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "NYcQg19zkwaCPM1B.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_8025"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "i2psm3knof5qjjix.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "I2PSm3Knof5qjjix.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_8034"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "9db4c708-aef8-4359-821b-38e47990be0d"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_8040"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "wwafj5LHl6bI8aU9.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_8043"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "03fcc618-b93d-6796-6aed-8a38c975d581"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "seribus.org"
    network: ws
    ws-opts:
      path: "linkvws"
      headers:
        Host: "seribus.org"
  - name: "@DeltaKroneckerGithub_8051"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "db50a20e-7ff5-4e70-948f-17cc9ca7c154"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "renderer-stream-2-62.mirra.now"
    network: ws
    ws-opts:
      path: "/api/v1/gpu-stream/socket"
      headers:
        Host: "renderer-stream-2-62.mirra.now"
  - name: "@DeltaKroneckerGithub_8085"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ce0gedpxwou6cqon.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "ce0gedpxwou6cqon.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_8091"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "60441548-b68e-43b2-8191-e3b884be4b3c"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "v2ray1.dozapp.xyz"
    network: ws
    ws-opts:
      path: "/lMnsZUN4/"
      headers:
        Host: "v2ray1.dozapp.xyz"
  - name: "@DeltaKroneckerGithub_8104"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "60441548-b68e-43b2-8191-e3b884be4b3c"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "v2ray1.dozapp.xyz"
    network: ws
    ws-opts:
      path: "/lMnsZUN4/"
      headers:
        Host: "v2ray1.dozapp.xyz"
  - name: "@DeltaKroneckerGithub_8114"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "d187a23a-76a9-4d55-84e3-ea3b8b222cbf"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dimensional-regularly-buildings-keys.trycloudflare.com"
    network: ws
    ws-opts:
      path: "/d187a23a-76a9-4d55-84e3-ea3b8b222cbf-vm"
      headers:
        Host: "dimensional-regularly-buildings-keys.trycloudflare.com"
  - name: "@DeltaKroneckerGithub_8138"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "1bb1f95f-7425-4442-93f7-8fc1bd1a2001"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/v2ray-wisp"
  - name: "@DeltaKroneckerGithub_8150"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "a25cbf11-2908-4a1b-a3a8-9a571777dca3"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/vmess/"
      headers:
        Host: "google.com"
  - name: "@DeltaKroneckerGithub_8160"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "80039b4d-bac0-4f89-82c7-54fad3b0a1ea"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/arki?ed=2048"
  - name: "@DeltaKroneckerGithub_8181"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427-c1f9-4373-876c-2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "6JDvArazgU3qQR6Q.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "6JDvArazgU3qQR6Q.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_8197"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "567f4be5-12ab-42e1-b8d9-db6fd1fdd31c"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/vmess/"
  - name: "@DeltaKroneckerGithub_8208"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "NYcQg19zkwaCPM1B.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "NYcQg19zkwaCPM1B.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_8220"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "60441548-b68e-43b2-8191-e3b884be4b3c"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "v2ray1.dozapp.xyz"
    network: ws
    ws-opts:
      path: "/lMnsZUN4/"
      headers:
        Host: "v2ray1.dozapp.xyz"
  - name: "@DeltaKroneckerGithub_8246"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "b3a11068-1a7e-4643-85de-7c82cce46943"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/vmess-ws"
  - name: "@DeltaKroneckerGithub_8255"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "U2FRxj0G13vDI0Wo.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_8273"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "VAH4URdZL3jDX5r2.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_8276"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f836c736-87fc-4fde-aabc-00857ecdff3e"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/cctv13.m3u8"
  - name: "@DeltaKroneckerGithub_8284"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "6JDvArazgU3qQR6Q.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "6JDvArazgU3qQR6Q.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_8316"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "848af33c-81f2-40c9-93b2-4681d056936b"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "57.131.32.191"
    network: ws
    ws-opts:
      path: "/vmess/"
      headers:
        Host: "OV-Italy1.09vpn.com"
  - name: "@DeltaKroneckerGithub_8325"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "5155860e-d07d-46c3-9128-3afbd84626c7"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/cctv13.m3u8"
  - name: "@DeltaKroneckerGithub_8330"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "11c3627f-31e8-4695-dfbd-34076e2f1f5d"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/cctv13.m3u8"
      headers:
        Host: "None"
  - name: "@DeltaKroneckerGithub_8336"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "drbkg16egf3fzlm3.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "DrBKg16eGf3FZlM3.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_8359"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "60441548-b68e-43b2-8191-e3b884be4b3c"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "v2ray1.dozapp.xyz"
    network: ws
    ws-opts:
      path: "/lMnsZUN4/"
      headers:
        Host: "v2ray1.dozapp.xyz"
  - name: "@DeltaKroneckerGithub_8373"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427-c1f9-4373-876c-2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "NYcQg19zkwaCPM1B.v.3dns.vip"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_7907"
      - "@DeltaKroneckerGithub_7909"
      - "@DeltaKroneckerGithub_7914"
      - "@DeltaKroneckerGithub_7917"
      - "@DeltaKroneckerGithub_7934"
      - "@DeltaKroneckerGithub_7950"
      - "@DeltaKroneckerGithub_7960"
      - "@DeltaKroneckerGithub_7965"
      - "@DeltaKroneckerGithub_7975"
      - "@DeltaKroneckerGithub_7986"
      - "@DeltaKroneckerGithub_7991"
      - "@DeltaKroneckerGithub_8013"
      - "@DeltaKroneckerGithub_8021"
      - "@DeltaKroneckerGithub_8025"
      - "@DeltaKroneckerGithub_8034"
      - "@DeltaKroneckerGithub_8040"
      - "@DeltaKroneckerGithub_8043"
      - "@DeltaKroneckerGithub_8051"
      - "@DeltaKroneckerGithub_8085"
      - "@DeltaKroneckerGithub_8091"
      - "@DeltaKroneckerGithub_8104"
      - "@DeltaKroneckerGithub_8114"
      - "@DeltaKroneckerGithub_8138"
      - "@DeltaKroneckerGithub_8150"
      - "@DeltaKroneckerGithub_8160"
      - "@DeltaKroneckerGithub_8181"
      - "@DeltaKroneckerGithub_8197"
      - "@DeltaKroneckerGithub_8208"
      - "@DeltaKroneckerGithub_8220"
      - "@DeltaKroneckerGithub_8246"
      - "@DeltaKroneckerGithub_8255"
      - "@DeltaKroneckerGithub_8273"
      - "@DeltaKroneckerGithub_8276"
      - "@DeltaKroneckerGithub_8284"
      - "@DeltaKroneckerGithub_8316"
      - "@DeltaKroneckerGithub_8325"
      - "@DeltaKroneckerGithub_8330"
      - "@DeltaKroneckerGithub_8336"
      - "@DeltaKroneckerGithub_8359"
      - "@DeltaKroneckerGithub_8373"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "@DeltaKroneckerGithub_7907"
      - "@DeltaKroneckerGithub_7909"
      - "@DeltaKroneckerGithub_7914"
      - "@DeltaKroneckerGithub_7917"
      - "@DeltaKroneckerGithub_7934"
      - "@DeltaKroneckerGithub_7950"
      - "@DeltaKroneckerGithub_7960"
      - "@DeltaKroneckerGithub_7965"
      - "@DeltaKroneckerGithub_7975"
      - "@DeltaKroneckerGithub_7986"
      - "@DeltaKroneckerGithub_7991"
      - "@DeltaKroneckerGithub_8013"
      - "@DeltaKroneckerGithub_8021"
      - "@DeltaKroneckerGithub_8025"
      - "@DeltaKroneckerGithub_8034"
      - "@DeltaKroneckerGithub_8040"
      - "@DeltaKroneckerGithub_8043"
      - "@DeltaKroneckerGithub_8051"
      - "@DeltaKroneckerGithub_8085"
      - "@DeltaKroneckerGithub_8091"
      - "@DeltaKroneckerGithub_8104"
      - "@DeltaKroneckerGithub_8114"
      - "@DeltaKroneckerGithub_8138"
      - "@DeltaKroneckerGithub_8150"
      - "@DeltaKroneckerGithub_8160"
      - "@DeltaKroneckerGithub_8181"
      - "@DeltaKroneckerGithub_8197"
      - "@DeltaKroneckerGithub_8208"
      - "@DeltaKroneckerGithub_8220"
      - "@DeltaKroneckerGithub_8246"
      - "@DeltaKroneckerGithub_8255"
      - "@DeltaKroneckerGithub_8273"
      - "@DeltaKroneckerGithub_8276"
      - "@DeltaKroneckerGithub_8284"
      - "@DeltaKroneckerGithub_8316"
      - "@DeltaKroneckerGithub_8325"
      - "@DeltaKroneckerGithub_8330"
      - "@DeltaKroneckerGithub_8336"
      - "@DeltaKroneckerGithub_8359"
      - "@DeltaKroneckerGithub_8373"

rules:
  - MATCH,PROXY
