name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "@DeltaKroneckerGithub_4801"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "60441548-b68e-43b2-8191-e3b884be4b3c"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "v2ray1.dozapp.xyz"
    network: ws
    ws-opts:
      path: "/lMnsZUN4/"
      headers:
        Host: "v2ray1.dozapp.xyz"
  - name: "@DeltaKroneckerGithub_4808"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "a7fba54d-1031-4b23-b8b6-dbf8ce6ad3b3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "included-shaw-lean-believe.trycloudflare.com"
    network: ws
    ws-opts:
      path: "/a7fba54d-1031-4b23-b8b6-dbf8ce6ad3b3-vm"
      headers:
        Host: "included-shaw-lean-believe.trycloudflare.com"
  - name: "@DeltaKroneckerGithub_4810"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "60441548-b68e-43b2-8191-e3b884be4b3c"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "v2ray1.dozapp.xyz"
    network: ws
    ws-opts:
      path: "/lMnsZUN4/"
      headers:
        Host: "v2ray1.dozapp.xyz"
  - name: "@DeltaKroneckerGithub_4817"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "DrBKg16eGf3FZlM3.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "DrBKg16eGf3FZlM3.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_4820"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "03fcc618-b93d-6796-6aed-8a38c975d581"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "rush-t2tvv.ceeopp.site"
  - name: "@DeltaKroneckerGithub_4824"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "wwafj5LHl6bI8aU9.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_4829"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427-c1f9-4373-876c-2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "U2FRxj0G13vDI0Wo.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_4835"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "b9de1bc9-baa7-41ac-86f7-ccd59695cb21"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/arki"
  - name: "@DeltaKroneckerGithub_4840"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "60441548-b68e-43b2-8191-e3b884be4b3c"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "v2ray1.dozapp.xyz"
    network: ws
    ws-opts:
      path: "/lMnsZUN4/"
      headers:
        Host: "v2ray1.dozapp.xyz"
  - name: "@DeltaKroneckerGithub_4843"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "93ucrn4i0PffUAbk.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_4847"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "1f01e389-fbcb-494c-e46a-210ec36329c2"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sg.11160321.de5.net"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "sg.11160321.de5.net"
  - name: "@DeltaKroneckerGithub_4852"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ce0gedpxwou6cqon.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "ce0gedpxwou6cqon.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_4855"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lcv8v9l7OyamxxfZ.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "lcv8v9l7OyamxxfZ.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_4865"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "9db4c708-aef8-4359-821b-38e47990be0d"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_4869"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "03fcc618-b93d-6796-6aed-8a38c975d581"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "rush-w1niu.teeopp.online"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "rush-w1niu.teeopp.online"
  - name: "@DeltaKroneckerGithub_4874"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "VAH4URdZL3jDX5r2.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_4880"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "DrBKg16eGf3FZlM3.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "DrBKg16eGf3FZlM3.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_4885"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "60441548-b68e-43b2-8191-e3b884be4b3c"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "v2ray1.dozapp.xyz"
    network: ws
    ws-opts:
      path: "/lMnsZUN4/"
  - name: "@DeltaKroneckerGithub_4889"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "848af33c-81f2-40c9-93b2-4681d056936b"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "57.131.32.191"
    network: ws
    ws-opts:
      path: "/vmess/"
      headers:
        Host: "OV-Italy1.09vpn.com"
  - name: "@DeltaKroneckerGithub_4904"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "567f4be5-12ab-42e1-b8d9-db6fd1fdd31c"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/vmess/"
      headers:
        Host: "google.com"
  - name: "@DeltaKroneckerGithub_4911"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "6ee2a7ba-cd92-427f-ac4f-2f8d284e316c"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "5b22547ba5cc9b83a7a9534b4a7cf9ea.mobgslb.tbcache.com"
  - name: "@DeltaKroneckerGithub_4925"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f836c736-87fc-4fde-aabc-00857ecdff3e"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/cctv13.m3u8"
  - name: "@DeltaKroneckerGithub_4929"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "60441548-b68e-43b2-8191-e3b884be4b3c"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "v2ray1.dozapp.xyz"
    network: ws
    ws-opts:
      path: "/lMnsZUN4/"
      headers:
        Host: "v2ray1.dozapp.xyz"
  - name: "@DeltaKroneckerGithub_4939"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "03fcc618-b93d-6796-6aed-8a38c975d581"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "seribus.org"
    network: ws
    ws-opts:
      path: "linkvws"
      headers:
        Host: "seribus.org"
  - name: "@DeltaKroneckerGithub_4942"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "b15e481d-17e4-41a8-84c2-23d4f0514d9a"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_4950"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "a3e3a710-79f8-4ae0-b83c-607aab40d197"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/vmess/"
      headers:
        Host: "61.245.11.60"
  - name: "@DeltaKroneckerGithub_4952"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "i2psm3knof5qjjix.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "I2PSm3Knof5qjjix.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_4954"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "60441548-b68e-43b2-8191-e3b884be4b3c"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "v2ray1.dozapp.xyz"
    network: ws
    ws-opts:
      path: "/lMnsZUN4/"
      headers:
        Host: "v2ray1.dozapp.xyz"
  - name: "@DeltaKroneckerGithub_4959"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "mTCKUNDiGePwU3uP.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_4965"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "a25cbf11-2908-4a1b-a3a8-9a571777dca3"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/vmess/"
      headers:
        Host: "google.com"
  - name: "@DeltaKroneckerGithub_4967"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427-c1f9-4373-876c-2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "NYcQg19zkwaCPM1B.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_4975"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "11c3627f-31e8-4695-dfbd-34076e2f1f5d"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/cctv13.m3u8"
      headers:
        Host: "jp01.a0a.xyz"
  - name: "@DeltaKroneckerGithub_4977"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "93ucrn4i0PffUAbk.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_4982"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "45b83519-9c4f-4052-a11b-02e017b636d4"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/arki?ed=2048"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_4801"
      - "@DeltaKroneckerGithub_4808"
      - "@DeltaKroneckerGithub_4810"
      - "@DeltaKroneckerGithub_4817"
      - "@DeltaKroneckerGithub_4820"
      - "@DeltaKroneckerGithub_4824"
      - "@DeltaKroneckerGithub_4829"
      - "@DeltaKroneckerGithub_4835"
      - "@DeltaKroneckerGithub_4840"
      - "@DeltaKroneckerGithub_4843"
      - "@DeltaKroneckerGithub_4847"
      - "@DeltaKroneckerGithub_4852"
      - "@DeltaKroneckerGithub_4855"
      - "@DeltaKroneckerGithub_4865"
      - "@DeltaKroneckerGithub_4869"
      - "@DeltaKroneckerGithub_4874"
      - "@DeltaKroneckerGithub_4880"
      - "@DeltaKroneckerGithub_4885"
      - "@DeltaKroneckerGithub_4889"
      - "@DeltaKroneckerGithub_4904"
      - "@DeltaKroneckerGithub_4911"
      - "@DeltaKroneckerGithub_4925"
      - "@DeltaKroneckerGithub_4929"
      - "@DeltaKroneckerGithub_4939"
      - "@DeltaKroneckerGithub_4942"
      - "@DeltaKroneckerGithub_4950"
      - "@DeltaKroneckerGithub_4952"
      - "@DeltaKroneckerGithub_4954"
      - "@DeltaKroneckerGithub_4959"
      - "@DeltaKroneckerGithub_4965"
      - "@DeltaKroneckerGithub_4967"
      - "@DeltaKroneckerGithub_4975"
      - "@DeltaKroneckerGithub_4977"
      - "@DeltaKroneckerGithub_4982"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "@DeltaKroneckerGithub_4801"
      - "@DeltaKroneckerGithub_4808"
      - "@DeltaKroneckerGithub_4810"
      - "@DeltaKroneckerGithub_4817"
      - "@DeltaKroneckerGithub_4820"
      - "@DeltaKroneckerGithub_4824"
      - "@DeltaKroneckerGithub_4829"
      - "@DeltaKroneckerGithub_4835"
      - "@DeltaKroneckerGithub_4840"
      - "@DeltaKroneckerGithub_4843"
      - "@DeltaKroneckerGithub_4847"
      - "@DeltaKroneckerGithub_4852"
      - "@DeltaKroneckerGithub_4855"
      - "@DeltaKroneckerGithub_4865"
      - "@DeltaKroneckerGithub_4869"
      - "@DeltaKroneckerGithub_4874"
      - "@DeltaKroneckerGithub_4880"
      - "@DeltaKroneckerGithub_4885"
      - "@DeltaKroneckerGithub_4889"
      - "@DeltaKroneckerGithub_4904"
      - "@DeltaKroneckerGithub_4911"
      - "@DeltaKroneckerGithub_4925"
      - "@DeltaKroneckerGithub_4929"
      - "@DeltaKroneckerGithub_4939"
      - "@DeltaKroneckerGithub_4942"
      - "@DeltaKroneckerGithub_4950"
      - "@DeltaKroneckerGithub_4952"
      - "@DeltaKroneckerGithub_4954"
      - "@DeltaKroneckerGithub_4959"
      - "@DeltaKroneckerGithub_4965"
      - "@DeltaKroneckerGithub_4967"
      - "@DeltaKroneckerGithub_4975"
      - "@DeltaKroneckerGithub_4977"
      - "@DeltaKroneckerGithub_4982"

rules:
  - MATCH,PROXY
