name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "@DeltaKroneckerGithub_1490"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "7967bf59-57e3-4cde-9898-527b0fe60022"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "speed.dulacloud.store"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/dula?Telegram-WangCai2"
      headers:
        Host: "speed.dulacloud.store"
  - name: "@DeltaKroneckerGithub_1262"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "e5cc16a6-ea42-46b2-82ae-ad2157e1641b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "hhlfy.twiladaphne.ndjp.net"
    network: ws
    ws-opts:
      path: "/fp"
      headers:
        Host: "hhlfy.twiladaphne.ndjp.net"
  - name: "@DeltaKroneckerGithub_295"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "6680846a-8a57-4dfd-9a0e-63209cfc8535"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "support.zoom.us.yxls.eu.cc"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/sg-amz"
      headers:
        Host: "support.zoom.us.yxls.eu.cc"
  - name: "@DeltaKroneckerGithub_508"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "d1yxsk0zprgivr.cloudfront.net"
  - name: "@DeltaKroneckerGithub_1753"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "XpnTeam-15"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ssl.fastly.com"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "Appxdn.global.ssl.fastly.net"
  - name: "@DeltaKroneckerGithub_1237"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "d1yxsk0zprgivr.cloudfront.net"
  - name: "@DeltaKroneckerGithub_964"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "d361072e-9e0e-4e2d-8ec7-2a4189b5b23a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ov.iran-servers.shop"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/J5aLQOY1R9ONWYCM"
      headers:
        Host: "ov.iran-servers.shop"
  - name: "@DeltaKroneckerGithub_3332"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "20ba0c60-0133-11f1-95ef-1239d0255272"
    sni: "uk1.test3.net"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/howdy"
      headers:
        Host: "uk1.test3.net"
  - name: "@DeltaKroneckerGithub_537"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "86c50e3a-5b87-49dd-bd20-03c7f2735e40"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "fuckfangbinxing.pusytroller.gq"
  - name: "@DeltaKroneckerGithub_462"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "03707fb7-0990-440f-88f6-b0e0f7242a38"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "de-new.ariyuz.org"
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_1670"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "fd3ff7be-f277-494b-a651-c210b93f2c19"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "usa1.wba-pn.ru"
    client-fingerprint: "android"
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_1598"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "f1d247db-d7ce-4eb8-9c0d-7b10603cd0b4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ty986gfazs.cainiaohub.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/81574b6b-c9d7-44a0-b83d-dad56e8cb530"
      headers:
        Host: "ty986gfazs.cainiaohub.xyz"
  - name: "@DeltaKroneckerGithub_1011"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "1f619326-cd93-4d6b-aebe-e0b5f8831d02"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "stream.meshbeat.online"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/api/v1/devices/1e0f5220d9/telemetry"
      headers:
        Host: "stream.meshbeat.online"
  - name: "@DeltaKroneckerGithub_3549"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "d272e730-67b2-11f1-9e71-1239d0255272"
    sni: "uk1.test3.NET"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/howdy"
      headers:
        Host: "uk1.test3.NET"
  - name: "@DeltaKroneckerGithub_364"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "d361072e-9e0e-4e2d-8ec7-2a4189b5b23a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ov.iran-servers.shop"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/J5aLQOY1R9ONWYCM"
      headers:
        Host: "ov.iran-servers.shop"
  - name: "@DeltaKroneckerGithub_360"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "e3a625d4-5adb-463d-bbff-bbe06b8e2c5c"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "@DeltaKroneckerGithub_878"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_1328"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "e5cc16a6-ea42-46b2-82ae-ad2157e1641b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "hhlfy.twiladaphne.ndjp.net"
    network: ws
    ws-opts:
      path: "/sg-melbi"
      headers:
        Host: "hhlfy.twiladaphne.ndjp.net"
  - name: "@DeltaKroneckerGithub_314"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "d1yxsk0zprgivr.cloudfront.net"
  - name: "@DeltaKroneckerGithub_1096"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "7a200d36-ba32-4871-8b8a-dd6245dc736b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "shieldwave.uk"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_788"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "e0454af2-6fe9-4983-a55d-05e1da202602"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ssl.fastly.com"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "lsjaoijji.global.ssl.fastly.neT."
  - name: "@DeltaKroneckerGithub_774"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "c7e9c591-2764-423a-afca-efbd010fd396"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "forfreeuse.rtqa.ru"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "forfreeuse.rtqa.ru"
  - name: "@DeltaKroneckerGithub_1424"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "9b18ccef-b9e0-41d1-8990-9d970569e142"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "web-socket.tgdaosheng.ggff.net"
    network: ws
    ws-opts:
      path: "/proxyip=bpb.yousef.isegaro.comfp=chrome"
      headers:
        Host: "web-socket.tgdaosheng.ggff.net"
  - name: "@DeltaKroneckerGithub_3818"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_1073"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "Telegram🇨🇳 @WangCai2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "support.zoom.us.yxls.eu.cc"
    network: ws
    ws-opts:
      path: "/sg-amz"
      headers:
        Host: "support.zoom.us.yxls.eu.cc"
  - name: "@DeltaKroneckerGithub_682"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "77fd4d9e-c314-4203-b3e0-b836a1d969b4"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "rzd.ru"
  - name: "@DeltaKroneckerGithub_338"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "03707fb7-0990-440f-88f6-b0e0f7242a38"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "de-new-1.ariyuz.org"
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_1150"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "37a0bd7c-8b9f-4693-8916-bd1e2da0a817"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_3440"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_2505"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "mJVGfrOkZGnMywJD2uwmuXgOQ"
    sni: "127.0.0.1"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/f2fc2a1f"
      headers:
        Host: "hl-freedom-2.undef.network"
  - name: "@DeltaKroneckerGithub_1326"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "7967bf59-57e3-4cde-9898-527b0fe60022"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "speed.dulacloud.store"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/dula?Telegram-WangCai2"
      headers:
        Host: "speed.dulacloud.store"
  - name: "@DeltaKroneckerGithub_1668"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "c7e9c591-2764-423a-afca-efbd010fd396"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "forfreeuse.rtqa.ru"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "forfreeuse.rtqa.ru"
  - name: "@DeltaKroneckerGithub_1155"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "5956ea09-4f31-4233-a763-fa16ed963666"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "test-production-a548.up.railway.app"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "test-production-a548.up.railway.app"
  - name: "@DeltaKroneckerGithub_121"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "03707fb7-0990-440f-88f6-b0e0f7242a38"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "de-new-1.ariyuz.org"
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_2802"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_1193"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "c7e9c591-2764-423a-afca-efbd010fd396"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "forfreeuse.rtqa.ru"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "forfreeuse.rtqa.ru"
  - name: "@DeltaKroneckerGithub_68"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "7967bf59-57e3-4cde-9898-527b0fe60022"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "speed.dulacloud.store"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/dula?Telegram-WangCai2"
      headers:
        Host: "speed.dulacloud.store"
  - name: "@DeltaKroneckerGithub_3321"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "018b8e7b-7813-4dcb-84a5-3c98f1521e00"
    sni: "id1.nathaya.web.id"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/trojan"
  - name: "@DeltaKroneckerGithub_1177"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "d1yxsk0zprgivr.cloudfront.net"
  - name: "@DeltaKroneckerGithub_179"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "b585dc5e-55bf-4a8b-913a-27c9ccac05c3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bab-6.site"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/vws/"
      headers:
        Host: "bab-6.site"
  - name: "@DeltaKroneckerGithub_930"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "f1d247db-d7ce-4eb8-9c0d-7b10603cd0b4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ty986gfazs.cainiaohub.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/81574b6b-c9d7-44a0-b83d-dad56e8cb530"
      headers:
        Host: "ty986gfazs.cainiaohub.xyz"
  - name: "@DeltaKroneckerGithub_1050"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "03707fb7-0990-440f-88f6-b0e0f7242a38"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "de-new.ariyuz.org"
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_1511"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "7967bf59-57e3-4cde-9898-527b0fe60022"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "speed.dulacloud.store"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/dula?Telegram-WangCai2"
      headers:
        Host: "speed.dulacloud.store"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_1490"
      - "@DeltaKroneckerGithub_1262"
      - "@DeltaKroneckerGithub_295"
      - "@DeltaKroneckerGithub_508"
      - "@DeltaKroneckerGithub_1753"
      - "@DeltaKroneckerGithub_1237"
      - "@DeltaKroneckerGithub_964"
      - "@DeltaKroneckerGithub_3332"
      - "@DeltaKroneckerGithub_537"
      - "@DeltaKroneckerGithub_462"
      - "@DeltaKroneckerGithub_1670"
      - "@DeltaKroneckerGithub_1598"
      - "@DeltaKroneckerGithub_1011"
      - "@DeltaKroneckerGithub_3549"
      - "@DeltaKroneckerGithub_364"
      - "@DeltaKroneckerGithub_360"
      - "@DeltaKroneckerGithub_878"
      - "@DeltaKroneckerGithub_1328"
      - "@DeltaKroneckerGithub_314"
      - "@DeltaKroneckerGithub_1096"
      - "@DeltaKroneckerGithub_788"
      - "@DeltaKroneckerGithub_774"
      - "@DeltaKroneckerGithub_1424"
      - "@DeltaKroneckerGithub_3818"
      - "@DeltaKroneckerGithub_1073"
      - "@DeltaKroneckerGithub_682"
      - "@DeltaKroneckerGithub_338"
      - "@DeltaKroneckerGithub_1150"
      - "@DeltaKroneckerGithub_3440"
      - "@DeltaKroneckerGithub_2505"
      - "@DeltaKroneckerGithub_1326"
      - "@DeltaKroneckerGithub_1668"
      - "@DeltaKroneckerGithub_1155"
      - "@DeltaKroneckerGithub_121"
      - "@DeltaKroneckerGithub_2802"
      - "@DeltaKroneckerGithub_1193"
      - "@DeltaKroneckerGithub_68"
      - "@DeltaKroneckerGithub_3321"
      - "@DeltaKroneckerGithub_1177"
      - "@DeltaKroneckerGithub_179"
      - "@DeltaKroneckerGithub_930"
      - "@DeltaKroneckerGithub_1050"
      - "@DeltaKroneckerGithub_1511"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "@DeltaKroneckerGithub_1490"
      - "@DeltaKroneckerGithub_1262"
      - "@DeltaKroneckerGithub_295"
      - "@DeltaKroneckerGithub_508"
      - "@DeltaKroneckerGithub_1753"
      - "@DeltaKroneckerGithub_1237"
      - "@DeltaKroneckerGithub_964"
      - "@DeltaKroneckerGithub_3332"
      - "@DeltaKroneckerGithub_537"
      - "@DeltaKroneckerGithub_462"
      - "@DeltaKroneckerGithub_1670"
      - "@DeltaKroneckerGithub_1598"
      - "@DeltaKroneckerGithub_1011"
      - "@DeltaKroneckerGithub_3549"
      - "@DeltaKroneckerGithub_364"
      - "@DeltaKroneckerGithub_360"
      - "@DeltaKroneckerGithub_878"
      - "@DeltaKroneckerGithub_1328"
      - "@DeltaKroneckerGithub_314"
      - "@DeltaKroneckerGithub_1096"
      - "@DeltaKroneckerGithub_788"
      - "@DeltaKroneckerGithub_774"
      - "@DeltaKroneckerGithub_1424"
      - "@DeltaKroneckerGithub_3818"
      - "@DeltaKroneckerGithub_1073"
      - "@DeltaKroneckerGithub_682"
      - "@DeltaKroneckerGithub_338"
      - "@DeltaKroneckerGithub_1150"
      - "@DeltaKroneckerGithub_3440"
      - "@DeltaKroneckerGithub_2505"
      - "@DeltaKroneckerGithub_1326"
      - "@DeltaKroneckerGithub_1668"
      - "@DeltaKroneckerGithub_1155"
      - "@DeltaKroneckerGithub_121"
      - "@DeltaKroneckerGithub_2802"
      - "@DeltaKroneckerGithub_1193"
      - "@DeltaKroneckerGithub_68"
      - "@DeltaKroneckerGithub_3321"
      - "@DeltaKroneckerGithub_1177"
      - "@DeltaKroneckerGithub_179"
      - "@DeltaKroneckerGithub_930"
      - "@DeltaKroneckerGithub_1050"
      - "@DeltaKroneckerGithub_1511"

rules:
  - MATCH,PROXY
