name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "@DeltaKroneckerGithub_4396"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8JHppSLSIBA0PK,Nx"
    sni: "8tsmm6NspoCZ3HA9.KHr2DZ0OLa61yDPZE6ZVU7Jhcd4.WORKErS.dEV"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/tr/fsvjN2wOC2fuDFrdawJtWADScC?ed=2560"
      headers:
        Host: "8tsmm6nspocz3ha9.khr2dz0ola61ydpze6zvu7jhcd4.workers.dev"
  - name: "@DeltaKroneckerGithub_4142"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "f6b5a6a3-f3e1-63ca-bb68-bdc400000000"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "netlivpn5505.ffffdsaaa.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN"
      headers:
        Host: "netlivpn5505.ffffdsaaa.workers.dev"
  - name: "@DeltaKroneckerGithub_214"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "cf39fab0-bb85-42cb-9945-2ad69d78e575"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    client-fingerprint: "qq"
    network: ws
    ws-opts:
      path: "/GOrbEh"
  - name: "@DeltaKroneckerGithub_1779"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "273e9057-8167-4d17-8de3-d44c82037cda"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "old-sky-2b90.seyowkclient.workers.dev"
    client-fingerprint: "qq"
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_393"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "a88e61a0-2b38-f6df-c5c7-d20600000000"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "netlivpn5002.whwbbb.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN"
      headers:
        Host: "netlivpn5002.whwbbb.workers.dev"
  - name: "@DeltaKroneckerGithub_2646"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "42c62a5a-cd31-4551-80ef-908732370287"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fq.jp188.dpdns.org"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/proxyip=154.17.22.207,69.63.210.157,134.195.211.13,172.236.245.153,209.146.115.209,64.186.224.194,149.28.94.52,107.151.188.57"
      headers:
        Host: "fq.jp188.dpdns.org"
  - name: "@DeltaKroneckerGithub_2895"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "9b71c9bd-6418-462b-82b4-4a30690e0d47"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ruu2rx-oycdrnsrzc.9uokolpk04vmg2ecqb8oys7.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "ruu2rx-oycdrnsrzc.9uokolpk04vmg2ecqb8oys7.workers.dev"
  - name: "@DeltaKroneckerGithub_1866"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "59b6ac03-2f22-490e-9f97-a6b942b49f60"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "wjwkhoaftdgrt8qus.mp8pmwdgwf3sdapasouszjobjr57nrxxgtx9n.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "wjwkhoaftdgrt8qus.mp8pmwdgwf3sdapasouszjobjr57nrxxgtx9n.workers.dev"
  - name: "@DeltaKroneckerGithub_3646"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "401d950d-4f5c-45c7-bf44-8b69acf35f6f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "7X70yYvt7EqotX-iq9N3RJt1Xn1JWKH9.ASdfSafDSAf.wOrkERs.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoidTBROThObHpLVyIsInByb3RvY29sIjoidmwiLCJtb2RlIjoicHJveHlpcCIsInBhbmVsSVBzIjpbXX0="
      headers:
        Host: "7x70yyvt7eqotx-iq9n3rjt1xn1jwkh9.asdfsafdsaf.workers.dev"
  - name: "@DeltaKroneckerGithub_1212"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "ba1c2531-79de-4c99-9d7d-137360b16a83"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "woc0zvrf11w2endu.dphdlc1u77bs3y4kvussbuap4p576f1ws7igthq8zbf3.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "woc0zvrf11w2endu.dphdlc1u77bs3y4kvussbuap4p576f1ws7igthq8zbf3.workers.dev"
  - name: "@DeltaKroneckerGithub_1684"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "a2eab2e7-af9e-4ea9-a603-05e83aa7bbea"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sxyyvihkektlx4rjxsdj.pkc73phpweu4rbxbatm444.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "sxyyvihkektlx4rjxsdj.pkc73phpweu4rbxbatm444.workers.dev"
  - name: "@DeltaKroneckerGithub_4238"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "50414e45-4c5f-5a45-5553-9568000eed47"
    udp: true
    network: ws
    ws-opts:
      path: "/stream/PANEL_ZEUS/9568000eed47/loc-1"
      headers:
        Host: "urzpn8e9ub5s.shoameni2.workers.dev"
  - name: "@DeltaKroneckerGithub_3589"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime19.workers.dev"
  - name: "@DeltaKroneckerGithub_3358"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "1a56b36c-cea1-45f6-82b7-86c96bf7c8fe"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
  - name: "@DeltaKroneckerGithub_1249"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "c98a16e4-0dc5-42f0-b3db-30f04525c123"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vless2-8vx.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vless2-8vx.pages.dev"
  - name: "@DeltaKroneckerGithub_2215"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "9c70dde1-5f1c-41c4-ac4d-4e740be0df08"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
  - name: "@DeltaKroneckerGithub_183"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "47fcef29-ab4e-4aa6-932b-d95a18f28a4e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "8gjxe.9zuh.7v9.hh.vavava.kdns.fr"
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "8gjxe.9zuh.7v9.hh.vavava.kdns.fr"
  - name: "@DeltaKroneckerGithub_9023"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "db50a20e-7ff5-4e70-948f-17cc9ca7c154"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "renderer-stream-2-62.mirra.now"
    network: ws
    ws-opts:
      path: "/api/v1/gpu-stream/socket"
      headers:
        Host: "renderer-stream-2-62.mirra.now"
  - name: "@DeltaKroneckerGithub_696"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "78b9ac78-ebdf-4e51-8114-f6b0cd6d2169"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sErVER15.PEeKCOnF1-741.wOrkErs.Dev."
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiOUZIcXVMV3FlbnoiLCJwcm90b2NvbCI6InZsIiwibW9kZSI6InByZWZpeCIsInBhbmVsSVBzIjpbIlsyYTAyOjg5ODoxNDY6NjQ6Ol0iLCJbMjYwMjpmYzU5OjExOjY0OjpdIiwiWzI2MDI6ZmM1OTpiMDo2NDo6XSJdfQ==?ed=2560"
      headers:
        Host: "server15.peekconf1-741.workers.dev."
  - name: "@DeltaKroneckerGithub_1340"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "78abbe41-95dd-4f6f-a500-1450913fb933"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "o.SERVeR3PeEkConFIG.WOrKerS.dEv"
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiZ3VVMHdacGtDIiwicHJvdG9jb2wiOiJ2bCIsIm1vZGUiOiJwcmVmaXgiLCJwYW5lbElQcyI6WyJbMmEwMjo4OTg6MTQ2OjY0OjpdIl19?ed"
      headers:
        Host: "o.server3peekconfig.workers.dev"
  - name: "@DeltaKroneckerGithub_1477"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "3076f0f0-558c-cbb3-0570-ca4200000014"
    udp: true
    network: ws
    ws-opts:
      path: "/sync"
      headers:
        Host: "abolfazl-1.danayyabwalfdl6.workers.dev"
  - name: "@DeltaKroneckerGithub_1598"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "42c62a5a-cd31-4551-80ef-908732370287"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fq.jp188.dpdns.org"
    client-fingerprint: "unsafe"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "fq.jp188.dpdns.org"
  - name: "@DeltaKroneckerGithub_457"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "73796e63-0000-4000-8000-000000000007"
    udp: true
    network: ws
    ws-opts:
      path: "/sync"
  - name: "@DeltaKroneckerGithub_4311"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "283665ab-54c2-4c59-ac55-5e8388558eba"
    udp: true
    network: ws
    ws-opts:
      path: "/vl/oCCSZfAWhGqcVO3WOEnIPj9Z9ke?ed"
      headers:
        Host: "27l432tlhnpcojr6u0d3.adfasdfadfasdf.workers.dev"
  - name: "@DeltaKroneckerGithub_2781"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "a22bff60-a40a-4250-bde2-4c660e363b47"
    udp: true
    network: ws
    ws-opts:
      path: "/axch1mttbxz2k55y01"
      headers:
        Host: "index.harmonica01.workers.dev"
  - name: "@DeltaKroneckerGithub_2337"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "44eae030-290b-4083-8102-6f8bab05701b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cfvvv-ev1.pages.dev"
    client-fingerprint: "unsafe"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "cfvvv-ev1.pages.dev"
  - name: "@DeltaKroneckerGithub_2234"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp58.cc.cd"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/TelegramU0001F1E8U0001F1F3@VPNine1fp=chrome"
      headers:
        Host: "vp58.cc.cd"
  - name: "@DeltaKroneckerGithub_1092"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "b8d8a5b0-867f-4491-b4e4-30edc04bb10e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "u.srilankangrill.online"
    client-fingerprint: "unsafe"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "u.srilankangrill.online"
  - name: "@DeltaKroneckerGithub_565"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "9c4306d6-3232-4b01-96df-4dc7dd90be77"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "mw5qisav.wjwqvie0wb1eqhb8e83clqdoq3m5p9a4on.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "mw5qisav.wjwqvie0wb1eqhb8e83clqdoq3m5p9a4on.workers.dev"
  - name: "@DeltaKroneckerGithub_853"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "47fcef29-ab4e-4aa6-932b-d95a18f28a4e"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560security=tls"
      headers:
        Host: "8nj2r.2k8t.f88.hh.vavava.kdns.fr"
  - name: "@DeltaKroneckerGithub_3660"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "47fcef29-ab4e-4aa6-932b-d95a18f28a4e"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560security=tls"
      headers:
        Host: "8nj2r.2k8t.f88.hh.vavava.kdns.fr"
  - name: "@DeltaKroneckerGithub_2514"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "47fcef29-ab4e-4aa6-932b-d95a18f28a4e"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "8nj2r.2k8t.f88.hh.vavava.kdns.fr"
  - name: "@DeltaKroneckerGithub_4754"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_2580"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "07821f66-cdb7-4c70-9de6-e230cffac470"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "wgrcqwtkfyqujs43.ghydgdbdbddvv.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/vl/-i10VPN-i10VPN-i10VPN-i10VPN-i10VPN-i10VPN-i10VPN-i10VPN-i10VPN-i10VPN-i10VPN-i10VPN-i10VPN-i10VPN-i10VPN?ed"
  - name: "@DeltaKroneckerGithub_3665"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "767b6340-96dc-4aa0-8013-a8af7513d920"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "c7dabe95.proxy-978.pages.dev"
    client-fingerprint: "random"
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "c7dabe95.proxy-978.pages.dev"
  - name: "@DeltaKroneckerGithub_5201"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "Telegram_healer_config"
    sni: "tO6R63-kkCHIgHQM2.vXZ0dDUq7to7SU0cdQF.wOrKERS.Dev"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/tr/yqf0HmXRcvB67eWDKZARhVo4Ts4?ed=2560"
  - name: "@DeltaKroneckerGithub_3116"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "54502a61-2af6-40e7-8331-2c9fc40e5903"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "old-cloud-a96a.rohamsahh90.workers.dev"
    client-fingerprint: "ios"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "old-cloud-a96a.rohamsahh90.workers.dev"
  - name: "@DeltaKroneckerGithub_4129"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "2388e166-3890-33ae-f77e-efac00000002"
    udp: true
    network: ws
    ws-opts:
      path: "/NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN"
      headers:
        Host: "netlivpn4813.ddhshhshs.workers.dev"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_4396"
      - "@DeltaKroneckerGithub_4142"
      - "@DeltaKroneckerGithub_214"
      - "@DeltaKroneckerGithub_1779"
      - "@DeltaKroneckerGithub_393"
      - "@DeltaKroneckerGithub_2646"
      - "@DeltaKroneckerGithub_2895"
      - "@DeltaKroneckerGithub_1866"
      - "@DeltaKroneckerGithub_3646"
      - "@DeltaKroneckerGithub_1212"
      - "@DeltaKroneckerGithub_1684"
      - "@DeltaKroneckerGithub_4238"
      - "@DeltaKroneckerGithub_3589"
      - "@DeltaKroneckerGithub_3358"
      - "@DeltaKroneckerGithub_1249"
      - "@DeltaKroneckerGithub_2215"
      - "@DeltaKroneckerGithub_183"
      - "@DeltaKroneckerGithub_9023"
      - "@DeltaKroneckerGithub_696"
      - "@DeltaKroneckerGithub_1340"
      - "@DeltaKroneckerGithub_1477"
      - "@DeltaKroneckerGithub_1598"
      - "@DeltaKroneckerGithub_457"
      - "@DeltaKroneckerGithub_4311"
      - "@DeltaKroneckerGithub_2781"
      - "@DeltaKroneckerGithub_2337"
      - "@DeltaKroneckerGithub_2234"
      - "@DeltaKroneckerGithub_1092"
      - "@DeltaKroneckerGithub_565"
      - "@DeltaKroneckerGithub_853"
      - "@DeltaKroneckerGithub_3660"
      - "@DeltaKroneckerGithub_2514"
      - "@DeltaKroneckerGithub_4754"
      - "@DeltaKroneckerGithub_2580"
      - "@DeltaKroneckerGithub_3665"
      - "@DeltaKroneckerGithub_5201"
      - "@DeltaKroneckerGithub_3116"
      - "@DeltaKroneckerGithub_4129"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "@DeltaKroneckerGithub_4396"
      - "@DeltaKroneckerGithub_4142"
      - "@DeltaKroneckerGithub_214"
      - "@DeltaKroneckerGithub_1779"
      - "@DeltaKroneckerGithub_393"
      - "@DeltaKroneckerGithub_2646"
      - "@DeltaKroneckerGithub_2895"
      - "@DeltaKroneckerGithub_1866"
      - "@DeltaKroneckerGithub_3646"
      - "@DeltaKroneckerGithub_1212"
      - "@DeltaKroneckerGithub_1684"
      - "@DeltaKroneckerGithub_4238"
      - "@DeltaKroneckerGithub_3589"
      - "@DeltaKroneckerGithub_3358"
      - "@DeltaKroneckerGithub_1249"
      - "@DeltaKroneckerGithub_2215"
      - "@DeltaKroneckerGithub_183"
      - "@DeltaKroneckerGithub_9023"
      - "@DeltaKroneckerGithub_696"
      - "@DeltaKroneckerGithub_1340"
      - "@DeltaKroneckerGithub_1477"
      - "@DeltaKroneckerGithub_1598"
      - "@DeltaKroneckerGithub_457"
      - "@DeltaKroneckerGithub_4311"
      - "@DeltaKroneckerGithub_2781"
      - "@DeltaKroneckerGithub_2337"
      - "@DeltaKroneckerGithub_2234"
      - "@DeltaKroneckerGithub_1092"
      - "@DeltaKroneckerGithub_565"
      - "@DeltaKroneckerGithub_853"
      - "@DeltaKroneckerGithub_3660"
      - "@DeltaKroneckerGithub_2514"
      - "@DeltaKroneckerGithub_4754"
      - "@DeltaKroneckerGithub_2580"
      - "@DeltaKroneckerGithub_3665"
      - "@DeltaKroneckerGithub_5201"
      - "@DeltaKroneckerGithub_3116"
      - "@DeltaKroneckerGithub_4129"

rules:
  - MATCH,PROXY
