name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "@DeltaKroneckerGithub_3567"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "f6a92fa2-5685-3c70-16d5-ba38b388dbbf"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "empty-water-a05b.gfbghfbfngbdgbghngf.workers.dev"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_1512"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "18535741-e8b3-4b43-9348-785b55936751"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
      headers:
        Host: "ov-germany1.09vpn.com👉🆔freenettir📡🇩🇪®️Germany©️Limburg"
  - name: "@DeltaKroneckerGithub_643"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "1679af35-6dd6-4c09-ae3b-18f239217f3e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "rAyAn-007.pArViN.DpDnS.OrG"
    client-fingerprint: "ios"
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "rayan-007.parvin.dpdns.org"
  - name: "@DeltaKroneckerGithub_4215"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "d6bdda67-168d-4501-a2c1-ef01070cb327"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net"
  - name: "@DeltaKroneckerGithub_5804"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "Telegram_healer_config"
    sni: "6M1RGyIeClMRx9hef1.z6-0HlnubjIbWZpa85.wOrKerS.DEv"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/tr/ox5zBiRQjs2Rscy0XwxXY2ZzE?ed=2560"
      headers:
        Host: "6m1rgyieclmrx9hef1.z6-0hlnubjibwzpa85.workers.dev"
  - name: "@DeltaKroneckerGithub_123"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "1d16c6e0-1bbe-435b-b661-90043fee999c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "notls.lukongtou.eu.org"
    network: ws
    ws-opts:
      path: "Telegram-WangCai2🇨🇳"
      headers:
        Host: "notls.lukongtou.eu.org"
  - name: "@DeltaKroneckerGithub_3058"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "bc01a49f-78dd-4bf0-994f-b86897e39a68"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
  - name: "@DeltaKroneckerGithub_6337"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "c30f9be0-6d5d-11f1-b3fc-1239d0255272"
    sni: "uk1.test3.net"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/howdy"
      headers:
        Host: "uk1.test3.net"
  - name: "@DeltaKroneckerGithub_2366"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "288bb3f1-8994-47cf-8bd8-9b7d4d716461"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "newvless2026.nova-b0f3f5.workers.dev"
  - name: "@DeltaKroneckerGithub_3180"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_4783"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "72e07880-67b8-11f1-af64-1239d0255272"
    sni: "uk1.test3.net"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/howdy"
      headers:
        Host: "uk1.test3.net"
  - name: "@DeltaKroneckerGithub_3367"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "e75feb84-1638-4817-9c31-53eacb147362"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
  - name: "@DeltaKroneckerGithub_3049"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "@DeltaKroneckerGithub_1067"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "a746a471-0339-41ae-9750-d1f572bde296"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "YDqbCJ3IE4sqJux1AH93x.l9yawn7wAgNMFd0-CnzjnDC1U24q.Workers.dEV"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/vl/lbzuMME2utgQTXnVd5CGjUAy4JtKk9yQ?ed=2560"
      headers:
        Host: "ydqbcj3ie4sqjux1ah93x.l9yawn7wagnmfd0-cnzjndc1u24q.workers.dev"
  - name: "@DeltaKroneckerGithub_3813"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "e5cc16a6-ea42-46b2-82ae-ad2157e1641b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "hhlfy.twiladaphne.ndjp.net"
    client-fingerprint: "random"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "hhlfy.twiladaphne.ndjp.net"
  - name: "@DeltaKroneckerGithub_1019"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "65c56e1f-5c41-40bc-b0b5-9346772476ca"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "hongkong.11459178.xyz"
    client-fingerprint: "edge"
    network: ws
    ws-opts:
      path: "/cdn/packages/runtime-core.tar.gz"
      headers:
        Host: "hongkong.11459178.xyz"
  - name: "@DeltaKroneckerGithub_357"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime02.workers.dev"
  - name: "@DeltaKroneckerGithub_4275"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "c04e959d-3b7a-4d4f-881a-935762102704"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.US.CMLiussss.net"
      headers:
        Host: "super-darkness-5bfb.298-142.workers.dev"
  - name: "@DeltaKroneckerGithub_4591"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "Telegram_healer_config"
    sni: "To6R63-kKChiGHqm2.vxz0Dduq7to7Su0CDQf.worKERs.DEV"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/tr/xwtrOUcg21SS0Ega?ed=2560"
      headers:
        Host: "to6r63-kkchighqm2.vxz0dduq7to7su0cdqf.workers.dev"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_3567"
      - "@DeltaKroneckerGithub_1512"
      - "@DeltaKroneckerGithub_643"
      - "@DeltaKroneckerGithub_4215"
      - "@DeltaKroneckerGithub_5804"
      - "@DeltaKroneckerGithub_123"
      - "@DeltaKroneckerGithub_3058"
      - "@DeltaKroneckerGithub_6337"
      - "@DeltaKroneckerGithub_2366"
      - "@DeltaKroneckerGithub_3180"
      - "@DeltaKroneckerGithub_4783"
      - "@DeltaKroneckerGithub_3367"
      - "@DeltaKroneckerGithub_3049"
      - "@DeltaKroneckerGithub_1067"
      - "@DeltaKroneckerGithub_3813"
      - "@DeltaKroneckerGithub_1019"
      - "@DeltaKroneckerGithub_357"
      - "@DeltaKroneckerGithub_4275"
      - "@DeltaKroneckerGithub_4591"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "@DeltaKroneckerGithub_3567"
      - "@DeltaKroneckerGithub_1512"
      - "@DeltaKroneckerGithub_643"
      - "@DeltaKroneckerGithub_4215"
      - "@DeltaKroneckerGithub_5804"
      - "@DeltaKroneckerGithub_123"
      - "@DeltaKroneckerGithub_3058"
      - "@DeltaKroneckerGithub_6337"
      - "@DeltaKroneckerGithub_2366"
      - "@DeltaKroneckerGithub_3180"
      - "@DeltaKroneckerGithub_4783"
      - "@DeltaKroneckerGithub_3367"
      - "@DeltaKroneckerGithub_3049"
      - "@DeltaKroneckerGithub_1067"
      - "@DeltaKroneckerGithub_3813"
      - "@DeltaKroneckerGithub_1019"
      - "@DeltaKroneckerGithub_357"
      - "@DeltaKroneckerGithub_4275"
      - "@DeltaKroneckerGithub_4591"

rules:
  - MATCH,PROXY
