name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇦🇹_1"
    type: vless
    server: "212.183.88.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "vms.lifetime23.workers.dev"
  - name: "🇦🇹_3"
    type: vless
    server: "138.124.90.249"
    port: 7445
    uuid: "76ad3e79-fb8c-4ee2-a8f1-491573daa663"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kqjifhg9rw.tradsc8p9xp7wxyqmc1wy0ah.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "kqjifhg9rw.tradsc8p9xp7wxyqmc1wy0ah.workers.dev"
  - name: "🇦🇹_5"
    type: vless
    server: "152.53.47.153"
    port: 16923
    uuid: "3e5797ff-cb46-48b2-be3c-1fc78a37a439"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "api-maps.yandex.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "_QeslG3rHGM7DoM99pYC8-jpc16pM2MbNZ6NRMoxmHA"
      short-id: "10ffb85da1c2d986"
    network: grpc
    grpc-opts:
      grpc-service-name: "neurex"
  - name: "🇦🇹_6"
    type: vless
    server: "77.110.110.214"
    port: 6443
    uuid: "29a77cbc-bd97-4b8c-af20-c3c6341da10f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "woc0zvrf11w2endu.dphdlc1u77bs3y4kvussbuap4p576f1ws7igthq8zbf3.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "woc0zvrf11w2endu.dphdlc1u77bs3y4kvussbuap4p576f1ws7igthq8zbf3.workers.dev"
  - name: "🇦🇹_8"
    type: vless
    server: "152.53.47.153"
    port: 16923
    uuid: "e1570488-d499-40bb-b9d4-a69c25c4b5ca"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "api-maps.yandex.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "_QeslG3rHGM7DoM99pYC8-jpc16pM2MbNZ6NRMoxmHA"
      short-id: "10ffb85da1c2d986"
    network: grpc
    grpc-opts:
      grpc-service-name: "neurex"
  - name: "🇦🇹_9"
    type: vless
    server: "152.53.46.27"
    port: 443
    uuid: "bcc094e4-1a85-8a25-f8e1-5b08b9af841c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "stackoverflow.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "LaGTRJ1CJnnYV7FnyqQnU28I0xFTPFKI8xmUFwig5ic"
      short-id: "c410508e9721512b"
    flow: "xtls-rprx-vision"
  - name: "🇦🇹_10"
    type: vless
    server: "152.53.47.153"
    port: 16923
    uuid: "4ab27adf-e13d-4eea-8cfc-a77f2a78c27b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "api-maps.yandex.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "_QeslG3rHGM7DoM99pYC8-jpc16pM2MbNZ6NRMoxmHA"
      short-id: "10ffb85da1c2d986"
    network: grpc
    grpc-opts:
      grpc-service-name: "neurex"
  - name: "🇦🇹_11"
    type: vless
    server: "77.73.131.154"
    port: 443
    uuid: "1f4c983e-382c-d2fa-b2dc-7981f02b34de"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vindobona.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "5GhMSJXQv1wXHVD999YHRRj83m-7VKH8qb_vTxBGbng"
      short-id: "08"
    flow: "xtls-rprx-vision"
  - name: "🇦🇹_12"
    type: vless
    server: "152.53.47.153"
    port: 16923
    uuid: "3df0d1ae-a205-4602-a9a1-f0d518dcc826"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "api-maps.yandex.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "_QeslG3rHGM7DoM99pYC8-jpc16pM2MbNZ6NRMoxmHA"
      short-id: "10ffb85da1c2d986"
    network: grpc
    grpc-opts:
      grpc-service-name: "neurex"
  - name: "🇦🇹_13"
    type: vless
    server: "152.53.47.153"
    port: 16923
    uuid: "fbefb819-d89f-412e-9a95-62c64fd8d123"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "api-maps.yandex.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "_QeslG3rHGM7DoM99pYC8-jpc16pM2MbNZ6NRMoxmHA"
      short-id: "10ffb85da1c2d986"
    network: grpc
    grpc-opts:
      grpc-service-name: "neurex"
  - name: "🇦🇹_14"
    type: vless
    server: "mouse3.1lil1.de"
    port: 443
    uuid: "bcc094e4-1a85-8a25-f8e1-5b08b9af841c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "stackoverflow.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "LaGTRJ1CJnnYV7FnyqQnU28I0xFTPFKI8xmUFwig5ic"
      short-id: "c410508e9721512b"
    flow: "xtls-rprx-vision"
  - name: "🇦🇹_15"
    type: trojan
    server: "212.183.88.136"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "🇦🇹_17"
    type: ss
    server: "130.195.222.215"
    port: 443
    cipher: "none"
    password: "https://t.me/WangCai2🇨🇳"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "59fc5f8c-5697-4eb8-acf2-8ae363f203a2/?ed\\=2560"
      host: "woshinidie-et3.pages.dev"
      tls: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇦🇹_1"
      - "🇦🇹_3"
      - "🇦🇹_5"
      - "🇦🇹_6"
      - "🇦🇹_8"
      - "🇦🇹_9"
      - "🇦🇹_10"
      - "🇦🇹_11"
      - "🇦🇹_12"
      - "🇦🇹_13"
      - "🇦🇹_14"
      - "🇦🇹_15"
      - "🇦🇹_17"


rules:
  - MATCH,PROXY
