name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇦🇺_1"
    type: vless
    server: "auth.figmafound.org"
    port: 443
    uuid: "71b91642-93ed-4923-8cab-877e19bfc2d6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "auth.figmafound.org"
    client-fingerprint: "random"
    reality-opts:
      public-key: "H5CXI4RvEWW0TFPvFrnF1iX-05Y57ZYMMngjmkMfv24"
      short-id: "711ad7f475c35e5e"
    flow: "xtls-rprx-vision"
  - name: "🇦🇺_2"
    type: vless
    server: "172.105.169.70"
    port: 443
    uuid: "03fcc618-b93d-6796-6aed-8a38c975d581"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "172.105.169.70"
  - name: "🇦🇺_3"
    type: vless
    server: "103.139.51.21"
    port: 443
    uuid: "71b91642-93ed-4923-8cab-877e19bfc2d6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "auth.figmafound.org"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "H5CXI4RvEWW0TFPvFrnF1iX-05Y57ZYMMngjmkMfv24"
      short-id: "711ad7f475c35e5e"
    flow: "xtls-rprx-vision"
  - name: "🇦🇺_4"
    type: vless
    server: "34.87.229.148"
    port: 443
    uuid: "4f865f35-cf47-4e7f-a7e6-8882511a1b36"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "OgTkmAQdLjipA9oLloxbU5BAX3hPjzbvkEGHF4aZ8z4"
      short-id: "8a7d5e0248cdb1b1"
  - name: "🇦🇺_5"
    type: vless
    server: "46.250.240.80"
    port: 2053
    uuid: "948df76f-505d-4608-9c76-a933ee3ccc76"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "CYFeysLf--_IVhxQOCd3ZxLrAVWFFOkJzvIGHOVXN3E"
      short-id: "4cc9dc65f7770115"
  - name: "🇦🇺_6"
    type: vless
    server: "34.87.244.111"
    port: 443
    uuid: "325bc1be-0cb7-4cf7-bd35-a79ded91bbbd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "fsdIMU2apN1C_NbkL7mHTsBKEfhwbDhgCRcB8ICf03E"
      short-id: "d725f0dd8cce210f"
  - name: "🇦🇺_7"
    type: trojan
    server: "true-pony.rooster465.autos"
    port: 443
    password: "FH72359861"
    sni: "true-pony.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_8"
    type: trojan
    server: "87.121.33.185"
    port: 443
    password: "JT80563429"
    sni: "humorous-llama.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_9"
    type: trojan
    server: "big-bonefish.rooster465.autos"
    port: 443
    password: "PQ05174892"
    sni: "big-bonefish.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_10"
    type: trojan
    server: "87.121.33.82"
    port: 443
    password: "JT80563429"
    sni: "darling-mutt.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_11"
    type: trojan
    server: "87.121.33.162"
    port: 443
    password: "WG39087154"
    sni: "together-dingo.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_12"
    type: trojan
    server: "87.121.33.183"
    port: 443
    password: "IQ68037294"
    sni: "fleet-hawk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_13"
    type: trojan
    server: "neat-whale.rooster465.autos"
    port: 443
    password: "JT80563429"
    sni: "neat-whale.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_14"
    type: trojan
    server: "together-dingo.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "together-dingo.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_15"
    type: trojan
    server: "together-dingo.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "together-dingo.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_16"
    type: trojan
    server: "darling-mutt.rooster465.autos"
    port: 443
    password: "PQ05174892"
    sni: "darling-mutt.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_17"
    type: trojan
    server: "neat-whale.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "neat-whale.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_18"
    type: trojan
    server: "87.121.33.56"
    port: 443
    password: "JT80563429"
    sni: "neat-whale.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_19"
    type: trojan
    server: "big-bonefish.rooster465.autos"
    port: 443
    password: "PD07395842"
    sni: "big-bonefish.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_20"
    type: trojan
    server: "darling-mutt.rooster465.autos"
    port: 443
    password: "WG39087154"
    sni: "darling-mutt.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_21"
    type: trojan
    server: "true-pony.rooster465.autos"
    port: 443
    password: "PQ05174892"
    sni: "true-pony.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_22"
    type: trojan
    server: "darling-mutt.rooster465.autos"
    port: 443
    password: "JT80563429"
    sni: "darling-mutt.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_23"
    type: trojan
    server: "darling-mutt.rooster465.autos"
    port: 443
    password: "PD07395842"
    sni: "darling-mutt.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_24"
    type: trojan
    server: "87.121.33.162"
    port: 443
    password: "IQ68037294"
    sni: "together-dingo.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_25"
    type: trojan
    server: "humorous-llama.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "humorous-llama.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_26"
    type: trojan
    server: "true-pony.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "true-pony.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_27"
    type: trojan
    server: "darling-mutt.rooster465.autos"
    port: 443
    password: "EQ30679154"
    sni: "darling-mutt.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_28"
    type: trojan
    server: "together-dingo.rooster465.autos"
    port: 443
    password: "WG39087154"
    sni: "together-dingo.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_29"
    type: trojan
    server: "87.121.33.82"
    port: 443
    password: "AE62539071"
    sni: "darling-mutt.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_30"
    type: trojan
    server: "neat-whale.rooster465.autos"
    port: 443
    password: "IQ68037294"
    sni: "neat-whale.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_31"
    type: trojan
    server: "87.121.33.82"
    port: 443
    password: "PD07395842"
    sni: "darling-mutt.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_32"
    type: trojan
    server: "87.121.33.185"
    port: 443
    password: "AE62539071"
    sni: "humorous-llama.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_33"
    type: trojan
    server: "true-pony.rooster465.autos"
    port: 443
    password: "WG39087154"
    sni: "true-pony.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_34"
    type: trojan
    server: "87.121.33.48"
    port: 443
    password: "PD07395842"
    sni: "big-bonefish.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_35"
    type: trojan
    server: "87.121.33.14"
    port: 443
    password: "WG39087154"
    sni: "true-pony.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_36"
    type: trojan
    server: "darling-mutt.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "darling-mutt.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_37"
    type: trojan
    server: "87.121.33.14"
    port: 443
    password: "PQ05174892"
    sni: "true-pony.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_38"
    type: trojan
    server: "87.121.33.185"
    port: 443
    password: "WG39087154"
    sni: "humorous-llama.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_39"
    type: trojan
    server: "87.121.33.48"
    port: 443
    password: "PQ05174892"
    sni: "big-bonefish.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_40"
    type: trojan
    server: "true-pony.rooster465.autos"
    port: 443
    password: "PD07395842"
    sni: "true-pony.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_41"
    type: trojan
    server: "fleet-hawk.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "fleet-hawk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_42"
    type: trojan
    server: "true-pony.rooster465.autos"
    port: 443
    password: "IQ68037294"
    sni: "true-pony.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_43"
    type: trojan
    server: "together-dingo.rooster465.autos"
    port: 443
    password: "IQ68037294"
    sni: "together-dingo.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_44"
    type: trojan
    server: "87.121.33.56"
    port: 443
    password: "IQ68037294"
    sni: "neat-whale.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_45"
    type: trojan
    server: "fleet-hawk.rooster465.autos"
    port: 443
    password: "EQ30679154"
    sni: "fleet-hawk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_46"
    type: trojan
    server: "87.121.33.14"
    port: 443
    password: "IQ68037294"
    sni: "true-pony.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_47"
    type: trojan
    server: "87.121.33.14"
    port: 443
    password: "JT80563429"
    sni: "true-pony.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_48"
    type: trojan
    server: "fleet-hawk.rooster465.autos"
    port: 443
    password: "IQ68037294"
    sni: "fleet-hawk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_49"
    type: trojan
    server: "darling-mutt.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "darling-mutt.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_50"
    type: trojan
    server: "87.121.33.162"
    port: 443
    password: "AE62539071"
    sni: "together-dingo.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_51"
    type: trojan
    server: "87.121.33.162"
    port: 443
    password: "FC60532879"
    sni: "together-dingo.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_52"
    type: trojan
    server: "neat-whale.rooster465.autos"
    port: 443
    password: "WG39087154"
    sni: "neat-whale.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_53"
    type: trojan
    server: "big-bonefish.rooster465.autos"
    port: 443
    password: "OD90375861"
    sni: "big-bonefish.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_54"
    type: trojan
    server: "87.121.33.82"
    port: 443
    password: "FC60532879"
    sni: "darling-mutt.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_55"
    type: trojan
    server: "humorous-llama.rooster465.autos"
    port: 443
    password: "WG39087154"
    sni: "humorous-llama.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_56"
    type: trojan
    server: "87.121.33.162"
    port: 443
    password: "JT80563429"
    sni: "together-dingo.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_57"
    type: trojan
    server: "87.121.33.183"
    port: 443
    password: "FC60532879"
    sni: "fleet-hawk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_58"
    type: trojan
    server: "87.121.33.56"
    port: 443
    password: "WG39087154"
    sni: "neat-whale.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_59"
    type: trojan
    server: "87.121.33.56"
    port: 443
    password: "FC60532879"
    sni: "neat-whale.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_60"
    type: trojan
    server: "87.121.33.48"
    port: 443
    password: "OD90375861"
    sni: "big-bonefish.rooster465.autos"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇦🇺_1"
      - "🇦🇺_2"
      - "🇦🇺_3"
      - "🇦🇺_4"
      - "🇦🇺_5"
      - "🇦🇺_6"
      - "🇦🇺_7"
      - "🇦🇺_8"
      - "🇦🇺_9"
      - "🇦🇺_10"
      - "🇦🇺_11"
      - "🇦🇺_12"
      - "🇦🇺_13"
      - "🇦🇺_14"
      - "🇦🇺_15"
      - "🇦🇺_16"
      - "🇦🇺_17"
      - "🇦🇺_18"
      - "🇦🇺_19"
      - "🇦🇺_20"
      - "🇦🇺_21"
      - "🇦🇺_22"
      - "🇦🇺_23"
      - "🇦🇺_24"
      - "🇦🇺_25"
      - "🇦🇺_26"
      - "🇦🇺_27"
      - "🇦🇺_28"
      - "🇦🇺_29"
      - "🇦🇺_30"
      - "🇦🇺_31"
      - "🇦🇺_32"
      - "🇦🇺_33"
      - "🇦🇺_34"
      - "🇦🇺_35"
      - "🇦🇺_36"
      - "🇦🇺_37"
      - "🇦🇺_38"
      - "🇦🇺_39"
      - "🇦🇺_40"
      - "🇦🇺_41"
      - "🇦🇺_42"
      - "🇦🇺_43"
      - "🇦🇺_44"
      - "🇦🇺_45"
      - "🇦🇺_46"
      - "🇦🇺_47"
      - "🇦🇺_48"
      - "🇦🇺_49"
      - "🇦🇺_50"
      - "🇦🇺_51"
      - "🇦🇺_52"
      - "🇦🇺_53"
      - "🇦🇺_54"
      - "🇦🇺_55"
      - "🇦🇺_56"
      - "🇦🇺_57"
      - "🇦🇺_58"
      - "🇦🇺_59"
      - "🇦🇺_60"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇦🇺_1"
      - "🇦🇺_2"
      - "🇦🇺_3"
      - "🇦🇺_4"
      - "🇦🇺_5"
      - "🇦🇺_6"
      - "🇦🇺_7"
      - "🇦🇺_8"
      - "🇦🇺_9"
      - "🇦🇺_10"
      - "🇦🇺_11"
      - "🇦🇺_12"
      - "🇦🇺_13"
      - "🇦🇺_14"
      - "🇦🇺_15"
      - "🇦🇺_16"
      - "🇦🇺_17"
      - "🇦🇺_18"
      - "🇦🇺_19"
      - "🇦🇺_20"
      - "🇦🇺_21"
      - "🇦🇺_22"
      - "🇦🇺_23"
      - "🇦🇺_24"
      - "🇦🇺_25"
      - "🇦🇺_26"
      - "🇦🇺_27"
      - "🇦🇺_28"
      - "🇦🇺_29"
      - "🇦🇺_30"
      - "🇦🇺_31"
      - "🇦🇺_32"
      - "🇦🇺_33"
      - "🇦🇺_34"
      - "🇦🇺_35"
      - "🇦🇺_36"
      - "🇦🇺_37"
      - "🇦🇺_38"
      - "🇦🇺_39"
      - "🇦🇺_40"
      - "🇦🇺_41"
      - "🇦🇺_42"
      - "🇦🇺_43"
      - "🇦🇺_44"
      - "🇦🇺_45"
      - "🇦🇺_46"
      - "🇦🇺_47"
      - "🇦🇺_48"
      - "🇦🇺_49"
      - "🇦🇺_50"
      - "🇦🇺_51"
      - "🇦🇺_52"
      - "🇦🇺_53"
      - "🇦🇺_54"
      - "🇦🇺_55"
      - "🇦🇺_56"
      - "🇦🇺_57"
      - "🇦🇺_58"
      - "🇦🇺_59"
      - "🇦🇺_60"

rules:
  - MATCH,PROXY
