name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇧🇷_1"
    type: ss
    server: "147.15.47.5"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "BFQyHWB20qvH0asuixcidL1wLU6XLdmFzANF3GjLFQw="
    udp: true
  - name: "🇧🇷_2"
    type: ss
    server: "147.15.47.5"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "BFQyHWB20qvH0asuixcidL1wLU6XLdmFzANF3GjLFQw="
    udp: true
  - name: "🇧🇷_3"
    type: ss
    server: "150.230.77.159"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "fQD3R706R6XGUCXh5XwMDv6IbqQO+g4iVYx5OnT/Cqs="
    udp: true
  - name: "🇧🇷_4"
    type: ss
    server: "147.15.47.5"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "BFQyHWB20qvH0asuixcidL1wLU6XLdmFzANF3GjLFQw="
    udp: true
  - name: "🇧🇷_5"
    type: ss
    server: "136.248.91.217"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "cj9WLCOZewj3P48o4esJrYqjmwu/aRUFkOMTcBi+LfE="
    udp: true
  - name: "🇧🇷_6"
    type: ss
    server: "159.112.176.198"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "ZxIQSuhi48PC6452e1GKuTGd2+zgR7so5ucyS+KveAc="
    udp: true
  - name: "🇧🇷_7"
    type: ss
    server: "136.248.91.217"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "cj9WLCOZewj3P48o4esJrYqjmwu/aRUFkOMTcBi+LfE="
    udp: true
  - name: "🇧🇷_8"
    type: ss
    server: "163.176.213.34"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "sGdbihOb/q/EbANW26ODkZvW+bFxtL5OISohA64vCqQ="
    udp: true
  - name: "🇧🇷_9"
    type: ss
    server: "64.181.186.88"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "4MhKF4RF8BxnWHiNv/M3wK+Himna7l+B8sv4wGwjCg4="
    udp: true
  - name: "🇧🇷_10"
    type: ss
    server: "163.176.45.90"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "j9Q61DrvJg9MJWw+u3riQklAPSkYF2uoTwLuL2xaBrA="
    udp: true
  - name: "🇧🇷_11"
    type: ss
    server: "159.112.176.198"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "ZxIQSuhi48PC6452e1GKuTGd2+zgR7so5ucyS+KveAc="
    udp: true
  - name: "🇧🇷_12"
    type: ss
    server: "136.248.91.217"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "cj9WLCOZewj3P48o4esJrYqjmwu/aRUFkOMTcBi+LfE="
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇧🇷_1"
      - "🇧🇷_2"
      - "🇧🇷_3"
      - "🇧🇷_4"
      - "🇧🇷_5"
      - "🇧🇷_6"
      - "🇧🇷_7"
      - "🇧🇷_8"
      - "🇧🇷_9"
      - "🇧🇷_10"
      - "🇧🇷_11"
      - "🇧🇷_12"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇧🇷_1"
      - "🇧🇷_2"
      - "🇧🇷_3"
      - "🇧🇷_4"
      - "🇧🇷_5"
      - "🇧🇷_6"
      - "🇧🇷_7"
      - "🇧🇷_8"
      - "🇧🇷_9"
      - "🇧🇷_10"
      - "🇧🇷_11"
      - "🇧🇷_12"

rules:
  - MATCH,PROXY
