name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇧🇷_1"
    type: vless
    server: "u234-6njjdk.startora.top"
    port: 443
    uuid: "c396fa08-e07a-459b-b894-389456fd6a82"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amazon.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "m89wjPa2LxODyi8U5pRVI4E1fwVawIaftC3fLY0ZLw4"
      short-id: "9ea177c3c147119b"
    flow: "xtls-rprx-vision"
  - name: "🇧🇷_2"
    type: vless
    server: "23.251.55.216"
    port: 443
    uuid: "c396fa08-e07a-459b-b894-389456fd6a82"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amazon.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "m89wjPa2LxODyi8U5pRVI4E1fwVawIaftC3fLY0ZLw4"
      short-id: "9ea177c3c147119b"
    flow: "xtls-rprx-vision"
  - name: "🇧🇷_3"
    type: vless
    server: "23.251.56.78"
    port: 443
    uuid: "9638a83e-f1f7-4cc8-a602-924965d9534f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "E6Y9lNizCXo8tJ6EXwLYQIjyIwmxIs4foyRlY2MgkjA"
      short-id: "59ccabb0a1483c4b"
    flow: "xtls-rprx-vision"
  - name: "🇧🇷_4"
    type: ss
    server: "144.22.132.191"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "SsMG/Y8d12j7lzjxerXFHpQw3YoMOrZ4eOJt2/NnWEM="
    udp: true
  - name: "🇧🇷_5"
    type: ss
    server: "159.112.178.179"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "858E8ArCFX7vumbFzuVpUw5FTQaoj058jNkOFWA58ds="
    udp: true
  - name: "🇧🇷_6"
    type: ss
    server: "144.22.232.252"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "5AUy4er8u7V/zMsQJk1vSda0I6vdApAU85sQ1G4X/0E="
    udp: true
  - name: "🇧🇷_7"
    type: ss
    server: "137.131.228.121"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "55nlrXTkb08jPEwboRS7GOlM3LiBb4sqMGC0wmvKhw0="
    udp: true
  - name: "🇧🇷_8"
    type: ss
    server: "129.159.49.64"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "MdImM0QejAzcmEd6BKaoy1mr4hVAIqXF7LTY1EqzTL0="
    udp: true
  - name: "🇧🇷_9"
    type: ss
    server: "150.230.229.189"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "VNZU26yCu5J1TaXQ9IdJasKHopBUzc2xt+JUl9ECB+g="
    udp: true
  - name: "🇧🇷_10"
    type: ss
    server: "159.112.178.179"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "858E8ArCFX7vumbFzuVpUw5FTQaoj058jNkOFWA58ds="
    udp: true
  - name: "🇧🇷_11"
    type: ss
    server: "64.181.171.113"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "OYAoH+Rfx3SHm6POtoPiRHDXs/hWB8AviM1xxUek39c="
    udp: true
  - name: "🇧🇷_12"
    type: ss
    server: "150.230.229.189"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "VNZU26yCu5J1TaXQ9IdJasKHopBUzc2xt+JUl9ECB+g="
    udp: true
  - name: "🇧🇷_13"
    type: ss
    server: "144.22.150.193"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "3c8tj0DA79hjfpioMZAadyGr/dNl4C6MTsJTNE8l8Mw="
    udp: true
  - name: "🇧🇷_14"
    type: ss
    server: "168.75.66.122"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "s6RXknYLMS6vQPV6efRSoLoe45c8/Pp1+dB8CdfNlmY="
    udp: true
  - name: "🇧🇷_15"
    type: ss
    server: "150.230.229.189"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "VNZU26yCu5J1TaXQ9IdJasKHopBUzc2xt+JUl9ECB+g="
    udp: true
  - name: "🇧🇷_16"
    type: ss
    server: "147.15.34.121"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "XVdJDPuYb1x072JrCC2+BfeiCgIMDhDO3q3hl467FZU="
    udp: true
  - name: "🇧🇷_17"
    type: ss
    server: "129.159.51.192"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "BpRvyXe7auEq/L91yrZqp46xURh6LDAgvcj2fXQ8Nzk="
    udp: true
  - name: "🇧🇷_18"
    type: ss
    server: "129.159.49.64"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "MdImM0QejAzcmEd6BKaoy1mr4hVAIqXF7LTY1EqzTL0="
    udp: true
  - name: "🇧🇷_19"
    type: ss
    server: "129.159.49.64"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "MdImM0QejAzcmEd6BKaoy1mr4hVAIqXF7LTY1EqzTL0="
    udp: true
  - name: "🇧🇷_20"
    type: ss
    server: "168.75.66.122"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "s6RXknYLMS6vQPV6efRSoLoe45c8/Pp1+dB8CdfNlmY="
    udp: true
  - name: "🇧🇷_21"
    type: ss
    server: "147.15.34.121"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "XVdJDPuYb1x072JrCC2+BfeiCgIMDhDO3q3hl467FZU="
    udp: true
  - name: "🇧🇷_22"
    type: ss
    server: "137.131.228.121"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "55nlrXTkb08jPEwboRS7GOlM3LiBb4sqMGC0wmvKhw0="
    udp: true
  - name: "🇧🇷_23"
    type: ss
    server: "147.15.34.121"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "XVdJDPuYb1x072JrCC2+BfeiCgIMDhDO3q3hl467FZU="
    udp: true
  - name: "🇧🇷_24"
    type: ss
    server: "137.131.228.121"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "55nlrXTkb08jPEwboRS7GOlM3LiBb4sqMGC0wmvKhw0="
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇧🇷_1"
      - "🇧🇷_2"
      - "🇧🇷_3"
      - "🇧🇷_4"
      - "🇧🇷_5"
      - "🇧🇷_6"
      - "🇧🇷_7"
      - "🇧🇷_8"
      - "🇧🇷_9"
      - "🇧🇷_10"
      - "🇧🇷_11"
      - "🇧🇷_12"
      - "🇧🇷_13"
      - "🇧🇷_14"
      - "🇧🇷_15"
      - "🇧🇷_16"
      - "🇧🇷_17"
      - "🇧🇷_18"
      - "🇧🇷_19"
      - "🇧🇷_20"
      - "🇧🇷_21"
      - "🇧🇷_22"
      - "🇧🇷_23"
      - "🇧🇷_24"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇧🇷_1"
      - "🇧🇷_2"
      - "🇧🇷_3"
      - "🇧🇷_4"
      - "🇧🇷_5"
      - "🇧🇷_6"
      - "🇧🇷_7"
      - "🇧🇷_8"
      - "🇧🇷_9"
      - "🇧🇷_10"
      - "🇧🇷_11"
      - "🇧🇷_12"
      - "🇧🇷_13"
      - "🇧🇷_14"
      - "🇧🇷_15"
      - "🇧🇷_16"
      - "🇧🇷_17"
      - "🇧🇷_18"
      - "🇧🇷_19"
      - "🇧🇷_20"
      - "🇧🇷_21"
      - "🇧🇷_22"
      - "🇧🇷_23"
      - "🇧🇷_24"

rules:
  - MATCH,PROXY
