name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇧🇷_1"
    type: ss
    server: "137.131.200.22"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "tNYMIixAhMRlptzlIGQrnx6y24ONgfLrblB3qmVzwDY="
    udp: true
  - name: "🇧🇷_2"
    type: ss
    server: "137.131.200.22"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "tNYMIixAhMRlptzlIGQrnx6y24ONgfLrblB3qmVzwDY="
    udp: true
  - name: "🇧🇷_3"
    type: ss
    server: "136.248.64.193"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "xBFY31OuGDv3C4VMzGuESB5OhMs18/5+/M7LnpmJfKA="
    udp: true
  - name: "🇧🇷_4"
    type: ss
    server: "150.230.85.156"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "I30kuoEIRZGueSf3vCEhIoVOqwLy98J1lRTJo8aC2Zw="
    udp: true
  - name: "🇧🇷_5"
    type: ss
    server: "146.235.25.6"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "FWlUCAS9IBNg+5FoZ+U0kRs3dcz+oQnQkjGI/iKZMR0="
    udp: true
  - name: "🇧🇷_6"
    type: ss
    server: "144.22.225.161"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "GRe/0J+gpJILazFMu8n4Lo6J1AjoIG2+mdCoR7RmX74="
    udp: true
  - name: "🇧🇷_7"
    type: ss
    server: "144.22.225.161"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "GRe/0J+gpJILazFMu8n4Lo6J1AjoIG2+mdCoR7RmX74="
    udp: true
  - name: "🇧🇷_8"
    type: ss
    server: "146.235.25.6"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "FWlUCAS9IBNg+5FoZ+U0kRs3dcz+oQnQkjGI/iKZMR0="
    udp: true
  - name: "🇧🇷_9"
    type: ss
    server: "146.235.25.6"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "FWlUCAS9IBNg+5FoZ+U0kRs3dcz+oQnQkjGI/iKZMR0="
    udp: true
  - name: "🇧🇷_10"
    type: ss
    server: "146.235.25.6"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "FWlUCAS9IBNg+5FoZ+U0kRs3dcz+oQnQkjGI/iKZMR0="
    udp: true
  - name: "🇧🇷_11"
    type: ss
    server: "144.22.225.161"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "GRe/0J+gpJILazFMu8n4Lo6J1AjoIG2+mdCoR7RmX74="
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇧🇷_1"
      - "🇧🇷_2"
      - "🇧🇷_3"
      - "🇧🇷_4"
      - "🇧🇷_5"
      - "🇧🇷_6"
      - "🇧🇷_7"
      - "🇧🇷_8"
      - "🇧🇷_9"
      - "🇧🇷_10"
      - "🇧🇷_11"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇧🇷_1"
      - "🇧🇷_2"
      - "🇧🇷_3"
      - "🇧🇷_4"
      - "🇧🇷_5"
      - "🇧🇷_6"
      - "🇧🇷_7"
      - "🇧🇷_8"
      - "🇧🇷_9"
      - "🇧🇷_10"
      - "🇧🇷_11"

rules:
  - MATCH,PROXY
