name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇨🇳_1"
    type: trojan
    server: "118.253.167.243"
    port: 59443
    password: "4c1511d220e1437b234fa40571c43810"
    sni: "tyy129.magiclampcloud.com"
    skip-cert-verify: true
    udp: true
  - name: "🇨🇳_2"
    type: trojan
    server: "ja262.magiclampcloud.cn"
    port: 59443
    password: "6edc9363c16bb2f7861bc1ab96edd69f"
    sni: "ja262.magiclampcloud.cn"
    skip-cert-verify: true
    udp: true
  - name: "🇨🇳_3"
    type: trojan
    server: "ja304.magiclampcloud.cn"
    port: 59443
    password: "1a4dbf8b75346468b85c8d7f70c0cc75"
    sni: "ja304.magiclampcloud.cn"
    skip-cert-verify: true
    udp: true
  - name: "🇨🇳_4"
    type: trojan
    server: "ja304.magiclampcloud.cn"
    port: 59443
    password: "2ddeb5f43bbb897b13db728b2dfbef92"
    sni: "ja304.magiclampcloud.cn"
    skip-cert-verify: true
    udp: true
  - name: "🇨🇳_5"
    type: trojan
    server: "tyy129.magiclampcloud.com"
    port: 59443
    password: "14bac0e43c849123ccb0fd0690f24316"
    sni: "tyy129.magiclampcloud.com"
    skip-cert-verify: true
    udp: true
  - name: "🇨🇳_6"
    type: trojan
    server: "tyy129.magiclampcloud.com"
    port: 59443
    password: "4c1511d220e1437b234fa40571c43810"
    sni: "tyy129.magiclampcloud.com"
    skip-cert-verify: true
    udp: true
  - name: "🇨🇳_7"
    type: trojan
    server: "117.149.198.190"
    port: 10051
    password: "a13820c547fa34c5c45515c12f0cd576"
    sni: "zz6.91js.pw"
    skip-cert-verify: true
    udp: true
  - name: "🇨🇳_8"
    type: trojan
    server: "118.253.167.243"
    port: 59443
    password: "14bac0e43c849123ccb0fd0690f24316"
    sni: "tyy129.magiclampcloud.com"
    skip-cert-verify: true
    udp: true
  - name: "🇨🇳_9"
    type: vmess
    server: "150.242.244.116"
    port: 2648
    uuid: "44712929-c2b7-4fa4-93bd-9de332a78c8c"
    alterId: 0
    cipher: "auto"
    udp: true
  - name: "🇨🇳_10"
    type: vmess
    server: "112.132.215.108"
    port: 50002
    uuid: "418048af-a293-4b99-9b0c-98ca3580dd24"
    alterId: 64
    cipher: "auto"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇨🇳_1"
      - "🇨🇳_2"
      - "🇨🇳_3"
      - "🇨🇳_4"
      - "🇨🇳_5"
      - "🇨🇳_6"
      - "🇨🇳_7"
      - "🇨🇳_8"
      - "🇨🇳_9"
      - "🇨🇳_10"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇨🇳_1"
      - "🇨🇳_2"
      - "🇨🇳_3"
      - "🇨🇳_4"
      - "🇨🇳_5"
      - "🇨🇳_6"
      - "🇨🇳_7"
      - "🇨🇳_8"
      - "🇨🇳_9"
      - "🇨🇳_10"

rules:
  - MATCH,PROXY
