name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇪🇪_1"
    type: vless
    server: "45.80.108.236"
    port: 443
    uuid: "ef9d2063-0140-472b-8b17-ba02ba4b4435"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lively-resonance-4e12.electrocellco-cf-059.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/proxyip=167.71.48.187"
      headers:
        Host: "lively-resonance-4e12.electrocellco-cf-059.workers.dev"
  - name: "🇪🇪_2"
    type: vless
    server: "94.183.170.231"
    port: 8443
    uuid: "19f54e37-5fae-47f6-bc10-e71ccbc58389"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "estproxy2.lockdwn.com"
    client-fingerprint: "firefox"
  - name: "🇪🇪_3"
    type: vless
    server: "est-1.p-esmy.icu"
    port: 2066
    uuid: "24f8209b-6689-4e7a-b067-f886e04dfc43"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "XIBKbglsQ9pI4eo26LoUkmNxnVqlKtxZRO0H91v3jF0"
      short-id: "1b2a3f"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_4"
    type: vless
    server: "185.155.97.241"
    port: 443
    uuid: "0b9bcbc1-b289-4a64-86fa-a5b731b65384"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "web.max.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "SJkDT_L0eziQR2afDGrkN7-uRxjYu6bZxIGXlKeCvX4"
      short-id: "15aa18f971da1f81"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_5"
    type: vless
    server: "95.85.224.3"
    port: 8443
    uuid: "7e8f7489-e65f-4be6-93ed-867a74ec6759"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇪🇪_6"
    type: vless
    server: "94.183.170.231"
    port: 443
    uuid: "19f54e37-5fae-47f6-bc10-e71ccbc58389"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "🇪🇪_7"
    type: vless
    server: "185.159.247.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime59.workers.dev"
  - name: "🇪🇪_8"
    type: vless
    server: "95.85.224.51"
    port: 443
    uuid: "342ab7e4-5a89-0001-8809-304120d4aa83"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "WWeAHWUVD-phmnjNJ823cer0c4CMIbEs08AhsuEZmDc"
      short-id: "a696de84963656de"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_9"
    type: vless
    server: "estproxy2.lockdwn.com"
    port: 8443
    uuid: "19f54e37-5fae-47f6-bc10-e71ccbc58389"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "estproxy2.lockdwn.com"
    client-fingerprint: "edge"
  - name: "🇪🇪_10"
    type: vless
    server: "estproxy2.lockdwn.com"
    port: 443
    uuid: "19f54e37-5fae-47f6-bc10-e71ccbc58389"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "🇪🇪_11"
    type: vless
    server: "2.26.128.77"
    port: 443
    uuid: "015b83b4-53a3-4719-8553-3a7c03c4128d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "wombat.mycdn-me.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "w88Ys8dVF9DuslGwUD05J9-FHNoAT9qmPysCvHiEmmg"
      short-id: "1b40e7c2a1d8f635"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_12"
    type: vless
    server: "64.188.82.152"
    port: 443
    uuid: "7836b28e-8451-4596-ad3e-e3601b2335ba"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cloudflare.vhub.pro"
    client-fingerprint: "safari"
    network: ws
    ws-opts:
      path: "/websocket?ed=2560"
      headers:
        Host: "cloudflare.vhub.pro"
  - name: "🇪🇪_13"
    type: vless
    server: "2.26.130.117"
    port: 443
    uuid: "015b83b4-53a3-4719-8553-3a7c03c4128d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nora.mycdn-me.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "GUdrwZxYWVvIFgC2fSJDs6U5Un6c7t1Yuvzl7yI1ohU"
      short-id: "2f6a8c3e90b2d574"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_14"
    type: vless
    server: "45.80.110.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime51.workers.dev"
  - name: "🇪🇪_15"
    type: vless
    server: "2.26.135.192"
    port: 443
    uuid: "015b83b4-53a3-4719-8553-3a7c03c4128d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "smorodina.mycdn-me.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "09O8bAlIWm9AGnNyxBtHwpYNQxlXPSQeQeKzS3ZMwGE"
      short-id: "a1f9c0e21d7b6485"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_16"
    type: vless
    server: "45.80.110.50"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "vms.lifetime51.workers.dev"
  - name: "🇪🇪_17"
    type: vless
    server: "45.80.108.123"
    port: 443
    uuid: "1d16c6e0-1bbe-435b-b661-90043fee999c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "notls.lukongtou.eu.org"
    network: ws
    ws-opts:
      path: "Telegram-WangCai2"
      headers:
        Host: "notls.lukongtou.eu.org"
  - name: "🇪🇪_18"
    type: trojan
    server: "185.36.141.81"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "🇪🇪_19"
    type: trojan
    server: "80.77.25.142"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇪🇪_1"
      - "🇪🇪_2"
      - "🇪🇪_3"
      - "🇪🇪_4"
      - "🇪🇪_5"
      - "🇪🇪_6"
      - "🇪🇪_7"
      - "🇪🇪_8"
      - "🇪🇪_9"
      - "🇪🇪_10"
      - "🇪🇪_11"
      - "🇪🇪_12"
      - "🇪🇪_13"
      - "🇪🇪_14"
      - "🇪🇪_15"
      - "🇪🇪_16"
      - "🇪🇪_17"
      - "🇪🇪_18"
      - "🇪🇪_19"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇪🇪_1"
      - "🇪🇪_2"
      - "🇪🇪_3"
      - "🇪🇪_4"
      - "🇪🇪_5"
      - "🇪🇪_6"
      - "🇪🇪_7"
      - "🇪🇪_8"
      - "🇪🇪_9"
      - "🇪🇪_10"
      - "🇪🇪_11"
      - "🇪🇪_12"
      - "🇪🇪_13"
      - "🇪🇪_14"
      - "🇪🇪_15"
      - "🇪🇪_16"
      - "🇪🇪_17"
      - "🇪🇪_18"
      - "🇪🇪_19"

rules:
  - MATCH,PROXY
