name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇪🇸_1"
    type: vless
    server: "154.23.242.96"
    port: 10047
    uuid: "7aecb4a5-f0a4-32a0-aabe-c9d5241e313f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.adobe.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "xnLREvR2BJGCu7teEqJej7qshkveyHNFwn1qKGgrAjA"
      short-id: "c5f8d3e8d4"
    flow: "xtls-rprx-vision"
  - name: "🇪🇸_2"
    type: trojan
    server: "65.20.102.54"
    port: 443
    password: "842b5f9dd11e458d8613c907c4cc5723"
    sni: "www.gpt123.one"
    skip-cert-verify: true
    udp: true
  - name: "🇪🇸_3"
    type: trojan
    server: "gfw.cmcuct.com"
    port: 50837
    password: "6fbda1e2-85e5-48dc-9fa0-21be0651aa47"
    sni: "cos.ap-hongkong.myqcloud.com"
    skip-cert-verify: true
    udp: true
  - name: "🇪🇸_4"
    type: ss
    server: "140.174.184.5"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "qItG8SueYQcP"
    udp: true
  - name: "🇪🇸_5"
    type: ss
    server: "108.181.121.226"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "WSyL4XTwNsdv"
    udp: true
  - name: "🇪🇸_6"
    type: ss
    server: "140.174.184.5"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "qItG8SueYQcP"
    udp: true
  - name: "🇪🇸_7"
    type: ss
    server: "108.181.121.226"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "WSyL4XTwNsdv"
    udp: true
  - name: "🇪🇸_8"
    type: vmess
    server: "85.90.217.42"
    port: 22324
    uuid: "04621bae-ab36-11ec-b909-0242ac120002"
    alterId: 0
    cipher: "auto"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇪🇸_1"
      - "🇪🇸_2"
      - "🇪🇸_3"
      - "🇪🇸_4"
      - "🇪🇸_5"
      - "🇪🇸_6"
      - "🇪🇸_7"
      - "🇪🇸_8"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇪🇸_1"
      - "🇪🇸_2"
      - "🇪🇸_3"
      - "🇪🇸_4"
      - "🇪🇸_5"
      - "🇪🇸_6"
      - "🇪🇸_7"
      - "🇪🇸_8"

rules:
  - MATCH,PROXY
