name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇫🇮_1"
    type: vless
    server: "171.22.129.56"
    port: 2053
    uuid: "b2744db0-1c64-4218-a93b-9eba0e5f811f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fi-one.quiet-rogue.site"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AKUQO-fKsD19FFBxNq5XTFCRXWDZfes4zJjRINY1KUI"
      short-id: "beff3ff061a64cfd"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_2"
    type: vless
    server: "37.143.129.244"
    port: 443
    uuid: "0e6de971-69e8-4536-b06d-8b6eae57021b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "gateway.icloud.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "5HArul2NDXfFUxijHj1xiPCfH-77zuuRxylT1vWIvUY"
      short-id: "48fd192dc4e46bc0"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_3"
    type: vless
    server: "5.61.91.207"
    port: 443
    uuid: "9ec52cb8-8daa-0021-ac36-d38295a25e5b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b4n1pcO8ST3JkGtj8YymXVrW17LEe2EHec5wY7hMMR4"
      short-id: "a7b2c9d4"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_4"
    type: vless
    server: "185.79.138.71"
    port: 448
    uuid: "0b0915d7-6800-4580-a44b-77d84f105e6a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.samsung.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "CsDgNRcCwCkPIslfZpKTIK71KFpIFNsotbdzKcZVoH8"
      short-id: "cd21e552537c7c0b"
  - name: "🇫🇮_5"
    type: vless
    server: "31.76.240.172"
    port: 443
    uuid: "d9d0f208-d582-41d5-bb7b-742671402810"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-north-fi-1.hanvpn.biz"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "nnkPnz6R86-6xG92s8k-1DUQPXAJIVMoMWDLPghh4x4"
      short-id: "0173b2681806bc97"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_6"
    type: vless
    server: "171.22.129.56"
    port: 2053
    uuid: "9f5b9ca7-d0bb-4e50-a3ca-acf5968027fc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fi-one.quiet-rogue.site"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AKUQO-fKsD19FFBxNq5XTFCRXWDZfes4zJjRINY1KUI"
      short-id: "beff3ff061a64cfd"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_7"
    type: vless
    server: "2.26.3.88"
    port: 443
    uuid: "5e666f1f-a7a4-4495-a220-98b5e588cf3b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fi.oblaco.bet"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "mJ-0fJDvKp0rhuyUvs1bw4RasRRM-BEOAl9iAZ8gXy0"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_8"
    type: vless
    server: "5.61.91.206"
    port: 443
    uuid: "d427a02f-e0ea-0021-9cfb-66c1866ca3ce"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn-up.perecbass.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b4n1pcO8ST3JkGtj8YymXVrW17LEe2EHec5wY7hMMR4"
      short-id: "6a2b5c9d"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_9"
    type: vless
    server: "fl.windconnect.pro"
    port: 443
    uuid: "af00e0c4-decf-48f2-9013-56abe9c9efcd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fl.windconnect.pro"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "40Tmrw44FhOyoqCQiOfR2kCgxEPXrBLLv6oYFvjbGUI"
      short-id: "3c6ec7b2d73a28b6"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_10"
    type: vless
    server: "2.26.100.192"
    port: 2087
    uuid: "40205ae5-d30f-4216-b2e0-0506dbbd382e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Ku60WZ3HEdE07DoEBJ5I9o_fjcN_bhdK8bTW3RJjBmM"
      short-id: "c226283c4de5b1ad"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇫🇮_11"
    type: vless
    server: "185.218.194.71"
    port: 443
    uuid: "31216f81-3139-0021-bac4-646680314264"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "b4n1pcO8ST3JkGtj8YymXVrW17LEe2EHec5wY7hMMR4"
      short-id: "e1f8a3b6"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_12"
    type: vless
    server: "fl.musicperec.ru"
    port: 443
    uuid: "31216f81-3139-0021-bac4-646680314264"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "b4n1pcO8ST3JkGtj8YymXVrW17LEe2EHec5wY7hMMR4"
      short-id: "e1f8a3b6"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_13"
    type: vless
    server: "87.239.249.137"
    port: 443
    uuid: "67eb6b17-7797-4ded-bf52-423c4c5f6cbd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.foxsports.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "G7bpUPFSW28-oE6ff8qZac1_apU6PiJ-GHmi7tAPDSY"
      short-id: "91af08b1ce1f"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_14"
    type: vless
    server: "2.26.100.192"
    port: 445
    uuid: "40205ae5-d30f-4216-b2e0-0506dbbd382e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Ku60WZ3HEdE07DoEBJ5I9o_fjcN_bhdK8bTW3RJjBmM"
      short-id: "c226283c4de5b1ad"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_15"
    type: vless
    server: "5.61.91.206"
    port: 443
    uuid: "bd99da97-265e-0021-82cc-4ec009fe9ce2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b4n1pcO8ST3JkGtj8YymXVrW17LEe2EHec5wY7hMMR4"
      short-id: "0a4b7c3d"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_16"
    type: vless
    server: "eu-north-fi-1.hanvpn.biz"
    port: 443
    uuid: "d9d0f208-d582-41d5-bb7b-742671402810"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-north-fi-1.hanvpn.biz"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "nnkPnz6R86-6xG92s8k-1DUQPXAJIVMoMWDLPghh4x4"
      short-id: "0173b2681806bc97"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_17"
    type: vless
    server: "31.77.199.182"
    port: 443
    uuid: "c09cfd91-b234-4998-9bed-a0211b7f5c3c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fi2.yservice.help"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "-qLezG1nUEtvOJi-Ra7WRYv-aHkv3PSefEuXpWV2G04"
      short-id: "abcd1234"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_18"
    type: vless
    server: "185.218.194.69"
    port: 443
    uuid: "31216f81-3139-0021-bac4-646680314264"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b4n1pcO8ST3JkGtj8YymXVrW17LEe2EHec5wY7hMMR4"
      short-id: "e1f8a3b6"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_19"
    type: vless
    server: "144.31.50.236"
    port: 443
    uuid: "1c332eae-7e02-4acd-996d-4eb3e652401c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yandex.ru"
    client-fingerprint: "randomized"
    reality-opts:
      public-key: "uitO4Z8t9TplwwYaqwLqh5rfxDh_X8bOBiNuPbzvaEM"
      short-id: "bbe46bd8f6b96839"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_20"
    type: vless
    server: "2.26.91.57"
    port: 443
    uuid: "af00e0c4-decf-48f2-9013-56abe9c9efcd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fl.windconnect.pro"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "40Tmrw44FhOyoqCQiOfR2kCgxEPXrBLLv6oYFvjbGUI"
      short-id: "3c6ec7b2d73a28b6"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_21"
    type: vless
    server: "prep.wwwinternetvideo.click"
    port: 443
    uuid: "1c332eae-7e02-4acd-996d-4eb3e652401c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yandex.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "uitO4Z8t9TplwwYaqwLqh5rfxDh_X8bOBiNuPbzvaEM"
      short-id: "bbe46bd8f6b96839"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_22"
    type: trojan
    server: "vvbgh.131.pp.ua"
    port: 443
    password: "98b419ef-83a2-4d1b-a23d-566b7f24477b"
    sni: "vvbgh.131.pp.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_23"
    type: trojan
    server: "bbbnhj.131.pp.ua"
    port: 443
    password: "98b419ef-83a2-4d1b-a23d-566b7f24477b"
    sni: "bbbnhj.131.pp.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_24"
    type: trojan
    server: "65.108.205.61"
    port: 443
    password: "88939272-790a-441f-b12b-8ce531aca810"
    sni: "polo01.kctr2038.icu"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_25"
    type: trojan
    server: "nnnmjju.131.pp.ua"
    port: 443
    password: "98b419ef-83a2-4d1b-a23d-566b7f24477b"
    sni: "nnnmjju.131.pp.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_26"
    type: trojan
    server: "144.31.82.35"
    port: 443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_27"
    type: trojan
    server: "45.12.70.200"
    port: 443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_28"
    type: trojan
    server: "65.108.205.61"
    port: 443
    password: "62b78c9b-16cb-4ee6-824b-a4f856cf18f3"
    sni: "65.108.205.61"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_29"
    type: ss
    server: "84.247.155.196"
    port: 80
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇫🇮_1"
      - "🇫🇮_2"
      - "🇫🇮_3"
      - "🇫🇮_4"
      - "🇫🇮_5"
      - "🇫🇮_6"
      - "🇫🇮_7"
      - "🇫🇮_8"
      - "🇫🇮_9"
      - "🇫🇮_10"
      - "🇫🇮_11"
      - "🇫🇮_12"
      - "🇫🇮_13"
      - "🇫🇮_14"
      - "🇫🇮_15"
      - "🇫🇮_16"
      - "🇫🇮_17"
      - "🇫🇮_18"
      - "🇫🇮_19"
      - "🇫🇮_20"
      - "🇫🇮_21"
      - "🇫🇮_22"
      - "🇫🇮_23"
      - "🇫🇮_24"
      - "🇫🇮_25"
      - "🇫🇮_26"
      - "🇫🇮_27"
      - "🇫🇮_28"
      - "🇫🇮_29"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇫🇮_1"
      - "🇫🇮_2"
      - "🇫🇮_3"
      - "🇫🇮_4"
      - "🇫🇮_5"
      - "🇫🇮_6"
      - "🇫🇮_7"
      - "🇫🇮_8"
      - "🇫🇮_9"
      - "🇫🇮_10"
      - "🇫🇮_11"
      - "🇫🇮_12"
      - "🇫🇮_13"
      - "🇫🇮_14"
      - "🇫🇮_15"
      - "🇫🇮_16"
      - "🇫🇮_17"
      - "🇫🇮_18"
      - "🇫🇮_19"
      - "🇫🇮_20"
      - "🇫🇮_21"
      - "🇫🇮_22"
      - "🇫🇮_23"
      - "🇫🇮_24"
      - "🇫🇮_25"
      - "🇫🇮_26"
      - "🇫🇮_27"
      - "🇫🇮_28"
      - "🇫🇮_29"

rules:
  - MATCH,PROXY
