name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇫🇮_1"
    type: vless
    server: "185.145.245.144"
    port: 443
    uuid: "618acefa-2ff1-41b0-a295-f8a08858a897"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d.tranzit-net.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "IAdOYYmEMPFAhpVUhqfML58AVtYPdAb71R_HAPf0N0k"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_2"
    type: vless
    server: "31.76.46.138"
    port: 20422
    uuid: "d8523317-503e-43ad-b2c3-e5f77d725848"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "ZUQTvwYk_hDqSrw36uc18MkeEIXIGZZGsf5XWVwdqAQ"
      short-id: "90"
  - name: "🇫🇮_3"
    type: vless
    server: "185.79.138.71"
    port: 448
    uuid: "0b0915d7-6800-4580-a44b-77d84f105e6a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.samsung.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "CsDgNRcCwCkPIslfZpKTIK71KFpIFNsotbdzKcZVoH8"
      short-id: "cd21e552537c7c0b"
  - name: "🇫🇮_4"
    type: vless
    server: "83.219.97.128"
    port: 13443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "auto.cendora.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "gc9oXe37KCCm3J1dJ03wdGsnxPBdeEkRPOvl_t-vfVM"
      short-id: "a7f3c91b2e6d84c0"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_5"
    type: vless
    server: "de42.tranzit-net.ru"
    port: 443
    uuid: "be3c103d-2c93-4f8e-adb9-2631537f80eb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d.tranzit-net.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "IAdOYYmEMPFAhpVUhqfML58AVtYPdAb71R_HAPf0N0k"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_6"
    type: vless
    server: "2.27.208.9"
    port: 443
    uuid: "dabb9a19-03ab-4cdf-8963-d3c45eb0f80d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fin4.freeinternat.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bZpzmeWiEJyJQy0W2hHc34Nr6BuFXj1UDd80Cbwh1Fk"
      short-id: "ff776ff77be48b88"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_7"
    type: vless
    server: "fin2.helper-internet.com"
    port: 443
    uuid: "ae8e0f7d-b661-41ca-b55d-d8c383adb2f8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fin2.helper-internet.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "W-zf_ncm9sYALF5EqvUsxqTkYGdAw-tQczT2SqwVMGE"
      short-id: "ff776ff77be48b88"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_8"
    type: vless
    server: "2.26.122.101"
    port: 8443
    uuid: "758f49d3-5f5f-47e7-bfa4-4ce96faf800d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn.shopify.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "NI5Rkfn6zO_gF-UC1nuvJwu4SDakCXh3ygJOKU1EITU"
      short-id: "f747a7a5793b5714"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇫🇮_9"
    type: vless
    server: "fin4.freeinternat.com"
    port: 443
    uuid: "dabb9a19-03ab-4cdf-8963-d3c45eb0f80d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fin4.freeinternat.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bZpzmeWiEJyJQy0W2hHc34Nr6BuFXj1UDd80Cbwh1Fk"
      short-id: "ff776ff77be48b88"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_10"
    type: vless
    server: "138.124.8.117"
    port: 443
    uuid: "ae8e0f7d-b661-41ca-b55d-d8c383adb2f8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fin2.helper-internet.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "W-zf_ncm9sYALF5EqvUsxqTkYGdAw-tQczT2SqwVMGE"
      short-id: "ff776ff77be48b88"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_11"
    type: vless
    server: "5.61.91.207"
    port: 443
    uuid: "9ec52cb8-8daa-0021-ac36-d38295a25e5b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b4n1pcO8ST3JkGtj8YymXVrW17LEe2EHec5wY7hMMR4"
      short-id: "a7b2c9d4"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_12"
    type: vless
    server: "2.26.100.192"
    port: 445
    uuid: "40205ae5-d30f-4216-b2e0-0506dbbd382e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Ku60WZ3HEdE07DoEBJ5I9o_fjcN_bhdK8bTW3RJjBmM"
      short-id: "c226283c4de5b1ad"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_13"
    type: vless
    server: "31.77.202.252"
    port: 443
    uuid: "b72fbee7-5ca7-4fb6-9d91-e92d803149dd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "MQYuCxmU1rN6IvUr7NWirfQB6-TM3KUUJvs-4AssHg4"
      short-id: "3b2921eebc134aa6"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_14"
    type: vless
    server: "de56.tranzit-net.ru"
    port: 443
    uuid: "be3c103d-2c93-4f8e-adb9-2631537f80eb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d.tranzit-net.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "IAdOYYmEMPFAhpVUhqfML58AVtYPdAb71R_HAPf0N0k"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_15"
    type: vless
    server: "2.26.100.192"
    port: 2087
    uuid: "40205ae5-d30f-4216-b2e0-0506dbbd382e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Ku60WZ3HEdE07DoEBJ5I9o_fjcN_bhdK8bTW3RJjBmM"
      short-id: "c226283c4de5b1ad"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇫🇮_16"
    type: vless
    server: "5.61.91.206"
    port: 443
    uuid: "d427a02f-e0ea-0021-9cfb-66c1866ca3ce"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn-up.perecbass.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b4n1pcO8ST3JkGtj8YymXVrW17LEe2EHec5wY7hMMR4"
      short-id: "6a2b5c9d"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_17"
    type: vless
    server: "132-243-223-227.sslip.io"
    port: 2101
    uuid: "2edfd299-fd54-4056-9d79-3c99f19bdae1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "132-243-223-227.sslip.io"
    client-fingerprint: "chrome"
    network: grpc
    grpc-opts:
      grpc-service-name: "fi-grpc-test"
  - name: "🇫🇮_18"
    type: vless
    server: "95.216.27.15"
    port: 2053
    uuid: "ea48c5b6-7a19-4fea-9902-17004a424452"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "JmAuytyIXW4klA7zqeSYi3EtWR0d4fNJCq4nR0LMQE8"
      short-id: "07316dd7d0e11c90"
  - name: "🇫🇮_19"
    type: vless
    server: "5.61.91.206"
    port: 443
    uuid: "bd99da97-265e-0021-82cc-4ec009fe9ce2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b4n1pcO8ST3JkGtj8YymXVrW17LEe2EHec5wY7hMMR4"
      short-id: "0a4b7c3d"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_20"
    type: vless
    server: "83.219.97.128"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nordic.cendora.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "YQTixaXzPVImuRc4TUbrFAekjIiaYV-t5S-HTKlH0AU"
      short-id: "2186a755ed67b034"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_21"
    type: vless
    server: "185.145.245.168"
    port: 443
    uuid: "618acefa-2ff1-41b0-a295-f8a08858a897"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d.tranzit-net.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "IAdOYYmEMPFAhpVUhqfML58AVtYPdAb71R_HAPf0N0k"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_22"
    type: vless
    server: "31.77.202.252"
    port: 20532
    uuid: "b72fbee7-5ca7-4fb6-9d91-e92d803149dd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "MQYuCxmU1rN6IvUr7NWirfQB6-TM3KUUJvs-4AssHg4"
      short-id: "3b2921eebc134aa6"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_23"
    type: vless
    server: "45.155.52.231"
    port: 443
    uuid: "219f9fec-8983-4f6f-af8c-31bd0c6dbf19"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ru2.skydrgn-online.online"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "6p0aVCkOgd-xaxqSMANYABL6O4Tdbftnxjiy5qcmISQ"
      short-id: "0b"
  - name: "🇫🇮_24"
    type: vless
    server: "132.243.223.227"
    port: 2101
    uuid: "2edfd299-fd54-4056-9d79-3c99f19bdae1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "132-243-223-227.sslip.io"
    client-fingerprint: "firefox"
    network: grpc
    grpc-opts:
      grpc-service-name: "fi-grpc-test"
  - name: "🇫🇮_25"
    type: vless
    server: "72.35.246.31"
    port: 1244
    uuid: "2d96d4d6-a276-4ab5-9f20-8dc5cbf6e902"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "axisvpn.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "gHG_cbbi-OJKY2tBQTqz1QryfmmRZEQ7BQgymimukkQ"
      short-id: "6ba85179e30d4fc2"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_26"
    type: trojan
    server: "65.108.205.61"
    port: 443
    password: "62b78c9b-16cb-4ee6-824b-a4f856cf18f3"
    sni: "65.108.205.61"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_27"
    type: trojan
    server: "65.108.205.61"
    port: 443
    password: "88939272-790a-441f-b12b-8ce531aca810"
    sni: "polo01.kctr2038.icu"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_28"
    type: trojan
    server: "144.31.82.35"
    port: 443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇫🇮_1"
      - "🇫🇮_2"
      - "🇫🇮_3"
      - "🇫🇮_4"
      - "🇫🇮_5"
      - "🇫🇮_6"
      - "🇫🇮_7"
      - "🇫🇮_8"
      - "🇫🇮_9"
      - "🇫🇮_10"
      - "🇫🇮_11"
      - "🇫🇮_12"
      - "🇫🇮_13"
      - "🇫🇮_14"
      - "🇫🇮_15"
      - "🇫🇮_16"
      - "🇫🇮_17"
      - "🇫🇮_18"
      - "🇫🇮_19"
      - "🇫🇮_20"
      - "🇫🇮_21"
      - "🇫🇮_22"
      - "🇫🇮_23"
      - "🇫🇮_24"
      - "🇫🇮_25"
      - "🇫🇮_26"
      - "🇫🇮_27"
      - "🇫🇮_28"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇫🇮_1"
      - "🇫🇮_2"
      - "🇫🇮_3"
      - "🇫🇮_4"
      - "🇫🇮_5"
      - "🇫🇮_6"
      - "🇫🇮_7"
      - "🇫🇮_8"
      - "🇫🇮_9"
      - "🇫🇮_10"
      - "🇫🇮_11"
      - "🇫🇮_12"
      - "🇫🇮_13"
      - "🇫🇮_14"
      - "🇫🇮_15"
      - "🇫🇮_16"
      - "🇫🇮_17"
      - "🇫🇮_18"
      - "🇫🇮_19"
      - "🇫🇮_20"
      - "🇫🇮_21"
      - "🇫🇮_22"
      - "🇫🇮_23"
      - "🇫🇮_24"
      - "🇫🇮_25"
      - "🇫🇮_26"
      - "🇫🇮_27"
      - "🇫🇮_28"

rules:
  - MATCH,PROXY
