name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇫🇮_1"
    type: vless
    server: "31.77.199.147"
    port: 4443
    uuid: "20dd9433-389e-4573-ba7b-689619cf13da"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "images.unsplash.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "GvkQwcZWiXQBLzEhTVfQkyPpdgo6Opc3RtLsED9sA0A"
      short-id: "7da2eae792187ab9"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_2"
    type: vless
    server: "212.193.18.183"
    port: 8443
    uuid: "246b101b-4e4a-451f-8e9c-5e8d3b64b4ef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "maps.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "XnPQT554eJohCPNsM8gw9oCS-3NTZmqxNoU36Td-tlM"
      short-id: "a1b2c3d4e5f6"
  - name: "🇫🇮_3"
    type: vless
    server: "144.31.90.72"
    port: 443
    uuid: "4360f941-b541-43d4-8507-2de3763e0cfd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fl.convert-flow.net"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "8ZYjmjb0b2QJKCGMrcdhQNV28jZZPCKgIQbIdqChQ0w"
      short-id: "00a61d55a07de885"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_4"
    type: vless
    server: "5.61.91.206"
    port: 443
    uuid: "bd99da97-265e-0021-82cc-4ec009fe9ce2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b4n1pcO8ST3JkGtj8YymXVrW17LEe2EHec5wY7hMMR4"
      short-id: "0a4b7c3d"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_5"
    type: vless
    server: "fin1.apexvpn.space"
    port: 8443
    uuid: "34b36719-7312-4608-ad2f-3776fd004fcc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amazon.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "wjBCPpdDXJxQhYabEsKQrBH7umpeZYnMOHMviAus1V8"
      short-id: "086007"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_6"
    type: vless
    server: "144.31.50.236"
    port: 443
    uuid: "1c332eae-7e02-4acd-996d-4eb3e652401c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yandex.ru"
    client-fingerprint: "randomized"
    reality-opts:
      public-key: "uitO4Z8t9TplwwYaqwLqh5rfxDh_X8bOBiNuPbzvaEM"
      short-id: "bbe46bd8f6b96839"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_7"
    type: vless
    server: "31.77.199.182"
    port: 443
    uuid: "c09cfd91-b234-4998-9bed-a0211b7f5c3c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fi2.yservice.help"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "-qLezG1nUEtvOJi-Ra7WRYv-aHkv3PSefEuXpWV2G04"
      short-id: "abcd1234"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_8"
    type: vless
    server: "144.31.90.65"
    port: 443
    uuid: "4360f941-b541-43d4-8507-2de3763e0cfd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fl.convert-flow.net"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "8ZYjmjb0b2QJKCGMrcdhQNV28jZZPCKgIQbIdqChQ0w"
      short-id: "00a61d55a07de885"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_9"
    type: vless
    server: "212.193.18.183"
    port: 8446
    uuid: "246b101b-4e4a-451f-8e9c-5e8d3b64b4ef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "maps.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "f6xhmL1XqUJ4zdkaDsh9GuEyXc0JXM2Dp5KwU8VHb0c"
      short-id: "7f8e9d0c1b2a"
    network: grpc
    grpc-opts:
      grpc-service-name: "snob-grpc"
  - name: "🇫🇮_10"
    type: vless
    server: "2.26.91.57"
    port: 443
    uuid: "af00e0c4-decf-48f2-9013-56abe9c9efcd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fl.windconnect.pro"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "40Tmrw44FhOyoqCQiOfR2kCgxEPXrBLLv6oYFvjbGUI"
      short-id: "3c6ec7b2d73a28b6"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_11"
    type: vless
    server: "app-ms-35.ecom-ai-solutions.com"
    port: 443
    uuid: "a71ad164-3b29-4dbe-aa66-24d095ca7b6d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "assets-ms-35.ecom-ai-solutions.com"
    client-fingerprint: "randomized"
    reality-opts:
      public-key: "NA5eMfdHkl_L80S75uxQwUirS9nvZ80V2u1s71KeXkc"
      short-id: "2de63d3fd7261b7e"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_12"
    type: vless
    server: "185.255.179.11"
    port: 9443
    uuid: "d9d0f208-d582-41d5-bb7b-742671402810"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "hub-se-02.hanvpn.cc"
    client-fingerprint: "chrome"
    network: grpc
    grpc-opts:
      grpc-service-name: "se02-grpc-8e47a"
  - name: "🇫🇮_13"
    type: vless
    server: "fl.windconnect.pro"
    port: 443
    uuid: "af00e0c4-decf-48f2-9013-56abe9c9efcd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fl.windconnect.pro"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "40Tmrw44FhOyoqCQiOfR2kCgxEPXrBLLv6oYFvjbGUI"
      short-id: "3c6ec7b2d73a28b6"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_14"
    type: vless
    server: "130.49.77.4"
    port: 8443
    uuid: "0ab925b6-35f7-6e27-e713-925bea65455e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "download.nvidia.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "hwwiWVqYq5b7S0JaXNSxjWSEv_1OUFMaWJGHzeAGyRM"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "TunService"
  - name: "🇫🇮_15"
    type: vless
    server: "185.79.138.71"
    port: 448
    uuid: "0b0915d7-6800-4580-a44b-77d84f105e6a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.samsung.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "CsDgNRcCwCkPIslfZpKTIK71KFpIFNsotbdzKcZVoH8"
      short-id: "cd21e552537c7c0b"
  - name: "🇫🇮_16"
    type: vless
    server: "144.31.90.75"
    port: 443
    uuid: "4360f941-b541-43d4-8507-2de3763e0cfd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fl.convert-flow.net"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "8ZYjmjb0b2QJKCGMrcdhQNV28jZZPCKgIQbIdqChQ0w"
      short-id: "00a61d55a07de885"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_17"
    type: vless
    server: "2.26.89.16"
    port: 443
    uuid: "a71ad164-3b29-4dbe-aa66-24d095ca7b6d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "assets-ms-35.ecom-ai-solutions.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "NA5eMfdHkl_L80S75uxQwUirS9nvZ80V2u1s71KeXkc"
      short-id: "2de63d3fd7261b7e"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_18"
    type: vless
    server: "193.35.17.133"
    port: 8443
    uuid: "34b36719-7312-4608-ad2f-3776fd004fcc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amazon.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "wjBCPpdDXJxQhYabEsKQrBH7umpeZYnMOHMviAus1V8"
      short-id: "086007"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_19"
    type: vless
    server: "95.216.27.15"
    port: 2053
    uuid: "1c81f6d3-5771-4c5d-9fdd-1655eff50634"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "4nfogj5mHqNowtSn_2sXS3xTX8vcH75rFEU2BWvyekM"
      short-id: "d368b94e275ab080"
  - name: "🇫🇮_20"
    type: trojan
    server: "bbbnhj.131.pp.ua"
    port: 443
    password: "98b419ef-83a2-4d1b-a23d-566b7f24477b"
    sni: "bbbnhj.131.pp.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_21"
    type: trojan
    server: "nnnmjju.131.pp.ua"
    port: 443
    password: "98b419ef-83a2-4d1b-a23d-566b7f24477b"
    sni: "nnnmjju.131.pp.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_22"
    type: trojan
    server: "vvbgh.131.pp.ua"
    port: 443
    password: "98b419ef-83a2-4d1b-a23d-566b7f24477b"
    sni: "vvbgh.131.pp.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_23"
    type: trojan
    server: "144.31.82.35"
    port: 443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_24"
    type: trojan
    server: "bbbnnmj.131.pp.ua"
    port: 443
    password: "98b419ef-83a2-4d1b-a23d-566b7f24477b"
    sni: "bbbnnmj.131.pp.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_25"
    type: trojan
    server: "45.12.70.200"
    port: 443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_26"
    type: ss
    server: "65.109.215.118"
    port: 1080
    cipher: "chacha20-ietf-poly1305"
    password: "rSeYcig_XBy8q3k33NpK3A"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇫🇮_1"
      - "🇫🇮_2"
      - "🇫🇮_3"
      - "🇫🇮_4"
      - "🇫🇮_5"
      - "🇫🇮_6"
      - "🇫🇮_7"
      - "🇫🇮_8"
      - "🇫🇮_9"
      - "🇫🇮_10"
      - "🇫🇮_11"
      - "🇫🇮_12"
      - "🇫🇮_13"
      - "🇫🇮_14"
      - "🇫🇮_15"
      - "🇫🇮_16"
      - "🇫🇮_17"
      - "🇫🇮_18"
      - "🇫🇮_19"
      - "🇫🇮_20"
      - "🇫🇮_21"
      - "🇫🇮_22"
      - "🇫🇮_23"
      - "🇫🇮_24"
      - "🇫🇮_25"
      - "🇫🇮_26"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇫🇮_1"
      - "🇫🇮_2"
      - "🇫🇮_3"
      - "🇫🇮_4"
      - "🇫🇮_5"
      - "🇫🇮_6"
      - "🇫🇮_7"
      - "🇫🇮_8"
      - "🇫🇮_9"
      - "🇫🇮_10"
      - "🇫🇮_11"
      - "🇫🇮_12"
      - "🇫🇮_13"
      - "🇫🇮_14"
      - "🇫🇮_15"
      - "🇫🇮_16"
      - "🇫🇮_17"
      - "🇫🇮_18"
      - "🇫🇮_19"
      - "🇫🇮_20"
      - "🇫🇮_21"
      - "🇫🇮_22"
      - "🇫🇮_23"
      - "🇫🇮_24"
      - "🇫🇮_25"
      - "🇫🇮_26"

rules:
  - MATCH,PROXY
