name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇭🇺_1"
    type: vless
    server: "155.117.137.201"
    port: 443
    uuid: "7d6d3391-7bf8-46bf-bd2e-01e82a790017"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn9-40.yahoo.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "CMkW1axrhEXoiJ6anMz9XEjlfqlAtEZya7L0b5ZPMyw"
      short-id: "69da7557f168a46a"
    flow: "xtls-rprx-vision"
  - name: "🇭🇺_2"
    type: vless
    server: "37.221.210.188"
    port: 443
    uuid: "fc64e874-656e-402e-a303-e0d161f907fb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "hu888.bearbeer.digital"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "z-TKWOWgZLfzQ-wNdwXQqVwaUgCmbchM2Xtrk1NGynU"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇭🇺_3"
    type: vless
    server: "155.117.137.81"
    port: 443
    uuid: "7d6d3391-7bf8-46bf-bd2e-01e82a790017"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn4-65.yahoo.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "CMkW1axrhEXoiJ6anMz9XEjlfqlAtEZya7L0b5ZPMyw"
      short-id: "3c9c5d01c6f824dd"
    flow: "xtls-rprx-vision"
  - name: "🇭🇺_4"
    type: vless
    server: "155.117.137.55"
    port: 443
    uuid: "5c2a674b-bf9d-4461-b56d-a9c2bc299d9a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn4-35.yahoo.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "CMkW1axrhEXoiJ6anMz9XEjlfqlAtEZya7L0b5ZPMyw"
      short-id: "7de40c5c4663409d"
    flow: "xtls-rprx-vision"
  - name: "🇭🇺_5"
    type: ss
    server: "146.70.203.254"
    port: 1080
    cipher: "chacha20-ietf-poly1305"
    password: "XF0klw7870vXn3uQIxe19Q"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇭🇺_1"
      - "🇭🇺_2"
      - "🇭🇺_3"
      - "🇭🇺_4"
      - "🇭🇺_5"


rules:
  - MATCH,PROXY
