name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇮🇪_1"
    type: vless
    server: "50.7.5.166"
    port: 443
    uuid: "cd3bb7d9-7df3-4644-ac05-c260990ac277"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ir-new.failspace.top"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇮🇪_2"
    type: vless
    server: "50.7.5.163"
    port: 443
    uuid: "cd3bb7d9-7df3-4644-ac05-c260990ac277"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ir-viper.failspace.top"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇮🇪_3"
    type: vless
    server: "50.7.5.164"
    port: 443
    uuid: "cd3bb7d9-7df3-4644-ac05-c260990ac277"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ir.failspace.top"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇮🇪_4"
    type: vless
    server: "ir-new.failspace.top"
    port: 443
    uuid: "cd3bb7d9-7df3-4644-ac05-c260990ac277"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ir-new.failspace.top"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇮🇪_5"
    type: trojan
    server: "well-goshawk.rooster465.autos"
    port: 443
    password: "EQ30679154"
    sni: "well-goshawk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_6"
    type: trojan
    server: "well-goshawk.rooster465.autos"
    port: 443
    password: "NQ26071394"
    sni: "well-goshawk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_7"
    type: trojan
    server: "worthy-perch.rooster465.autos"
    port: 443
    password: "FH72359861"
    sni: "worthy-perch.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_8"
    type: trojan
    server: "adapting-basilisk.rooster465.autos"
    port: 443
    password: "CF68213490"
    sni: "adapting-basilisk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_9"
    type: trojan
    server: "well-goshawk.rooster465.autos"
    port: 443
    password: "ON38567014"
    sni: "well-goshawk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_10"
    type: trojan
    server: "verified-ringtail.rooster465.autos"
    port: 443
    password: "NQ26071394"
    sni: "verified-ringtail.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_11"
    type: ss
    server: "128.251.10.166"
    port: 443
    cipher: "chacha20-ietf-poly1305"
    password: "fz0bBBPUiKFgPDvJ"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇮🇪_1"
      - "🇮🇪_2"
      - "🇮🇪_3"
      - "🇮🇪_4"
      - "🇮🇪_5"
      - "🇮🇪_6"
      - "🇮🇪_7"
      - "🇮🇪_8"
      - "🇮🇪_9"
      - "🇮🇪_10"
      - "🇮🇪_11"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇮🇪_1"
      - "🇮🇪_2"
      - "🇮🇪_3"
      - "🇮🇪_4"
      - "🇮🇪_5"
      - "🇮🇪_6"
      - "🇮🇪_7"
      - "🇮🇪_8"
      - "🇮🇪_9"
      - "🇮🇪_10"
      - "🇮🇪_11"

rules:
  - MATCH,PROXY
