name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇮🇷_1"
    type: vless
    server: "mci.v2plus.ovh"
    port: 80
    uuid: "0c6c9627-95fe-418a-bd4c-50df888c44bd"
    udp: true
    network: ws
    ws-opts:
      path: "/ffEt2nn4iTWiXfi8"
      headers:
        Host: "worker3.bobiv63003.workers.dev"
  - name: "🇮🇷_2"
    type: vless
    server: "188.121.123.147"
    port: 46153
    uuid: "4b9ac6db-3e71-409b-ad39-438b0c6027af"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "play.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "juzUXIxIbuFscz16cvvS0W7rKiK0P0shJLvKd4Oz-Ro"
      short-id: "01c39f90eb0455e1"
  - name: "🇮🇷_3"
    type: vless
    server: "45.131.4.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime59.workers.dev"
  - name: "🇮🇷_4"
    type: trojan
    server: "ir1.iobase.ir"
    port: 443
    password: "a6xjq4UD2t"
    sni: "ir1.iobase.ir"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇷_5"
    type: trojan
    server: "193.151.134.182"
    port: 443
    password: "diCyRX1d"
    sni: "iprostable.enterprises"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇷_6"
    type: ss
    server: "185.188.106.10"
    port: 443
    cipher: "none"
    password: "RSzEIkk2EsHEAVj15N5E/A=="
    udp: true
  - name: "🇮🇷_7"
    type: ss
    server: "185.188.107.10"
    port: 443
    cipher: "none"
    password: "RSzEIkk2EsHEAVj15N5E/A=="
    udp: true
  - name: "🇮🇷_8"
    type: ss
    server: "185.188.106.10"
    port: 443
    cipher: "none"
    password: "RSzEIkk2EsHEAVj15N5E/A=="
    udp: true
  - name: "🇮🇷_9"
    type: ss
    server: "185.188.105.10"
    port: 443
    cipher: "none"
    password: "RSzEIkk2EsHEAVj15N5E/A=="
    udp: true
  - name: "🇮🇷_10"
    type: ss
    server: "185.188.105.11"
    port: 443
    cipher: "none"
    password: "RSzEIkk2EsHEAVj15N5E/A=="
    udp: true
  - name: "🇮🇷_11"
    type: ss
    server: "185.188.104.10"
    port: 443
    cipher: "none"
    password: "RSzEIkk2EsHEAVj15N5E/A=="
    udp: true
  - name: "🇮🇷_12"
    type: ss
    server: "dkstatics-public.digikala.com"
    port: 443
    cipher: "none"
    password: "RSzEIkk2EsHEAVj15N5E/A=="
    udp: true
  - name: "🇮🇷_13"
    type: ss
    server: "185.188.107.10"
    port: 443
    cipher: "none"
    password: "RSzEIkk2EsHEAVj15N5E/A=="
    udp: true
  - name: "🇮🇷_14"
    type: ss
    server: "185.188.105.10"
    port: 443
    cipher: "none"
    password: "RSzEIkk2EsHEAVj15N5E/A=="
    udp: true
  - name: "🇮🇷_15"
    type: ss
    server: "185.188.104.10"
    port: 443
    cipher: "none"
    password: "RSzEIkk2EsHEAVj15N5E/A=="
    udp: true
  - name: "🇮🇷_16"
    type: ss
    server: "dkstatics-public.digikala.com"
    port: 443
    cipher: "none"
    password: "RSzEIkk2EsHEAVj15N5E/A=="
    udp: true
  - name: "🇮🇷_17"
    type: ss
    server: "185.188.105.11"
    port: 443
    cipher: "none"
    password: "RSzEIkk2EsHEAVj15N5E/A=="
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇮🇷_1"
      - "🇮🇷_2"
      - "🇮🇷_3"
      - "🇮🇷_4"
      - "🇮🇷_5"
      - "🇮🇷_6"
      - "🇮🇷_7"
      - "🇮🇷_8"
      - "🇮🇷_9"
      - "🇮🇷_10"
      - "🇮🇷_11"
      - "🇮🇷_12"
      - "🇮🇷_13"
      - "🇮🇷_14"
      - "🇮🇷_15"
      - "🇮🇷_16"
      - "🇮🇷_17"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇮🇷_1"
      - "🇮🇷_2"
      - "🇮🇷_3"
      - "🇮🇷_4"
      - "🇮🇷_5"
      - "🇮🇷_6"
      - "🇮🇷_7"
      - "🇮🇷_8"
      - "🇮🇷_9"
      - "🇮🇷_10"
      - "🇮🇷_11"
      - "🇮🇷_12"
      - "🇮🇷_13"
      - "🇮🇷_14"
      - "🇮🇷_15"
      - "🇮🇷_16"
      - "🇮🇷_17"

rules:
  - MATCH,PROXY
