name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇮🇹_1"
    type: vless
    server: "150.241.73.177"
    port: 13443
    uuid: "b80b392c-0cf4-42f9-ae54-9f862e3ba276"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "auto.cendora.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "gc9oXe37KCCm3J1dJ03wdGsnxPBdeEkRPOvl_t-vfVM"
      short-id: "a7f3c91b2e6d84c0"
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_2"
    type: vless
    server: "57.131.38.163"
    port: 2053
    uuid: "d4b08cd6-0903-411a-9dac-45dbdf5c9712"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Ej2H5ucT7qKegYcT8wODdlxa-cLHr7F4hDVUHzAhcnc"
      short-id: "5b8a942318178e7b"
  - name: "🇮🇹_3"
    type: vless
    server: "31.76.113.94"
    port: 443
    uuid: "419f25c1-bc35-412e-93fb-258efee859b5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "it1.murhost.network"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "H9-mAKSPlIPGVDI2uBSZqxxOkLGTsfciqL5rAKIwUlg"
      short-id: "ad416bcb922d986b"
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_4"
    type: vless
    server: "fi.riotvpn.eu"
    port: 9443
    uuid: "2e9d3568-f977-4cea-800d-fd9a876e7252"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "static.vkimages.io"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "8h8t5eBWL9oERK7xWHQLFJE5j6sZdgNDQAs3EGnNbho"
      short-id: "2f49bccf11150ef2"
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_5"
    type: vless
    server: "it1.murhost.network"
    port: 443
    uuid: "419f25c1-bc35-412e-93fb-258efee859b5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "it1.murhost.network"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "H9-mAKSPlIPGVDI2uBSZqxxOkLGTsfciqL5rAKIwUlg"
      short-id: "ad416bcb922d986b"
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_6"
    type: vless
    server: "92yqc126g8qwe6v23n01.haiyucloud.com"
    port: 49475
    uuid: "485717cf-e96c-40db-9bc1-624060b89f20"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.python.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "i0nN_0uLl5ha8pIf6gNNLeLQe7it-nXDFLC5eM1BHV4"
      short-id: "bb9b8f5f"
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_7"
    type: vless
    server: "204.216.216.23"
    port: 1114
    uuid: "6ba2eac6-0ec9-44ca-a42b-a8e23aafb530"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "WfkCF0eEuIoO0MyJsKOddU89QrTzCZ4y2dzCJbH99CQ"
      short-id: "79a1e14b"
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_8"
    type: vless
    server: "204.216.216.23"
    port: 10086
    uuid: "9f0285ee-20ca-4953-bcdb-86a920652923"
    udp: true
  - name: "🇮🇹_9"
    type: vless
    server: "31.76.113.64"
    port: 443
    uuid: "33c150b7-c0ca-4133-9a52-6f1207da9b8b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "vnjp7zIK2H3CGdjSis_79KXqS6IG-opmpbETPUD-EC8"
      short-id: "15affa0af66dfc79"
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_10"
    type: vless
    server: "211.76.176.156"
    port: 49475
    uuid: "485717cf-e96c-40db-9bc1-624060b89f20"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.python.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "i0nN_0uLl5ha8pIf6gNNLeLQe7it-nXDFLC5eM1BHV4"
      short-id: "bb9b8f5f"
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_11"
    type: vless
    server: "150.241.73.137"
    port: 13443
    uuid: "b80b392c-0cf4-42f9-ae54-9f862e3ba276"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "auto.cendora.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "gc9oXe37KCCm3J1dJ03wdGsnxPBdeEkRPOvl_t-vfVM"
      short-id: "a7f3c91b2e6d84c0"
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_12"
    type: vless
    server: "italy.funvideorus.net"
    port: 443
    uuid: "33c150b7-c0ca-4133-9a52-6f1207da9b8b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "vnjp7zIK2H3CGdjSis_79KXqS6IG-opmpbETPUD-EC8"
      short-id: "15affa0af66dfc79"
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_13"
    type: vless
    server: "104.105.78.231"
    port: 17780
    uuid: "a06119a7-4f1a-4592-86d9-e050a332b2b3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "amp-api-edge.apps.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "CHNEnURyZzZ1OQwb5SD2Ze8K9eIY2oggyrV5FOIsU28"
      short-id: "a0fbc54d937aaccb"
  - name: "🇮🇹_14"
    type: trojan
    server: "91.193.5.121"
    port: 8443
    password: "Aimer"
    sni: "ngepz.ambercc.filegear-sg.me"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇮🇹_1"
      - "🇮🇹_2"
      - "🇮🇹_3"
      - "🇮🇹_4"
      - "🇮🇹_5"
      - "🇮🇹_6"
      - "🇮🇹_7"
      - "🇮🇹_8"
      - "🇮🇹_9"
      - "🇮🇹_10"
      - "🇮🇹_11"
      - "🇮🇹_12"
      - "🇮🇹_13"
      - "🇮🇹_14"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇮🇹_1"
      - "🇮🇹_2"
      - "🇮🇹_3"
      - "🇮🇹_4"
      - "🇮🇹_5"
      - "🇮🇹_6"
      - "🇮🇹_7"
      - "🇮🇹_8"
      - "🇮🇹_9"
      - "🇮🇹_10"
      - "🇮🇹_11"
      - "🇮🇹_12"
      - "🇮🇹_13"
      - "🇮🇹_14"

rules:
  - MATCH,PROXY
