name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇮🇹_1"
    type: vless
    server: "31.76.71.130"
    port: 443
    uuid: "75079a7f-75b5-418b-8a65-f7b2f438cd4a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "eNvO4-6_VFngHHC6D5AhcCpCpOdi5gY7-Srimhh-6Xw"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_2"
    type: vless
    server: "172.238.232.239"
    port: 32833
    uuid: "167ed405-7de9-4bff-b1ea-6e3d49c76b0b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "PaTDdYBrlh1xBixdI0igvRRkf0vnUwMRzi-4oDyfS20"
      short-id: "a0a305ccc8e94aa8"
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_3"
    type: vless
    server: "31.76.71.130"
    port: 443
    uuid: "82d145c1-d691-4eef-9de1-9c316db4859a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "eNvO4-6_VFngHHC6D5AhcCpCpOdi5gY7-Srimhh-6Xw"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_4"
    type: vless
    server: "31.76.71.130"
    port: 443
    uuid: "d900a139-8b5f-4758-8a32-389c6f36fc86"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "eNvO4-6_VFngHHC6D5AhcCpCpOdi5gY7-Srimhh-6Xw"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_5"
    type: vless
    server: "57.131.38.163"
    port: 2053
    uuid: "d4b08cd6-0903-411a-9dac-45dbdf5c9712"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Ej2H5ucT7qKegYcT8wODdlxa-cLHr7F4hDVUHzAhcnc"
      short-id: "5b8a942318178e7b"
  - name: "🇮🇹_6"
    type: trojan
    server: "91.193.5.121"
    port: 8443
    password: "Aimer"
    sni: "ngepz.ambercc.filegear-sg.me"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇹_7"
    type: ss
    server: "57.131.48.45"
    port: 8388
    cipher: "aes-256-gcm"
    password: "itzvpn@321"
    udp: true
  - name: "🇮🇹_8"
    type: ss
    server: "57.131.48.45"
    port: 8388
    cipher: "aes-256-gcm"
    password: "itzvpn@321"
    udp: true
  - name: "🇮🇹_9"
    type: ss
    server: "194.87.47.204"
    port: 10901
    cipher: "aes-256-gcm"
    password: "d1fa2f4b98a38bc8"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇮🇹_1"
      - "🇮🇹_2"
      - "🇮🇹_3"
      - "🇮🇹_4"
      - "🇮🇹_5"
      - "🇮🇹_6"
      - "🇮🇹_7"
      - "🇮🇹_8"
      - "🇮🇹_9"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇮🇹_1"
      - "🇮🇹_2"
      - "🇮🇹_3"
      - "🇮🇹_4"
      - "🇮🇹_5"
      - "🇮🇹_6"
      - "🇮🇹_7"
      - "🇮🇹_8"
      - "🇮🇹_9"

rules:
  - MATCH,PROXY
