name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇷🇺_1"
    type: vless
    server: "83.222.8.125"
    port: 8443
    uuid: "228ecfd3-9bf0-42fd-a50e-581f84022513"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ozone.nl"
    client-fingerprint: "random"
    reality-opts:
      public-key: "yyH7Fyfh1ULPH4L5mFVtqPf_rB1IY6jwDgOuIRY7-wA"
      short-id: "ccbe97abe7"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_2"
    type: vless
    server: "195.133.73.65"
    port: 443
    uuid: "ebd1c0d6-7ff4-4b9f-8692-237517a27a64"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "anyfile2file.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "mza5Hn1aolSz65qu-UwvBP3oesxMe25r11o4nxvikF0"
      short-id: "64c1fe36c7846400"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_3"
    type: vless
    server: "176.109.107.1"
    port: 9889
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "ycPIUcY6ci2yi7YA_OHc20e4gzxEdJTqpmeShxSuHRU"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_4"
    type: vless
    server: "83.222.8.125"
    port: 8443
    uuid: "6db7ea14-ed33-4591-a9b1-f1e91b1c0ff5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.ozone.nl"
    client-fingerprint: "random"
    reality-opts:
      public-key: "yyH7Fyfh1ULPH4L5mFVtqPf_rB1IY6jwDgOuIRY7-wA"
      short-id: "ccbe97abe7"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_5"
    type: vless
    server: "176.53.162.58"
    port: 24449
    uuid: "b229d38c-35ec-4a0b-9c86-8fceba243d6c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "spry-jolt.cdn.cachefleet.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "esOi15BFVX7pHyci7GQp8_FVlY2EmjSF2-0pPu4lIlk"
      short-id: "defeaa98406c7bdf"
    network: grpc
    grpc-opts:
      grpc-service-name: "telegram-bridge"
  - name: "🇷🇺_6"
    type: vless
    server: "176.109.107.1"
    port: 9881
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "ycPIUcY6ci2yi7YA_OHc20e4gzxEdJTqpmeShxSuHRU"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_7"
    type: vless
    server: "176.108.247.31"
    port: 9844
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: "aabb"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_8"
    type: vless
    server: "79.174.95.96"
    port: 443
    uuid: "b4ba6557-c6ce-43fc-afe6-cc6a2d059356"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "tVc65Jg20nTeP9qsSd9WIqRjLqU-PWKFYtBYHQbwtyw"
      short-id: "a1b2c3d4"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇷🇺_9"
    type: vless
    server: "109.120.181.153"
    port: 443
    uuid: "adc11f30-e4cb-4985-bf5e-f9ded69c019f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eh.vk.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "fNfokzklCF4l_c8k8PciOCjm5ecNoF_sNLjEtaO-xzI"
      short-id: "db04ce8bdb8900f1"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_10"
    type: vless
    server: "176.108.246.58"
    port: 9881
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    reality-opts:
      public-key: "ycPIUcY6ci2yi7YA_OHc20e4gzxEdJTqpmeShxSuHRU"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_11"
    type: vless
    server: "176.53.162.58"
    port: 24448
    uuid: "b229d38c-35ec-4a0b-9c86-8fceba243d6c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "spry-jolt.cdn.cachefleet.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "esOi15BFVX7pHyci7GQp8_FVlY2EmjSF2-0pPu4lIlk"
      short-id: "defeaa98406c7bdf"
    network: grpc
    grpc-opts:
      grpc-service-name: "telegram-bridge"
  - name: "🇷🇺_12"
    type: vless
    server: "5.42.99.64"
    port: 8443
    uuid: "c53ea5e9-ed8b-4990-805d-7f1d6451426c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "du-rov.secureservice.top"
    client-fingerprint: "random"
    reality-opts:
      public-key: "fSVfR9NB-6J6smrZlavi0GWd8JfDh0aXuEkKbtuFzUI"
      short-id: "3cbc3d737fb9c4af"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_13"
    type: vless
    server: "176.53.162.58"
    port: 24450
    uuid: "b229d38c-35ec-4a0b-9c86-8fceba243d6c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "spry-jolt.cdn.cachefleet.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "esOi15BFVX7pHyci7GQp8_FVlY2EmjSF2-0pPu4lIlk"
      short-id: "defeaa98406c7bdf"
    network: grpc
    grpc-opts:
      grpc-service-name: "telegram-bridge"
  - name: "🇷🇺_14"
    type: vless
    server: "176.53.162.58"
    port: 24446
    uuid: "b229d38c-35ec-4a0b-9c86-8fceba243d6c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "spry-jolt.cdn.cachefleet.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "esOi15BFVX7pHyci7GQp8_FVlY2EmjSF2-0pPu4lIlk"
      short-id: "defeaa98406c7bdf"
    network: grpc
    grpc-opts:
      grpc-service-name: "telegram-bridge"
  - name: "🇷🇺_15"
    type: vless
    server: "n98o5teg7.dendiboss.org"
    port: 443
    uuid: "386d4342-768d-4ed0-9478-4dba23220aed"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "n98o5teg7.dendiboss.org"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Oq-xzuGJS90vXtDM5_WM73LESpRBoXB7drkaBdUPW1Y"
      short-id: "68721887"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_16"
    type: vless
    server: "du-rov.secureservice.top"
    port: 8443
    uuid: "c53ea5e9-ed8b-4990-805d-7f1d6451426c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "du-rov.secureservice.top"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "fSVfR9NB-6J6smrZlavi0GWd8JfDh0aXuEkKbtuFzUI"
      short-id: "3cbc3d737fb9c4af"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_17"
    type: vless
    server: "95.163.232.98"
    port: 443
    uuid: "386d4342-768d-4ed0-9478-4dba23220aed"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "ZgSVwP_wlM4-oG8E03W3cMqK_VrS8oHXF4wzyBkISWo"
      short-id: "a1b2c3d4"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇷🇺_18"
    type: vless
    server: "45.12.75.242"
    port: 26424
    uuid: "633f424e-2b11-48da-a6b3-a849dd71456f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ya.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0"
      short-id: "23103e1e"
  - name: "🇷🇺_19"
    type: trojan
    server: "45.147.200.44"
    port: 443
    password: "265f092f-418b-30c9-a479-4800fd44dd19mielink"
    sni: "$$paydiu.com"
    skip-cert-verify: true
    udp: true
  - name: "🇷🇺_20"
    type: trojan
    server: "188.225.37.70"
    port: 11443
    password: "WaGG8TGpKhcMU-F-e9vrjB7MnUHGPhtt"
    sni: "msk1.cenza.cloud"
    skip-cert-verify: true
    udp: true
  - name: "🇷🇺_21"
    type: trojan
    server: "217.16.17.127"
    port: 25565
    password: "WaGG8TGpKhcMU-F-e9vrjB7MnUHGPhtt"
    sni: "vkc2.safesurf.cloud"
    skip-cert-verify: true
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇷🇺_22"
    type: trojan
    server: "tr-wien.unlimited-access.ru"
    port: 443
    password: "kxHw-Dk-e9dffgzYszMlEqLJ92AnY3Pi"
    sni: "tr-wien.unlimited-access.ru"
    skip-cert-verify: true
    udp: true
  - name: "🇷🇺_23"
    type: trojan
    server: "ru-1.krugvpn.com"
    port: 443
    password: "jj59d0f73f5d6"
    sni: "ru-1.krugvpn.com"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇷🇺_1"
      - "🇷🇺_2"
      - "🇷🇺_3"
      - "🇷🇺_4"
      - "🇷🇺_5"
      - "🇷🇺_6"
      - "🇷🇺_7"
      - "🇷🇺_8"
      - "🇷🇺_9"
      - "🇷🇺_10"
      - "🇷🇺_11"
      - "🇷🇺_12"
      - "🇷🇺_13"
      - "🇷🇺_14"
      - "🇷🇺_15"
      - "🇷🇺_16"
      - "🇷🇺_17"
      - "🇷🇺_18"
      - "🇷🇺_19"
      - "🇷🇺_20"
      - "🇷🇺_21"
      - "🇷🇺_22"
      - "🇷🇺_23"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇷🇺_1"
      - "🇷🇺_2"
      - "🇷🇺_3"
      - "🇷🇺_4"
      - "🇷🇺_5"
      - "🇷🇺_6"
      - "🇷🇺_7"
      - "🇷🇺_8"
      - "🇷🇺_9"
      - "🇷🇺_10"
      - "🇷🇺_11"
      - "🇷🇺_12"
      - "🇷🇺_13"
      - "🇷🇺_14"
      - "🇷🇺_15"
      - "🇷🇺_16"
      - "🇷🇺_17"
      - "🇷🇺_18"
      - "🇷🇺_19"
      - "🇷🇺_20"
      - "🇷🇺_21"
      - "🇷🇺_22"
      - "🇷🇺_23"

rules:
  - MATCH,PROXY
