name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇷🇺_1"
    type: vless
    server: "tgfree.rush-server.com"
    port: 443
    uuid: "ebd1c0d6-7ff4-4b9f-8692-237517a27a64"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "anyfile2file.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "mza5Hn1aolSz65qu-UwvBP3oesxMe25r11o4nxvikF0"
      short-id: "64c1fe36c7846400"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_2"
    type: vless
    server: "45.12.75.242"
    port: 26424
    uuid: "633f424e-2b11-48da-a6b3-a849dd71456f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ya.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0"
      short-id: "23103e1e"
  - name: "🇷🇺_3"
    type: vless
    server: "spb.snappycore.com"
    port: 443
    uuid: "8f9c5260-9456-472b-8ee2-444500ba6cab"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "spb.snappycore.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SCuasCPva4lPGu-QRP955zZB8f6i7ydHBQh6bsSlrgo"
      short-id: "3d87c490ddd41305"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_4"
    type: vless
    server: "84.201.164.49"
    port: 443
    uuid: "06ec3898-f952-52a5-8547-51ae1e6f0a62"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "api-maps.yandex.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "2SVMBXiViUclgzkSfLCV2w6dOMJwA61YGFv7ne5wMgM"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_5"
    type: vless
    server: "195.133.73.65"
    port: 443
    uuid: "ebd1c0d6-7ff4-4b9f-8692-237517a27a64"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "anyfile2file.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "mza5Hn1aolSz65qu-UwvBP3oesxMe25r11o4nxvikF0"
      short-id: "64c1fe36c7846400"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_6"
    type: trojan
    server: "45.147.200.44"
    port: 443
    password: "265f092f-418b-30c9-a479-4800fd44dd19mielink"
    sni: "$$paydiu.com"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇷🇺_1"
      - "🇷🇺_2"
      - "🇷🇺_3"
      - "🇷🇺_4"
      - "🇷🇺_5"
      - "🇷🇺_6"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇷🇺_1"
      - "🇷🇺_2"
      - "🇷🇺_3"
      - "🇷🇺_4"
      - "🇷🇺_5"
      - "🇷🇺_6"

rules:
  - MATCH,PROXY
