name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇷🇺_1"
    type: vless
    server: "31.76.34.216"
    port: 443
    uuid: "94def50e-5f3c-4e4c-9719-3325f42d2131"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ru-c-1.minzt.su"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "XrgbY2hKJQG8QOZO2J1pGmZsbvjSsSWoM9iULIMGK00"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_2"
    type: vless
    server: "5.42.99.64"
    port: 8443
    uuid: "c53ea5e9-ed8b-4990-805d-7f1d6451426c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "du-rov.secureservice.top"
    client-fingerprint: "random"
    reality-opts:
      public-key: "fSVfR9NB-6J6smrZlavi0GWd8JfDh0aXuEkKbtuFzUI"
      short-id: "3cbc3d737fb9c4af"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_3"
    type: vless
    server: "189.74.114.135"
    port: 443
    uuid: "ea954244-bd25-4233-a77e-bf04b7a7fd5a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "api.setevoyprichal.cc"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "r5WB5FnSCt4eeBC1FJMfkWHbzsMuabo0Rc6wuAhlZUs"
      short-id: "a8"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_4"
    type: vless
    server: "104.171.132.197"
    port: 443
    uuid: "e0b9fb0f-1bbd-478b-9580-c2294778338b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "es.avroraservice.online"
    client-fingerprint: "firefox"
    network: grpc
    grpc-opts:
      grpc-service-name: "cdn.v1.EsService"
  - name: "🇷🇺_5"
    type: vless
    server: "pl.avroraservice.online"
    port: 443
    uuid: "0dca2cfe-98eb-4f9d-9a47-cf87510c558b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl.avroraservice.online"
    client-fingerprint: "random"
    network: grpc
    grpc-opts:
      grpc-service-name: "cdn.v1.PlService"
  - name: "🇷🇺_6"
    type: vless
    server: "155.212.141.4"
    port: 443
    uuid: "3ec45835-1201-4f94-b1d6-2e1f909ec718"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "x4.megabitvpn.org"
    client-fingerprint: "random"
    reality-opts:
      public-key: "b5VaXsT5MRRBTqUeSC4vSCgX_Jb9oEsSaoAoUGkihG0"
      short-id: "bcdc67aebc7e14cf"
    network: grpc
    grpc-opts:
      grpc-service-name: "MSKUSAGRPC"
  - name: "🇷🇺_7"
    type: vless
    server: "195.133.73.65"
    port: 443
    uuid: "ebd1c0d6-7ff4-4b9f-8692-237517a27a64"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "anyfile2file.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "mza5Hn1aolSz65qu-UwvBP3oesxMe25r11o4nxvikF0"
      short-id: "64c1fe36c7846400"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_8"
    type: vless
    server: "45.12.75.242"
    port: 26424
    uuid: "633f424e-2b11-48da-a6b3-a849dd71456f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ya.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0"
      short-id: "23103e1e"
  - name: "🇷🇺_9"
    type: vless
    server: "x4.megabitvpn.org"
    port: 443
    uuid: "3ec45835-1201-4f94-b1d6-2e1f909ec718"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "x4.megabitvpn.org"
    client-fingerprint: "random"
    reality-opts:
      public-key: "b5VaXsT5MRRBTqUeSC4vSCgX_Jb9oEsSaoAoUGkihG0"
      short-id: "bcdc67aebc7e14cf"
    network: grpc
    grpc-opts:
      grpc-service-name: "MSKUSAGRPC"
  - name: "🇷🇺_10"
    type: vless
    server: "orm.g4m1.biz"
    port: 443
    uuid: "0dca2cfe-98eb-4f9d-9a47-cf87510c558b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "orm.g4m1.biz"
    client-fingerprint: "random"
    network: grpc
    grpc-opts:
      grpc-service-name: "cdn.v1.PlService"
  - name: "🇷🇺_11"
    type: vless
    server: "tgfree.rush-server.com"
    port: 443
    uuid: "ebd1c0d6-7ff4-4b9f-8692-237517a27a64"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "anyfile2file.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "mza5Hn1aolSz65qu-UwvBP3oesxMe25r11o4nxvikF0"
      short-id: "64c1fe36c7846400"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_12"
    type: vless
    server: "nl.g4m1.biz"
    port: 443
    uuid: "0dca2cfe-98eb-4f9d-9a47-cf87510c558b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nl.g4m1.biz"
    client-fingerprint: "chrome"
    network: grpc
    grpc-opts:
      grpc-service-name: "cdn.v1.NlService"
  - name: "🇷🇺_13"
    type: trojan
    server: "185.241.195.185"
    port: 2224
    password: "WaGG8TGpKhcMU-F-e9vrjB7MnUHGPhtt"
    sni: "vkc9.secured-by-tenzo.sbs"
    skip-cert-verify: true
    udp: true
  - name: "🇷🇺_14"
    type: trojan
    server: "188.225.37.70"
    port: 11443
    password: "WaGG8TGpKhcMU-F-e9vrjB7MnUHGPhtt"
    sni: "msk1.cenza.cloud"
    skip-cert-verify: true
    udp: true
  - name: "🇷🇺_15"
    type: trojan
    server: "ru-1.krugvpn.com"
    port: 443
    password: "jj59d0f73f5d6"
    sni: "ru-1.krugvpn.com"
    skip-cert-verify: true
    udp: true
  - name: "🇷🇺_16"
    type: trojan
    server: "217.16.17.127"
    port: 25565
    password: "WaGG8TGpKhcMU-F-e9vrjB7MnUHGPhtt"
    sni: "vkc2.safesurf.cloud"
    skip-cert-verify: true
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇷🇺_17"
    type: trojan
    server: "tr-wien.unlimited-access.ru"
    port: 443
    password: "kxHw-Dk-e9dffgzYszMlEqLJ92AnY3Pi"
    sni: "tr-wien.unlimited-access.ru"
    skip-cert-verify: true
    udp: true
  - name: "🇷🇺_18"
    type: ss
    server: "46.17.40.25"
    port: 20998
    cipher: "aes-256-gcm"
    password: "6b39ae3234dfd68b"
    udp: true
  - name: "🇷🇺_19"
    type: ss
    server: "46.17.40.25"
    port: 20998
    cipher: "aes-256-gcm"
    password: "6b39ae3234dfd68b"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇷🇺_1"
      - "🇷🇺_2"
      - "🇷🇺_3"
      - "🇷🇺_4"
      - "🇷🇺_5"
      - "🇷🇺_6"
      - "🇷🇺_7"
      - "🇷🇺_8"
      - "🇷🇺_9"
      - "🇷🇺_10"
      - "🇷🇺_11"
      - "🇷🇺_12"
      - "🇷🇺_13"
      - "🇷🇺_14"
      - "🇷🇺_15"
      - "🇷🇺_16"
      - "🇷🇺_17"
      - "🇷🇺_18"
      - "🇷🇺_19"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇷🇺_1"
      - "🇷🇺_2"
      - "🇷🇺_3"
      - "🇷🇺_4"
      - "🇷🇺_5"
      - "🇷🇺_6"
      - "🇷🇺_7"
      - "🇷🇺_8"
      - "🇷🇺_9"
      - "🇷🇺_10"
      - "🇷🇺_11"
      - "🇷🇺_12"
      - "🇷🇺_13"
      - "🇷🇺_14"
      - "🇷🇺_15"
      - "🇷🇺_16"
      - "🇷🇺_17"
      - "🇷🇺_18"
      - "🇷🇺_19"

rules:
  - MATCH,PROXY
