name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇸🇪_1"
    type: vless
    server: "185.186.78.111"
    port: 443
    uuid: "fbb74aa8-b89a-4f20-9504-6b25aadf6681"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "swed2.freeinternat.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bZpzmeWiEJyJQy0W2hHc34Nr6BuFXj1UDd80Cbwh1Fk"
      short-id: "ff776ff77be48b88"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_2"
    type: vless
    server: "31.77.111.11"
    port: 43439
    uuid: "428e923f-e608-412b-9e51-3b09ffab551f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn.higames.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b4n1pcO8ST3JkGtj8YymXVrW17LEe2EHec5wY7hMMR4"
      short-id: "39ad36226f3abec8"
    network: grpc
    grpc-opts:
      grpc-service-name: "streaming"
  - name: "🇸🇪_3"
    type: vless
    server: "185.58.115.34"
    port: 443
    uuid: "1b627e4d-4ea4-4dce-8bd8-fc2d3ffbeaba"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "restore.anti-zapret.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "0AVsyS7udTbxKRdSyQ2rtFC63icDQOVWq8FvAhhU-WY"
      short-id: "cbb0a5c1dc905505"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_4"
    type: vless
    server: "185.58.115.166"
    port: 443
    uuid: "1b627e4d-4ea4-4dce-8bd8-fc2d3ffbeaba"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "restore.anti-zapret.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "0AVsyS7udTbxKRdSyQ2rtFC63icDQOVWq8FvAhhU-WY"
      short-id: "cbb0a5c1dc905505"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_5"
    type: vless
    server: "143.246.198.91"
    port: 2054
    uuid: "80d02a71-54a5-4c5b-976d-5ee573c502af"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.ibm.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "z8O-5nI4-3eKexufSrkEUvAubPw7a73cQtTGNDp3Uxo"
      short-id: "6ffc74326185d4d6"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇸🇪_6"
    type: vless
    server: "143.246.198.91"
    port: 2054
    uuid: "d900a139-8b5f-4758-8a32-389c6f36fc86"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.ibm.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "z8O-5nI4-3eKexufSrkEUvAubPw7a73cQtTGNDp3Uxo"
      short-id: "6ffc74326185d4d6"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇸🇪_7"
    type: vless
    server: "swed2.freeinternat.com"
    port: 443
    uuid: "fbb74aa8-b89a-4f20-9504-6b25aadf6681"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "swed2.freeinternat.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bZpzmeWiEJyJQy0W2hHc34Nr6BuFXj1UDd80Cbwh1Fk"
      short-id: "ff776ff77be48b88"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_8"
    type: vless
    server: "2.27.57.154"
    port: 143
    uuid: "0a11d3b4-682c-4bfb-afb0-820b8285cb4b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ubuntu.com"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "6LSBBaOUWujvSovACjcP7m-DI9u9R584qdJxNYnu-24"
      short-id: "d1d36176bf36387e"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_9"
    type: vless
    server: "143.246.198.91"
    port: 2054
    uuid: "626c0789-16d1-4815-be8b-bd03959d7d12"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.ibm.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "z8O-5nI4-3eKexufSrkEUvAubPw7a73cQtTGNDp3Uxo"
      short-id: "6ffc74326185d4d6"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇸🇪_10"
    type: vless
    server: "185.58.115.232"
    port: 443
    uuid: "1b627e4d-4ea4-4dce-8bd8-fc2d3ffbeaba"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "restore.anti-zapret.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "0AVsyS7udTbxKRdSyQ2rtFC63icDQOVWq8FvAhhU-WY"
      short-id: "cbb0a5c1dc905505"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_11"
    type: vless
    server: "2.26.101.64"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nordic.cendora.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "YQTixaXzPVImuRc4TUbrFAekjIiaYV-t5S-HTKlH0AU"
      short-id: "2186a755ed67b034"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_12"
    type: vless
    server: "144.31.171.143"
    port: 13443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "auto.cendora.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "gc9oXe37KCCm3J1dJ03wdGsnxPBdeEkRPOvl_t-vfVM"
      short-id: "a7f3c91b2e6d84c0"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_13"
    type: vless
    server: "178.83.31.93"
    port: 443
    uuid: "4a97788b-5d8a-410c-875c-ba36930e185e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "989gq45ogQSZLDoUTcLNSYW5v_3ER7W_6Oi_8swZzXo"
      short-id: "cb55f541"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_14"
    type: vless
    server: "143.246.198.91"
    port: 2054
    uuid: "0a2988ed-9f42-499e-b4a8-3ed4cbda5457"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.ibm.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "z8O-5nI4-3eKexufSrkEUvAubPw7a73cQtTGNDp3Uxo"
      short-id: "6ffc74326185d4d6"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇸🇪_15"
    type: vless
    server: "restore.anti-zapret.com"
    port: 443
    uuid: "1b627e4d-4ea4-4dce-8bd8-fc2d3ffbeaba"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "restore.anti-zapret.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "0AVsyS7udTbxKRdSyQ2rtFC63icDQOVWq8FvAhhU-WY"
      short-id: "cbb0a5c1dc905505"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_16"
    type: vless
    server: "143.246.198.91"
    port: 2054
    uuid: "82d145c1-d691-4eef-9de1-9c316db4859a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.ibm.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "z8O-5nI4-3eKexufSrkEUvAubPw7a73cQtTGNDp3Uxo"
      short-id: "6ffc74326185d4d6"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇸🇪_17"
    type: vless
    server: "143.246.198.91"
    port: 2054
    uuid: "25d18f6f-f701-4da1-93d8-ec712f05963b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.ibm.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "z8O-5nI4-3eKexufSrkEUvAubPw7a73cQtTGNDp3Uxo"
      short-id: "6ffc74326185d4d6"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇸🇪_18"
    type: vless
    server: "143.246.198.91"
    port: 2054
    uuid: "0e75f6ee-9a4d-4019-8276-cacf388d2ec6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.ibm.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "z8O-5nI4-3eKexufSrkEUvAubPw7a73cQtTGNDp3Uxo"
      short-id: "6ffc74326185d4d6"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇸🇪_19"
    type: vless
    server: "143.246.198.91"
    port: 2054
    uuid: "4fe19d97-7b1d-4cb2-99ee-4bd8658a4c34"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.ibm.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "z8O-5nI4-3eKexufSrkEUvAubPw7a73cQtTGNDp3Uxo"
      short-id: "6ffc74326185d4d6"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇸🇪_20"
    type: vless
    server: "144.31.171.143"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-central.cendora.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b-Cm9hX-3UHsS1L_lnUB6AMjuKhlN1IDdBbZ506itjI"
      short-id: "00bca5982f82d083"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_21"
    type: vless
    server: "45.196.161.208"
    port: 443
    uuid: "66824c94-7ba9-4113-908e-bd793f296852"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "storage.yandex.net"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "pPi-WO8qQFFZ9UJWNLW9YClbjcoAAZWJQ2_FM3Kjhz8"
      short-id: "500aec9e9e5e2212"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_22"
    type: trojan
    server: "194.87.77.91"
    port: 443
    password: "1234567890"
    sni: "kfm-bn0.pages.dev"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇪_23"
    type: trojan
    server: "65.20.113.246"
    port: 443
    password: "Bw5Mz7QkVp"
    sni: "z-v2-074389.kailib.com"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇪_24"
    type: trojan
    server: "70.34.206.32"
    port: 443
    password: "Bw5Mz7QkVp"
    sni: "z-v2-077787.kailib.com"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇪_25"
    type: trojan
    server: "185.117.89.88"
    port: 9443
    password: "e72c6ea7e61f4dcea568aa569fb9b771"
    sni: "apple.com"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇪_26"
    type: trojan
    server: "45.91.171.116"
    port: 443
    password: "2ee85121-31de-4581-a492-eb00f606e392"
    sni: "sto.freeguard.org"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇸🇪_1"
      - "🇸🇪_2"
      - "🇸🇪_3"
      - "🇸🇪_4"
      - "🇸🇪_5"
      - "🇸🇪_6"
      - "🇸🇪_7"
      - "🇸🇪_8"
      - "🇸🇪_9"
      - "🇸🇪_10"
      - "🇸🇪_11"
      - "🇸🇪_12"
      - "🇸🇪_13"
      - "🇸🇪_14"
      - "🇸🇪_15"
      - "🇸🇪_16"
      - "🇸🇪_17"
      - "🇸🇪_18"
      - "🇸🇪_19"
      - "🇸🇪_20"
      - "🇸🇪_21"
      - "🇸🇪_22"
      - "🇸🇪_23"
      - "🇸🇪_24"
      - "🇸🇪_25"
      - "🇸🇪_26"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇸🇪_1"
      - "🇸🇪_2"
      - "🇸🇪_3"
      - "🇸🇪_4"
      - "🇸🇪_5"
      - "🇸🇪_6"
      - "🇸🇪_7"
      - "🇸🇪_8"
      - "🇸🇪_9"
      - "🇸🇪_10"
      - "🇸🇪_11"
      - "🇸🇪_12"
      - "🇸🇪_13"
      - "🇸🇪_14"
      - "🇸🇪_15"
      - "🇸🇪_16"
      - "🇸🇪_17"
      - "🇸🇪_18"
      - "🇸🇪_19"
      - "🇸🇪_20"
      - "🇸🇪_21"
      - "🇸🇪_22"
      - "🇸🇪_23"
      - "🇸🇪_24"
      - "🇸🇪_25"
      - "🇸🇪_26"

rules:
  - MATCH,PROXY
