name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇸🇪_1"
    type: vless
    server: "13.249.8.21"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇸🇪_2"
    type: vless
    server: "2.26.55.164"
    port: 443
    uuid: "2cb6b4d9-0c74-45e2-a4fb-645bb8ac532a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "swed4.o4ka-internet.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "V2JprbR_aJkS7uX6anyU3nrswGxdvDQT2HpY4WnzuC8"
      short-id: "5629431325884ff0"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_3"
    type: vless
    server: "41.216.182.105"
    port: 443
    uuid: "e911c552-3a98-41e0-b5fb-0dd3879887b7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vod.ensf.top"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/api/v1/irc"
      headers:
        Host: "vod.ensf.top"
  - name: "🇸🇪_4"
    type: vless
    server: "103.110.66.158"
    port: 443
    uuid: "218fd696-e3a2-4c33-b397-a5f13a82969e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.telekom.de"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "ECYE8G81FW1V__Y9yBYxIU0TWWcConhXoJncZG1D_0U"
      short-id: "7a08844f"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇸🇪_5"
    type: vless
    server: "13.249.8.83"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇸🇪_6"
    type: vless
    server: "13.249.8.3"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇸🇪_7"
    type: vless
    server: "13.249.8.113"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇸🇪_8"
    type: vless
    server: "77.221.136.148"
    port: 443
    uuid: "e911c552-3a98-41e0-b5fb-0dd3879887b7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vod.ensf.top"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/api/v1/irc"
      headers:
        Host: "vod.ensf.top"
  - name: "🇸🇪_9"
    type: vless
    server: "usa-01.node.lumixnet.com"
    port: 443
    uuid: "8645697d-51c1-4e90-aca5-ba63a0392f11"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "usa-01.node.lumixnet.com"
    client-fingerprint: "hellochrome_120"
    reality-opts:
      public-key: "vEXgvoW9iQo6iiKT71cNt1CC3cAB4IWswAn-cScDz1A"
      short-id: "bd8a588cebc3395a"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_10"
    type: trojan
    server: "185.117.89.88"
    port: 9443
    password: "e72c6ea7e61f4dcea568aa569fb9b771"
    sni: "apple.com"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇪_11"
    type: trojan
    server: "45.91.171.116"
    port: 443
    password: "2ee85121-31de-4581-a492-eb00f606e392"
    sni: "sto.freeguard.org"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇪_12"
    type: trojan
    server: "194.87.77.91"
    port: 443
    password: "1234567890"
    sni: "kfm-bn0.pages.dev"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇪_13"
    type: trojan
    server: "77.221.138.199"
    port: 8443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "🇸🇪_14"
    type: trojan
    server: "65.20.113.246"
    port: 443
    password: "Bw5Mz7QkVp"
    sni: "z-v2-074389.kailib.com"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇪_15"
    type: trojan
    server: "70.34.206.32"
    port: 443
    password: "Bw5Mz7QkVp"
    sni: "z-v2-077787.kailib.com"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇪_16"
    type: ss
    server: "45.138.103.4"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "YjM0M"
    udp: true
  - name: "🇸🇪_17"
    type: ss
    server: "45.138.103.4"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "YjM0M"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇸🇪_1"
      - "🇸🇪_2"
      - "🇸🇪_3"
      - "🇸🇪_4"
      - "🇸🇪_5"
      - "🇸🇪_6"
      - "🇸🇪_7"
      - "🇸🇪_8"
      - "🇸🇪_9"
      - "🇸🇪_10"
      - "🇸🇪_11"
      - "🇸🇪_12"
      - "🇸🇪_13"
      - "🇸🇪_14"
      - "🇸🇪_15"
      - "🇸🇪_16"
      - "🇸🇪_17"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇸🇪_1"
      - "🇸🇪_2"
      - "🇸🇪_3"
      - "🇸🇪_4"
      - "🇸🇪_5"
      - "🇸🇪_6"
      - "🇸🇪_7"
      - "🇸🇪_8"
      - "🇸🇪_9"
      - "🇸🇪_10"
      - "🇸🇪_11"
      - "🇸🇪_12"
      - "🇸🇪_13"
      - "🇸🇪_14"
      - "🇸🇪_15"
      - "🇸🇪_16"
      - "🇸🇪_17"

rules:
  - MATCH,PROXY
