name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇸🇪_1"
    type: vless
    server: "84.238.133.186"
    port: 443
    uuid: "ae8e0f7d-b661-41ca-b55d-d8c383adb2f8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "swed2.helper-internet.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "pgG2grngQEtOFJImLfz0AEm-O2IodM2jCY4aMCYQI1U"
      short-id: "6aa2d2e950441a9a"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_2"
    type: vless
    server: "84.238.133.104"
    port: 443
    uuid: "ae8e0f7d-b661-41ca-b55d-d8c383adb2f8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "swed2.helper-internet.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "pgG2grngQEtOFJImLfz0AEm-O2IodM2jCY4aMCYQI1U"
      short-id: "6aa2d2e950441a9a"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_3"
    type: vless
    server: "2.26.101.64"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nordic.cendora.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "YQTixaXzPVImuRc4TUbrFAekjIiaYV-t5S-HTKlH0AU"
      short-id: "2186a755ed67b034"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_4"
    type: vless
    server: "193.148.59.178"
    port: 443
    uuid: "20d7c485-5d24-49b5-a5cc-bb7a7daf9908"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "-GMpCber8qtrKzJbwvpLcwlIhOy-5zS66u_x9lLvIjE"
      short-id: "e3daad69"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_5"
    type: vless
    server: "2.27.23.115"
    port: 443
    uuid: "d53f098c-c146-4c16-b8fc-263743fdb6b3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "swplay.tgflow.me"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "qoahUemfDpTEl1IMf8gMj4RIDILO2dT0MKWVMvRCrU4"
      short-id: "b0982475784c64cc"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_6"
    type: vless
    server: "31.76.81.9"
    port: 443
    uuid: "c47b421f-65f1-4190-b7ba-bd2045086fe4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "diw5L3O4EkRQGWDSfdpQooPUc3zBTItooeOQ_fIDFWI"
      short-id: "7f2e9c4b1a8d6e53"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_7"
    type: trojan
    server: "45.91.171.116"
    port: 443
    password: "2ee85121-31de-4581-a492-eb00f606e392"
    sni: "sto.freeguard.org"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇪_8"
    type: trojan
    server: "5.180.21.146"
    port: 4443
    password: "owefv0_92Z540k2F_nx83245_J9130oS_tY"
    sni: "borat-hopp.bumbleshrimp.com"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇪_9"
    type: trojan
    server: "70.34.206.32"
    port: 443
    password: "Bw5Mz7QkVp"
    sni: "z-v2-077787.kailib.com"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇪_10"
    type: trojan
    server: "65.20.113.246"
    port: 443
    password: "Bw5Mz7QkVp"
    sni: "z-v2-074389.kailib.com"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇸🇪_1"
      - "🇸🇪_2"
      - "🇸🇪_3"
      - "🇸🇪_4"
      - "🇸🇪_5"
      - "🇸🇪_6"
      - "🇸🇪_7"
      - "🇸🇪_8"
      - "🇸🇪_9"
      - "🇸🇪_10"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇸🇪_1"
      - "🇸🇪_2"
      - "🇸🇪_3"
      - "🇸🇪_4"
      - "🇸🇪_5"
      - "🇸🇪_6"
      - "🇸🇪_7"
      - "🇸🇪_8"
      - "🇸🇪_9"
      - "🇸🇪_10"

rules:
  - MATCH,PROXY
