name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇹🇷_1"
    type: vless
    server: "91.228.227.172"
    port: 8080
    uuid: "367111be-17b4-4abc-aae0-3d7fe72aa3ec"
    udp: true
  - name: "🇹🇷_2"
    type: vless
    server: "185.123.100.56"
    port: 8443
    uuid: "78eb4455-0d07-4bc2-93e3-7c8654f11d74"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "EltWI8AOqkN8lMjRycweRRoFRah5hu6xiKtgBmQOdE8"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_3"
    type: vless
    server: "premium-tr.geodema.network"
    port: 8443
    uuid: "78eb4455-0d07-4bc2-93e3-7c8654f11d74"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "EltWI8AOqkN8lMjRycweRRoFRah5hu6xiKtgBmQOdE8"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_4"
    type: vless
    server: "parta3.api3-max.ru"
    port: 443
    uuid: "5999a497-a2da-41d0-92cb-5b758082f83c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "parta3.api3-max.ru"
    client-fingerprint: "edge"
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_5"
    type: vless
    server: "156.67.63.231"
    port: 443
    uuid: "b052df40-d51c-456c-9bd6-57af01a87e4e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sync-bridge.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "PTqeBbbr2xJ1L3V1PyYjKjxanMKKqJHU-wtnpYmFQCI"
      short-id: "5606d4a25c99e7af"
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_6"
    type: vless
    server: "198.105.123.79"
    port: 443
    uuid: "5999a497-a2da-41d0-92cb-5b758082f83c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "parta3.api3-max.ru"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_7"
    type: vless
    server: "151.241.226.201"
    port: 2053
    uuid: "e691b034-dfc9-4f22-80aa-6d4f6404a4df"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "k5COjpopVNGzEuMb457zCrrZegSdBX-d8bg0G6HDsE4"
      short-id: "9bd613c48251f0db"
  - name: "🇹🇷_8"
    type: trojan
    server: "195.162.69.238"
    port: 9443
    password: "ac8ae2c29cd149eb85cae990572f0d59"
    sni: "apple.com"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇹🇷_1"
      - "🇹🇷_2"
      - "🇹🇷_3"
      - "🇹🇷_4"
      - "🇹🇷_5"
      - "🇹🇷_6"
      - "🇹🇷_7"
      - "🇹🇷_8"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇹🇷_1"
      - "🇹🇷_2"
      - "🇹🇷_3"
      - "🇹🇷_4"
      - "🇹🇷_5"
      - "🇹🇷_6"
      - "🇹🇷_7"
      - "🇹🇷_8"

rules:
  - MATCH,PROXY
