name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇹🇷_1"
    type: vless
    server: "91.124.63.229"
    port: 443
    uuid: "acc50200-7f21-4f90-9cca-0057efcbf042"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.ya.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "rNBFVzV18kAj_ei4AqsgZywzmvD36WK9hcRdVnpHPAM"
      short-id: "c0573c8280a0c019"
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_2"
    type: vless
    server: "185.39.204.155"
    port: 8443
    uuid: "1f29762d-3f23-4207-9e39-f774de5d49ba"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇹🇷_3"
    type: vless
    server: "dp-tr-01.live"
    port: 443
    uuid: "b1787456-cc54-4191-99e9-c609bf7c2853"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "storage.yandex.net"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "zii4nGNapnFKL6SN8GzWNqFlElBvUCUFUThEP0kFH04"
      short-id: "c6ef72e4635d15a5"
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_4"
    type: trojan
    server: "195.162.69.238"
    port: 9443
    password: "ac8ae2c29cd149eb85cae990572f0d59"
    sni: "apple.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇷_5"
    type: trojan
    server: "dem.yariresanbot.ir"
    port: 39594
    password: "77a4056f31f24ea592bb7aa1e88aced4"
    sni: "dem.yariresanbot.ir"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇷_6"
    type: trojan
    server: "193.111.125.82"
    port: 39594
    password: "77a4056f31f24ea592bb7aa1e88aced4"
    sni: "dem.yariresanbot.ir"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇷_7"
    type: ss
    server: "31.210.78.66"
    port: 1080
    cipher: "chacha20-ietf-poly1305"
    password: "XF0klw7870vXn3uQIxe19Q"
    udp: true
  - name: "🇹🇷_8"
    type: ss
    server: "Vpna.Poorifast.ir"
    port: 1080
    cipher: "chacha20-ietf-poly1305"
    password: "rYfi4cQ3z7zts7BO4-Y9_A"
    udp: true
  - name: "🇹🇷_9"
    type: ss
    server: "38.180.113.194"
    port: 8119
    cipher: "aes-256-gcm"
    password: "cdBIDV42DCwnfIN"
    udp: true
  - name: "🇹🇷_10"
    type: ss
    server: "185.123.101.64"
    port: 2376
    cipher: "aes-256-gcm"
    password: "faBAoD54k87UJG7"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇹🇷_1"
      - "🇹🇷_2"
      - "🇹🇷_3"
      - "🇹🇷_4"
      - "🇹🇷_5"
      - "🇹🇷_6"
      - "🇹🇷_7"
      - "🇹🇷_8"
      - "🇹🇷_9"
      - "🇹🇷_10"


rules:
  - MATCH,PROXY
