name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇹🇷_1"
    type: vless
    server: "93.190.9.10"
    port: 3090
    uuid: "2ff150f3-705a-4699-ba63-3dd743942a67"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇹🇷_2"
    type: vless
    server: "93.190.9.2"
    port: 3090
    uuid: "eeccb1d3-2d30-439e-b4c7-895f84c41f03"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇹🇷_3"
    type: vless
    server: "167.104.219.66"
    port: 18361
    uuid: "My-chanel-Telegram-ATOVPN "
    udp: true
  - name: "🇹🇷_4"
    type: vless
    server: "185.87.24.173"
    port: 2085
    uuid: "3f654175-4f83-47ec-8ce2-f2bf0d160b27"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇹🇷_5"
    type: vless
    server: "104.245.240.9"
    port: 8443
    uuid: "bb20d3fc-fc15-0935-11c5-82775c39e6b0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "download.nvidia.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "D2SXHZRRYM0WcFChGWd57XB-U73aIsGfMpe2-Gq5XSs"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "TunService"
  - name: "🇹🇷_6"
    type: vless
    server: "151.241.226.201"
    port: 2053
    uuid: "0eed6293-8cf1-4e77-ac10-9c3d50d0b2f8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bYW_MmB_CUHrsyoCAUKviI2LZdHf63yY2yOPXbih104"
      short-id: "9e419c0759b54d6f"
  - name: "🇹🇷_7"
    type: vless
    server: "194.87.59.13"
    port: 2085
    uuid: "6687af93-eb39-47a3-9a73-0f79234ef507"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇹🇷_8"
    type: vless
    server: "78.135.73.47"
    port: 443
    uuid: "25e16692-d097-4e69-9e2d-8415609c1968"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.datadoghq.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "sZAJkAu23wp1WKY-qeaeiwR38izP5OyfhumoE9xhbB8"
      short-id: "f46cd3ea3d1eb72d"
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_9"
    type: vless
    server: "93.190.9.24"
    port: 3090
    uuid: "f68a9fd4-16c7-46d1-b17c-0a4b224cc00d"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇹🇷_10"
    type: vless
    server: "93.190.9.23"
    port: 3090
    uuid: "2ff150f3-705a-4699-ba63-3dd743942a67"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇹🇷_11"
    type: vless
    server: "93.190.8.19"
    port: 3090
    uuid: "6687af93-eb39-47a3-9a73-0f79234ef507"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇹🇷_12"
    type: vless
    server: "93.190.9.16"
    port: 3090
    uuid: "77d89693-d043-402d-ba6b-5adacf705da4"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇹🇷_13"
    type: vless
    server: "tr.plus-hit.ru"
    port: 443
    uuid: "84a794a5-2420-4ca7-8e08-8d21571f36f3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tr.plus-hit.ru"
    client-fingerprint: "random"
    reality-opts:
      public-key: "d3yQvdpwFHpLkl0ZbTnMH4uihCTKn4CAHy0W6so0VTI"
      short-id: "7c8e3d4a9b1f26d3"
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_14"
    type: trojan
    server: "subtu.charsoulink3.ir"
    port: 2087
    password: "v2whz6ahmyy2f84j"
    sni: "pus.mmdaqaorg2.ir"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇹🇷_1"
      - "🇹🇷_2"
      - "🇹🇷_3"
      - "🇹🇷_4"
      - "🇹🇷_5"
      - "🇹🇷_6"
      - "🇹🇷_7"
      - "🇹🇷_8"
      - "🇹🇷_9"
      - "🇹🇷_10"
      - "🇹🇷_11"
      - "🇹🇷_12"
      - "🇹🇷_13"
      - "🇹🇷_14"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇹🇷_1"
      - "🇹🇷_2"
      - "🇹🇷_3"
      - "🇹🇷_4"
      - "🇹🇷_5"
      - "🇹🇷_6"
      - "🇹🇷_7"
      - "🇹🇷_8"
      - "🇹🇷_9"
      - "🇹🇷_10"
      - "🇹🇷_11"
      - "🇹🇷_12"
      - "🇹🇷_13"
      - "🇹🇷_14"

rules:
  - MATCH,PROXY
